### ISSUE TITLE
[virtctl stop]: `--force` and `--grace-period` do not behave as documented

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#10211]
**What happened**:
When looking at the different `virtctl stop` argument documentations via `virtctl stop --help`, we can see:
```bash
Flags:
      --force              --force=false: Only used when grace-period=0. If true, immediately remove VMI pod from API and bypass graceful deletion. Note that immediate deletion of some resources may result in inconsistency or data loss and requires confirmation.
      --grace-period int   --grace-period=-1: Period of time in seconds given to the VMI to terminate gracefully. Can only be set to 0 when --force is true (force deletion). Currently only setting 0 is supported. (default -1)
```

However, both of these argument behave different than explained. Let's discuss them one by one.

<ins>--grace-period argument</ins>:
When virt-handler [processes vm shutdown](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-handler/vm.go#L2205)[1], it checks if the grace period has expired. If it didn't, virt-handler uses `handleVMIShutdown()` which in turn uses [ACPI](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-launcher/virtwrap/manager.go#L1634)[2] to shutdown the guest gracefully.

However, if the grace period did expire, [KillVirtualMachine()](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-handler/vm.go#L2223)[3] is being called. In turn, libvirt shuts down the guest, but still [does so gracefully](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-launcher/virtwrap/manager.go#L1677)[4].

**Problems**:
1. The grace-period for VMIs behaves very different than the grace-period for pods. For pods, grace-period defines the time between graceful shutdown and the unmerciful killing of the processes. In other words, in regular pods when the grace period expires the pod dies instantly - while for VMIs when the grace period expires libvirt switches from using one type of graceful termination (via ACPI) and another type of graceful termination (using `DOMAIN_DESTROY_GRACEFUL` flag).
2. The documentation says: "Period of time in seconds given to the VMI to terminate gracefully". This description conflicts with the actual behavior.

<ins>--force argument</ins>:
As can be seen, when a `virtctl stop` [command is used](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virtctl/vm/vm.go#L539) [5] it then uses either `ForceStop()` or `Stop()` functions. However, these two functions [are equivalent](https://github.com/kubevirt/kubevirt/blob/v1.0.0/staging/src/kubevirt.io/client-go/kubecli/vm.go#L217)[6].

The only difference between the two functions is the `StopOptions` argument that's provided to them - with `ForceStop()` the [grace period is passed](https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virtctl/vm/vm.go#L545)[7] and with `Stop()` it isn't.

**Problems**:
1. Once again the argument's behavior is different between regular pods and VMs. With regular pods, `--force` means that k8s won't wait for the object to be deleted from etcd. Here the effect is minimal and only affects grace period, which is also flawed as explained above.
2. This argument behaves differently than documented: "immediately remove VMI pod from API and bypass graceful deletion".

**What you expected to happen**:
1. The arguments' behavior should be clear, simple and easy to understand.
2. The behavior should satisfy what's explained in the documentation.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.27.3

[1] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-handler/vm.go#L2205
[2] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-launcher/virtwrap/manager.go#L1634
[3] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-handler/vm.go#L2223
[4] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virt-launcher/virtwrap/manager.go#L1677
[5] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virtctl/vm/vm.go#L539
[6] https://github.com/kubevirt/kubevirt/blob/v1.0.0/staging/src/kubevirt.io/client-go/kubecli/vm.go#L217
[7] https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/virtctl/vm/vm.go#L545

**Comment by prnaraya** [comment]
After looking at this a little bit more, I want to say the path forward here would involve a couple things:

1. Update the documentation for `--force` and `--grace-period` to more accurately reflect the actual behavior of these flags when using `virtctl stop` and `virtctl restart`
2. Change the behavior of the `--grace-period` flag to be more in line with the way `kubectl` uses it. With this approach, I am not sure that the `--force` flag would even be necessary since the `--grace-period` implies that after the grace period expires, the VMI will be killed. Alternatively, we can leave the grace-period functioning as is (and change the docs to reflect this behavior), using `--force` to indicate killing the VMI without the grace period (or allowing `--grace-period` and `--force` to both be set and kill the VMI rather than attempt another graceful termination when the grace period expires).
3. Functionally, the methods for `ForceStop` and `Stop` (and likewise, `ForceRestart` and `Restart`) behave almost identically aside from the force functions making the API call and passing the grace period. We can probably refactor this to just use a single `Stop` or `Restart` method.
