### ISSUE TITLE
Clone vm cross namespace.

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10280]
**Is your feature request related to a problem? Please describe**:
We can't clone vm cross namespace as well as restore a vm from vmsnapshot to another namespace.

**Describe the solution you'd like**:
 I would like the ability to set the target VM namespace in `VirtualMachineRestore`or somewhere, and use this namespace in vmRestoreTarget.Reconcile() method to set namespace for targetvm.

**Describe alternatives you've considered**:
None

**Additional context**:
I don't know if I didn't read the documentation carefully and the solution is a rough idea. Any discussion is welcome.

**Comment by xpivarc** [comment]
FYI @iholder101

**Comment by iholder101** [comment]
> FYI @iholder101

@xpivarc Thanks for the FYI!

-------

@Longchuanzheng Thanks very much for bringing this up.
This topic was brought up a few times before and is indeed something we want to support.

VM Clones are based on `VirtualMachineSnapshot`s, which in turn are based on `VolumeSnapshot`s.
So, in order to support a cross-namespace clone we first need to support cross-namespace VMsnapshots.

Also, I would appreciate it if you can explain more about your use-case.

@ShellyKa13 @mhenriks: can you keep me honest here? do we plan to support VMsnapshots anytime soon? Are there any technical barriers here?

**Comment by mhenriks** [comment]
Cross namespace authorization is a pain.  We rolled our own for DataVolume cross namespace cloning.  For VMSnapshot/VMClone, I say we wait for the community standard discussed here to go beta:  https://kubernetes.io/blog/2023/01/02/cross-namespace-data-sources-alpha/
