### ISSUE TITLE
k8s kube-apiserver report some errlog when install kubevirt v1.0.0

### ISSUE THREAD

**Issue by caijian76** [kubevirt/kubevirt#10338]
```
E0825 16:18:50.570760       1 controller.go:113] loading OpenAPI spec for "v1.subresources.kubevirt.io" failed with: Error, could not get list of group versions for APIService
I0825 16:18:50.570782       1 controller.go:126] OpenAPI AggregationController: action for item v1.subresources.kubevirt.io: Rate Limited Requeue.
E0825 16:18:50.573848       1 controller.go:113] loading OpenAPI spec for "v1alpha3.subresources.kubevirt.io" failed with: Error, could not get list of group versions for APIService
I0825 16:18:50.573859       1 controller.go:126] OpenAPI AggregationController: action for item v1alpha3.subresources.kubevirt.io: Rate Limited Requeue.
```

the same log will repeat 1 min

**Comment by aburdenthehand** [comment]
Does KubeVirt install regardless? We have seen in the past this issue, where KubeVirt installs but the error gets logged: https://github.com/kubevirt/kubevirt/issues/9725

If not, it might help to know your environment details.

**Comment by starcraft66** [comment]
I'm seeing this constant spam in my kube-apiserver logs.

**Comment by aburdenthehand** [comment]
@starcraft66 What version of k8s and kubevirt are you running?

**Comment by berlineric** [comment]
same here.
k8s 1.26.8
kubevirt 1.1.0

api-logs spammed as hell.

**Comment by tiraboschi** [comment]
checking virt-api pods logs I see:
`2024-04-07T09:45:21.077587774Z {"component":"virt-api","level":"info","msg":"setting rate limiter for the API to 5 QPS and 10 Burst","pos":"api.go:1097","timestamp":"2024-04-07T09:45:21.072417Z"}`

so virt-api is setting a rate limit of 5 queries per second with a burst of 10.

This is probably exceeded during the installation due to many request in a short sequence, but it simply means that we are hitting the rate limit and the request is delayed by requeuing but this is definitively harmless if the install is then fine.

This is not systematic depending on the speed of the hardware, maybe we can fine-tune the rate limit on virt-api to prevent this noise.

**Comment by xpivarc** [comment]
The root cause is missing `/openapi/v3` endpoint. It should not have any functional impact. We would welcome a PR if anyone would be interested.
