### ISSUE TITLE
Support ephemeral volumes with containerDisk

### ISSUE THREAD

**Issue by dimm0** [kubevirt/kubevirt#10368]
**Is your feature request related to a problem? Please describe**:
I'm trying to run some VMs with quay.io/containerdisks/ubuntu containerDisk image. It starts fine, but the root partition is only 2GB (I assume that's the size of ubuntu qcow2 image?), and I can't really install any more packages.

I can create another image with CDI, but that's way less convenient than simply using a container image.

I see there's an option to have the ephemeral volumes with COW, which can solve it - all writes will go on local disk and I'll have more space. But it only supports PVC's currently.

**Describe the solution you'd like**:
Support ephemeral storage with containerDisk images (read from containerDisk, write to emptyDir)

**Describe alternatives you've considered**:
Is there a way to resize the root containerDisk partition on start?

**Comment by alicefr** [comment]
@dimm0 The image inside the containerdisk is the size of the raw/qcow image you created and put it in the container image. Nothing prevents you from making a larger image, but I strongly encourage you to use qcow2 format since container images don't support sparse files.

Generally, I would say that containerdisk are limited, so IMO creating another image with CDI is the right way to achieve what you want. You can create a [golden image](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/design.md#work-flow) and then VMs from that image.

You can also use PVC + ephemeral storage to achieve what you want. But if you still want to use container disks, then the first option is the only way I see.

**Comment by dimm0** [comment]
Got it, thanks
