### ISSUE TITLE
Use decorators for storage functional test instead of skips

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#10399]
/label good-first-issue

Right now we are using skips based on if a particular storage class with some attribute is defined in the cluster. If not a test is skipped. For instance if the test requires snapshots, the test checks in tests/default-config.json or tests/default-ceph-config.json if there is a storage class for it. If it is blank, then the test is skipped.

Instead of checking that, we should use a decorator that we can associate with a test, then if that decorator is not enabled for the run, instead of skipping the test won't be in the test run at all, and no skips will be counted.

Decorators are defined here https://github.com/kubevirt/kubevirt/blob/main/tests/decorators/decorators.go
An example of skipping some decorators can be found here https://github.com/kubevirt/kubevirt/blob/main/automation/test.sh#L447

We need to add decorators for the different combinations of storage classes defined in https://github.com/kubevirt/kubevirt/blob/main/tests/default-ceph-config.json and https://github.com/kubevirt/kubevirt/blob/main/tests/default-config.json so we can stop using skips and start using decorators.

**Comment by Jay179-sudo** [comment]
Hi @awels! I'd like to contribute to this issue at hand! I would need some time and guidance with getting acquainted with the codebase.

**Comment by awels** [comment]
Okay so this is just cleaning up the functional tests in particular for storage. For example you will find a lot of this pattern in the test suite https://github.com/kubevirt/kubevirt/blob/main/tests/storage/snapshot.go#L314-L319 . Essentially what we are doing there is skipping the test if the storage class that is associated with a snapshot is blank. But this throws off testing numbers a bit since we don't want skipped tests. So instead of doing that we want to use a 'decorator'. The decorator is just a string that can be excluded for a particular test run, and will result in the test not being run, instead of skipped.

Now you will have to tell me how much you have looked into the code base, and if you are able to start a development cluster with `make cluster-up`. There is some configuration and setup needed before we can dive into the code.

**Comment by Jay179-sudo** [comment]
I also looked around the code a little bit and I made some notes on it. Could you please tell me if I am in the right track or not.

- We do not want to write the conditionals in the test (what we have been doing with returning an empty string). We want to replace it with decorators. The decorators will take care of running or not running the tests _entirely_ instead of entering a test and then deciding to skip it.
- We can set decorators to not run in the test.sh file by using ' add_to_label_filter '(!mylabel)' '&&' '. All these labels will be passed to Ginkgo and it will run only those tests whose decorators are set and will not run those tests whose corresponding decorators are not set. Is this correct? Are we mapping decorators to tests in some way?
- If we are mapping decorators to tests in some way, how would we decide to set (or not set) those decorators? Are we keeping some state variables that will help us? I noticed variables such as TARGET, KUBEVIRT_E2E_FOCUS, etc in the [test.sh](https://github.com/kubevirt/kubevirt/blob/main/automation/test.sh#L447) file. Are these relevant to the state? I see conditionals on TARGET that decides what decorators to set. How is the value of TARGET set?

Am I closer to understanding things or am I digging down the wrong rabbit hole? I am sorry if this is frustrating to you!

**Comment by awels** [comment]
Hi, so you are getting close the first two points are spot on. Think of a decorator as a label that is set on a test. When the test suite runs and it is told to use the label, the test is run, if the label is not set (!label) then it won't enter the test at all. By default all the labels are used.

Now the third point was confusing to me as well, essentially in our [CI configuration](github.com/kubevirt/project-infra) we set various combinations of environment variables in the CI job. Then the bash script disables the labels based on the variables.

Now what we need to happen is that we add a few new decorators (For the different combinations of storage class types found in the default-config.json file) and then we need to find all the skips and replace them with the decorator. We can assume that the environment variables are properly set in the CI jobs.

**Comment by prady0t** [comment]
@Jay179-sudo are you still working on this?
