### ISSUE TITLE
CPU Hotplug failures

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#10690]
**What happened**:
Flakes as https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10673/pull-kubevirt-e2e-k8s-1.28-sig-compute-migrations/1721470125107843072

exposes error messages that should not be present:

```
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvmi-wr2gd","namespace":"kubevirt-test-default1","pos":"server.go:202","reason":"not enough exclusive threads provided, could not fit 2 core(s)","timestamp":"2023-11-06T11:11:41.099883Z","uid":"132c50c2-8d82-4e49-8857-dc737adcd6cc"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled vmi migration","name":"testvmi-wr2gd","namespace":"kubevirt-test-default1","pos":"server.go:118","timestamp":"2023-11-06T11:11:41.353208Z","uid":"132c50c2-8d82-4e49-8857-dc737adcd6cc"}
```

**What you expected to happen**:

No error

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vladikr** [comment]
Interesting, we didn't see this before.
From the logs, it looks like the error came from the sync command failing on the source. The source virt-handler had enough time between the VM spec change and a (hot-plug) migration starting to issue a Sync().
(could be that we hit a parallel migration limit?)
In general, I think, the error on the source is harmless but shouldn't be raised or needs to be handled.

**Comment by enp0s3** [comment]
@vladikr Thank you for the information! I see many different issues:
* The test should read the domain XML from the target pod of the hot-plug migration, according to the failure log the test was reading the XML from the first manual migration target pod. This can happen because the [`GetRunningPodByLabel`](https://github.com/kubevirt/kubevirt/blob/d41b6ddb20837e4445a899be0dc492bde25beb26/tests/utils.go#L471) function doesn't guarantee to return the target pod.
* We have 2 VMIM objects, one created by the test and the other created by the workload updater due to hotplug. Both were created in different time slots and still they point to the same target pod `virt-launcher-testvmi-wr2gd-sc7f2`
* The migration we initiate in the test was marked as succeeded, although the migration target pod has the unhealthy domain due to the fit cores issue.
* I don't know yet how it happens, but the hot-plug migration is managed to run from an unhealthy domain, this is the domain where we see the SyncVMI failures, and actually the migration succeeded, we can see the target pod `virt-launcher-testvmi-wr2gd-sc7f2` which is ready and running, and the its launcher log indicates VCPU was updated:

```
{"component":"virt-launcher","kind":"","level":"info","msg":"VMI vCPUs has been updated","name":"testvmi-wr2gd","namespace":"kubevirt-test-default1","pos":"server.go:190","timestamp":"2023-11-06T11:11:43.036846Z","uid":"132c50c2-8d82-4e49-8857-dc737adcd6cc"}

```

**Comment by enp0s3** [comment]
I think I found at least one problematic place in [code](https://github.com/kubevirt/kubevirt/blob/d41b6ddb20837e4445a899be0dc492bde25beb26/pkg/virt-controller/watch/migration.go#L611). Here in the migration controller we aren't checking the migration phase as it was set by the virt-handler in the VMI status, we ignore the value of `vmi.Status.MigrationState.Failed` and then we cause the inconsistency between the reported phase in VMIM vs. the one in VMI status

**Comment by xpivarc** [comment]
@enp0s3 additionally what I observed is that the source pod is kept around for some time. That's why `GetRunningPodByLabel` is now flaky. @vladikr I do not remember this was ever a problem before hotplug, maybe we slowed down somewhere?

> Interesting, we didn't see this before. From the logs, it looks like the error came from the sync command failing on the source. The source virt-handler had enough time between the VM spec change and a (hot-plug) migration starting to issue a Sync(). (could be that we hit a parallel migration limit?) In general, I think, the error on the source is harmless but shouldn't be raised or needs to be handled.

Yeah, good observation. Still, this needs to be resolved as this is a valid state. BTW, do we really need to re-fit the cores? (no)




> I think I found at least one problematic place in [code](https://github.com/kubevirt/kubevirt/blob/d41b6ddb20837e4445a899be0dc492bde25beb26/pkg/virt-controller/watch/migration.go#L611). Here in the migration controller we aren't checking the migration state as it was set by the virt-handler in the VMI status, we ignore the value of `vmi.Status.MigrationState.Failed` and then we cause the inconsistency between the reported phase in VMIM vs. the one in VMI status

The failed case should be handled before, can you check?

**Comment by enp0s3** [comment]
@xpivarc Checked, indeed its handled before, so the flow is correct. I think I've found the problem - the [`GetCPUTopology`](https://github.com/kubevirt/kubevirt/blob/99b5d4c79b8d990b92a62eb4b88fdb10b30f6105/pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go#L292) function in virt-launcher doesn't use the topology from the VMI status, but from the VMI spec. I suspect that when the VMI patching occurs, the SyncVMI comes with the changed topology and it obviously fails because the current cpu set cannot fit the new topology.

**Comment by enp0s3** [comment]
Since the `GetCPUTopology` is used in multiple contexts, I think we will have to distinguish between 2 cases, when we want the current CPU topology, and when we want the requested CPU topology.

**Comment by acardace** [comment]
https://github.com/kubevirt/kubevirt/pull/10835 is now merged in main.

**Comment by xpivarc** [comment]
@enp0s3 Do you have a PR for it?

**Comment by enp0s3** [comment]
@xpivarc Currently I don't have the BW for the virt-launcher refactoring effort, if you have something please update here with a ref link. Thanks!
