### ISSUE TITLE
CloneAPI: Clone triggers cloud-init to take effect

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10797]
**What happened**:
We create a vm which uses cloud-init to set user's password and we name it as vm1. Then we login the vm and change the password.
we create clone from vm1 and we name it vm2. The vm2 can't keep the password.

**What you expected to happen**:
I think the vm2 should keep the password no matther how many times we clone it. But in fact that the cloud-init will take effect. 

**How to reproduce it (as minimally and precisely as possible)**:
1. create vm1 and use cloud-init to change it's password
2. login vm1 and change password(for example) 
3. clone vm2 form vm1.
4. login vm2 to use the changing password.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
In my opinion, The target vm shouldn't contains Clouod-init-ConfigDrive when we execute the command of "clone". What do you think?

**Comment by matthewei** [comment]
@enp0s3 Hi sir, could you help me with this?

**Comment by enp0s3** [comment]
@matthewei Hi, sure, will take a look

/cc

**Comment by matthewei** [comment]
when we clone a vm, do we need to clone the disk of cloud-init?

**Comment by matthewei** [comment]
In my opinion,

**Comment by matthewei** [comment]
@enp0s3 could you tell me the progress?

**Comment by enp0s3** [comment]
@matthewei Hey, sorry I was overloaded a bit, I will take a look at it starting next week.

**Comment by enp0s3** [comment]
@matthewei Hi, each time you power off/on your VM, the VMI object is being re-created, also the libvirt XML is being re-created from scratch. The aim of fixing the UUID was to give a persistent view on your virtual HW from libvirt perspective, otherwise each time you power on the VM the UUID on libvirt side is being generated from scratch. 

I don't think it would be the right behavior to clone the UUID, to me it feels like the same issue with cloning a virtual TPM device for example.

Is it possible to make the cloud-init script leave a flag on the persistent filesystem, so that with the VM cloning the flag will be there and cloud-init won't try to change the password in the cloned VM?

**Comment by matthewei** [comment]
> @matthewei Hi, each time you power off/on your VM, the VMI object is being re-created, also the libvirt XML is being re-created from scratch. The aim of fixing the UUID was to give a persistent view on your virtual HW from libvirt perspective, otherwise each time you power on the VM the UUID on libvirt side is being generated from scratch.
> 
> I don't think it would be the right behavior to clone the UUID, to me it feels like the same issue with cloning a virtual TPM device for example.
> 
> Is it possible to make the cloud-init script leave a flag on the persistent filesystem, so that with the VM cloning the flag will be there and cloud-init won't try to change the password in the cloned VM?

yes，we recognize the clone vm as a new vm so we generate a new firmwareUUID. But in fact that the clone vm's cloud-init would think it's the first time boot because the new firmwareUUID. In my opinion, we should remove the Clouod-init-ConfigDrive.

**Comment by enp0s3** [comment]
@matthewei Let me check this possiblity

**Comment by matthewei** [comment]
kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
  name: testclone
spec:
  volumes:
    - name: mybootdisk
      persistentVolumeClaim:
        claimName: mypvc
    - name: mynoclouddisk
      cloudInitNoCloud:
        secretRef:
          name: testsecret

**Comment by matthewei** [comment]
@enp0s3 friend, any progress?

**Comment by matthewei** [comment]
could we set a label to remoark the vm which comes form clone? If so we can controll the colud-init depdend on it.

**Comment by enp0s3** [comment]
@matthewei Hey! 
* I would need you to provide this issue with a full example of the VM YAML with the cloud-init configuration that causes the bug. 
* Cloning the VM w/o the cloud-init configDrive would be a bad approach IMO, since the cloning process in general should not touch anything in the VM spec, unless it's a unique indentifier of a virtual HW like a MAC address. We try to stick to the concept that the VM spec should have only one owner and its the user.
*  It feels to me like we try to trick cloud-init here instead of trying to solve the issue. Can we observe the following path-forwards:
* * un-mount the cloud-init before clonning.
* * Make sure the data relevant to cloud-init trigger will remain the same in the clones i.e. copy the UUID to the clones.

**Comment by enp0s3** [comment]
> * * un-mount the cloud-init before clonning.
@matthewei Here I meant to edit the VM spec, remove the cloud-init volume, power cycle the machine if needed, and then clone

**Comment by matthewei** [comment]
@enp0s3 you can find the vm's yaml from the here.
`
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: clone-vm-test
spec:
  dataVolumeTemplates:
  - metadata:
      name: datavolumevolume
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
        storageClassName: rbd-ssd
        volumeMode: Block
      source:
        pvc:
          name: vm-root-volume
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootvolumevolume
          - disk:
              bus: virtio
              readonly: true
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: attachnet
        machine:
          type: q35
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            memory: 1Gi
      networks:
      - multus:
          networkName: default/attachnet
        name: attachnet
      volumes:
      - dataVolume:
          name: datavolumevolume2
        name: rootvolumevolume
      - cloudInitConfigDrive:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpkaXNhYmxlX3Jvb3Q6IGZhbHNlCnBhc3N3b3JkOiBBMW0jNHd2NQpjaHBhc3N3ZDoKICAgICBsaXN0OiB8CiAgICAgICAgICAgIHJvb3Q6QTFtIzR3djUKICAgICBleHBpcmU6IEZhbHNlCnNzaF9wd2F1dGg6IFRydWU=
        name: cloudinitdisk
`

**Comment by matthewei** [comment]
I want to clairfy how doen the cloud-init work.
1. When the cloud-init found this is the first time boot. The cloud-init will generate the some files and you can find in the path of `/var/lib/cloud`. Those files is realated to firmwareUUID.
2. When the cloud-init found it's firmwareUUID does't change the cloud-init wouldn't be took effect. This why the vm can be reboot many times and the vm's password couldn't be changed.

**Comment by matthewei** [comment]
@enp0s3 hi friend, Have you verifed it? could you share your info?
