### ISSUE TITLE
Want to optimize setting hostname when creating a virtual machine

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10933]
**What happened**:

Now if we don't set hostname when we create a vm and the virt-laucher will use vmi.spec.name as the vm's hostname and you can find the code from [here](https://github.com/kubevirt/kubevirt/blob/2c5e56f2cd0fcde341f47a7da0b94bc812c2f43f/pkg/cloud-init/cloud-init.go#L126C1-L135C39). In my opinion we should generate the hostname by virt-controller rather than virt-launcher. If we use virt-controller to generate it and we can update the vm's configuration. Such as we can use `kubectl get vm -o yaml` to get the hostname.
WDYT?

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
I think it't better to set hostname rather than virt-launcher. WDYT?

**Comment by stu-gott** [comment]
I think it should be possible to set the hostname using cloud-init, for scenarios where the hostname would not otherwise be set.

https://kubevirt.io/user-guide/virtual_machines/startup_scripts/

**Comment by EdDev** [comment]
I fail to understand what is the bug is here.

> If we use virt-controller to generate it and we can update the vm's configuration

I am not clear what you expect the virt-controller to do. If you mean it should mutate the VM or VMI spec, I think it is wrong. Through the spec we express what "we" desire, therefore if one did not desire anything, it should not contain anything. What actually is set and examine later can be expressed through the `Status` section, either through the guest-agent or possibly directly if available (I am not sure it is ok to guess what the guest actually has be set with, no one really can assure cloud-init is available in the guest).

**Comment by matthewei** [comment]
> I fail to understand what is the bug is here.
> 
> > If we use virt-controller to generate it and we can update the vm's configuration
> 
> I am not clear what you expect the virt-controller to do. If you mean it should mutate the VM or VMI spec, I think it is wrong. Through the spec we express what "we" desire, therefore if one did not desire anything, it should not contain anything. What actually is set and examine later can be expressed through the `Status` section, either through the guest-agent or possibly directly if available (I am not sure it is ok to guess what the guest actually has be set with, no one really can assure cloud-init is available in the guest).

I will upload a detailed report to explain it.
