### ISSUE TITLE
RPM inconsistency issue in KubeVirt caused by bazeldnf

### ISSUE THREAD

**Issue by fanzhangio** [kubevirt/kubevirt#11086]
**What happened**:
Bazel keeps reporting errors with the RPM package's SHA256 verification, claiming it's incorrect. However, the RPM defined in the WORKSPACE in KubeVirt has the exact same SHA256 value and should be correct. 
The error is like this:
```
+ KUBEVIRT_BOOTSTRAPPING=true
+ bazel run --config x86_64 //rpm:sandbox_x86_64
INFO: Repository libmpc-0__1.1.0-9.1.el8.x86_64 instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:2360:4: in <toplevel>
Repository rule rpm defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl:46:22: in <toplevel>
WARNING: Download from [http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm](http://rpms/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm) failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95 but wanted 93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638
ERROR: An error occurred during the fetch of repository 'libmpc-0__1.1.0-9.1.el8.x86_64':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl", line 29, column 37, in _rpm_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [[http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm](http://rpms/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm)] to /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/downloaded: Checksum was 4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95 but wanted 93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638
ERROR: /root/go/src/kubevirt.io/kubevirt/WORKSPACE:2360:4: fetching rpm rule //external:libmpc-0__1.1.0-9.1.el8.x86_64: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/internal/rpm.bzl", line 29, column 37, in _rpm_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [[http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm](http://rpms/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm)] to /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/downloaded: Checksum was 4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95 but wanted 93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638
```

#### 1. RPM defined in WORKSPACE is correct.
The RPM is served from a private RPM http container. The RPM and URL are defined in WORKSPACE:
```
rpm( // this is line 2360
    name = "libmpc-0__1.1.0-9.1.el8.x86_64",
    sha256 = "4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95",
    urls = ["http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm"],
)
```

#### 2. The RPM deps required in rpm/BUILD.bazel is correct
```
rpmtree( // this is line 1503
    name = "sandboxroot_x86_64",
    rpms = [ 
              <TL;DR>
             "@libmpc-0__1.1.0-9.1.el8.x86_64//rpm",
             <TL;DR>
    ],
```
#### 3. The downloaded RPM inside builder container is correct
We checked the downloaded rpm in the build container and verified that checksum of this RPM is correct:
```
[root@7c68ab516306 rpm]# cd  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/
[root@7c68ab516306 rpm]# sha256sum downloaded 
4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95  downloaded 
```

#### 4. Ensure cache is clear before running rpm-deps
For local builds, to clear the cache before each RPM dependency operation, we modified Makefile to this:
```
bazel-clean:
	hack/dockerized "bazel clean --expunge"

rpm-deps: bazel-clean
	SYNC_VENDOR=true hack/dockerized "CUSTOM_REPO=${CUSTOM_REPO} SINGLE_ARCH=${SINGLE_ARCH} BASESYSTEM=${BASESYSTEM} LIBVIRT_VERSION=${LIBVIRT_VERSION} QEMU_VERSION=${QEMU_VERSION} SEABIOS_VERSION=${SEABIOS_VERSION} EDK2_VERSION=${EDK2_VERSION} LIBGUESTFS_VERSION=${LIBGUESTFS_VERSION} GUESTFSTOOLS_VERSION=${GUESTFSTOOLS_VERSION} PASST_VERSION=${PASST_VERSION} VIRTIOFSD_VERSION=${VIRTIOFSD_VERSION} SWTPM_VERSION=${SWTPM_VERSION} ./hack/rpm-deps.sh"
```

**What you expected to happen**:
Bazeldnf should calculate the checksum based on the downloaded RPM in the builder, in this case it is `/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/downloaded`. The checksum should be consistent. 

**Suspect cause**:
This is suspect to be a defect of `bazeldnf`. The bazeldnf selects package from upstream centos8/9 or local docker container (in our case). For some reason, bazeldnf messed up. 
Guess this might be related to https://github.com/rmohr/bazeldnf/blob/67cb93b4fd7dd217cafac3625dd09313dde9dad2/pkg/bazel/bazel.go#L125C1-L135C36, which seems trying to fix it but does not work for this case.
We are using KubeVirt release-1.0.1

**Additional context**:
https://github.com/rmohr/bazeldnf/ 

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.1
- Kubernetes version (use `kubectl version`): 1.26.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): Linux 6.2.0-39-generic x86_64
- Install tools: N/A
- Others: N/A

**Comment by fanzhangio** [comment]
@rmohr Can you please take a look ?

**Comment by rmohr** [comment]
> Suspect cause:
This is suspect to be a defect of bazeldnf. The bazeldnf selects package from upstream centos8/9 or local docker container (in our case). For some reason, bazeldnf messed up.
Guess this might be related to https://github.com/rmohr/bazeldnf/blob/67cb93b4fd7dd217cafac3625dd09313dde9dad2/pkg/bazel/bazel.go#L125C1-L135C36, which seems trying to fix it but does not work for this case.
We are using KubeVirt release-1.0.1

I don't think it is related to this. This path is only executed when resolving dependencies from a remote repository to write the expected checksums to the WORKSPACE file (would be called during `jack/rpm-deps.sh` to update dependencies in the WORKSPACE file but it does not actually download any RPMs, nor does it itself calculate a checksum).


> rpm( // this is line 2360
    name = "libmpc-0__1.1.0-9.1.el8.x86_64",
    sha256 = "4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95",
    urls = ["http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm"],
)

So here it seems to have the correct digest. The `rpm` rule is just a thin wrapper around what `http_archive` does. If there would be a bug passing down the `sha256` to the bazel downloader, I think we would know about this already, but maybe that would be something ...


> Error in download: java.io.IOException: Error downloading [[http://rpms:80/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm](http://rpms/AppStream/Packages/libmpc-1.1.0-9.1.el8.x86_64.rpm)] to /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/downloaded: Checksum was 4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95 but wanted 93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638


This seems to look like we would have in the WORKSPACE file the checksum `93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638` specified, but according to your code snippet above you have `4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95` there. This looks to me like a very suspicius thing when you say that the checksum of the file actually is `4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95` in the container.

It looks to me like some important bit of info is missing or not entirely correct. Because what I would expect to see in your case would be a message the other way round, that it wanted `4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95` but got `93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638`.

Just to highlight it again:

 > Bazeldnf should calculate the checksum based on the downloaded RPM in the builder, in this case it is /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libmpc-0__1.1.0-9.1.el8.x86_64/rpm/downloaded. The checksum should be consistent.
 
 Bazeldnf does not do that. It just writes a checksum it gets from the repo information into the WORKSPACE file. If you have there `4fbf751702394211896af9f253ad2f38c80f603e007a7c9ed2b9c8e5d97f2f95`, then we just call BAZELs download things and are no longer involved during build (https://github.com/rmohr/bazeldnf/blob/main/internal/rpm.bzl#L25).

**Comment by fanzhangio** [comment]
Thanks @rmohr for your response. This is a very weird error we don't understand. It is reproducing on local dev env and CI. We expect the WORKSPACE is the only place where customized RPM is updated, e,g, checksum and rul, as what we already do in above example. Can you please point me any suggestions or workaround that can fix it ?

**Comment by rmohr** [comment]
> Can you please point me any suggestions or workaround that can fix this blocker ?

Can you grep the WORKSPACE file and all cache directories for the `93c2232d1885ec6265159f4669aeb13335a80e74d3ae0832f624678d87ea3638` checksum and maybe backtrace where this value is even coming from?

**Comment by rmohr** [comment]
Seems to be resolved according to above comment.
