### ISSUE TITLE
Running OVM can't be deleted using REST api

### ISSUE THREAD

**Issue by jniederm** [kubevirt/kubevirt#1112]
[Documentation][1] doesn't seem to be particularly clear on what's the default behavior. Based on IRC conversation I assume the expected behavior of firing DELETE request on running ovm resource is deleted ovm and orphaned corresponding VM.

#### Actual behavior in Kubevirt v0.4.1, Openshift v3.9.0+191fece:

```
$ http --verify=no DELETE https://localhost:8443/apis/kubevirt.io/v1alpha1/namespaces/project1/offlinevirtualmachines/ovm1 'authorization:Bearer _jBwAgdArFAnb2uWz_txZzgaMuXbFtuZDuRis3YLLh0'
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Length: 194
Content-Type: application/json
Date: Wed, 06 Jun 2018 17:52:46 GMT

{
    "apiVersion": "v1",
    "details": {
        "group": "kubevirt.io",
        "kind": "offlinevirtualmachines",
        "name": "ovm1",
        "uid": "527e2f17-69b2-11e8-bad2-54e1ad30565a"
    },
    "kind": "Status",
    "metadata": {},
    "status": "Success"
}
```

Corresponding vm gets deleted as well.

#### Actual behavior in Kubevirt v0.5.0, Openshift v3.9.0+191fece:

```
$ http --verify=no DELETE https://localhost:8443/apis/kubevirt.io/v1alpha1/namespaces/project1/offlinevirtualmachines/ovm1 'authorization:Bearer gnf8xO-YVJpfozRBPx-AAH50OURrge1z3p24J8bSNuY'
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Length: 710
Content-Type: application/json
Date: Wed, 06 Jun 2018 17:33:42 GMT

{
    "apiVersion": "kubevirt.io/v1alpha1",
    "kind": "OfflineVirtualMachine",
    "metadata": {
        "clusterName": "",
        "creationTimestamp": "2018-06-06T03:06:16Z",
        "deletionGracePeriodSeconds": 0,
        "deletionTimestamp": "2018-06-06T17:33:42Z",
        "finalizers": [
            "foregroundDeletion"
        ],
        "generation": 0,
        "labels": {
            "kubevirt.io/my": "label"
        },
        "name": "ovm1",
        "namespace": "project1",
        "resourceVersion": "53725",
        "selfLink": "/apis/kubevirt.io/v1alpha1/namespaces/project1/offlinevirtualmachines/ovm1",
        "uid": "93e760c3-6936-11e8-98d2-54e1ad30565a"
    },
    "spec": {
        "running": true,
        "template": {
            "metadata": {
                "creationTimestamp": null
            },
            "spec": {
                "domain": {
                    "devices": {},
                    "machine": {
                        "type": ""
                    },
                    "resources": {
                        "requests": {
                            "memory": "32M"
                        }
                    }
                }
            }
        }
    },
    "status": {
        "created": true,
        "ready": true
    }
}
```

Both ovm and corresponding vm remains in the system.

Please
* make documentation clear on what's the default behavior
* align actual behavior with the doc

[1]: http://kubevirt.io/api-reference/master/operations.html#_deletenamespacedofflinevirtualmachine

**Comment by rmohr** [comment]
@jniederm the behaviour got improved, it did not change. As you can see `deletionTimestamp` is set on the object, also the `forground` finalizer is added to the `OfflineVirtualMachine`. You should also see `deletionTimestamp` set on the vm. 

 In previous releases the vms disappeared immediately when you sent a delete request. That was because the vm object will disappear from the cluster once the vm is down and the pod got removed by the kubelet. That can take some time (shtudown timeouts, ...). If the vm would disappear before that, the user could aready post the same vm again although it might still run (in the past we detected that internally and delayed the start as a temporary workaround).

From the API perspective you will have to check for `deletionTimestamp` on the vm and ovm and maybe mark them in the UI as `terminating`.

Finally **all** deletes in k8s are potentially asynchronous. A success on a delete just means that the system accepted the delete (declarative).

I hope that helps.

**Comment by jniederm** [comment]
It helped a lot. Thanks @rmohr. Is there any place (I'd expect http://kubevirt.io/user-guide) I can get such info without opening an issue next time?

**Comment by rmohr** [comment]
> It helped a lot. Thanks @rmohr. Is there any place (I'd expect http://kubevirt.io/user-guide) I can get such info without opening an issue next time?

Most of the flow I described should be move the the user-guide (let's open an issue there).
