### ISSUE TITLE
test/utils.go: Inline CreateConfigMap

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11436]
**Is your feature request related to a problem? Please describe**:

The function `CreateConfigMap` in tests/utils.go could be inlined, since it does not provide much additional value. Also since this is test code, assertions should be used instead of panicking on errors.

**Describe the solution you'd like**:

Inline `CreateConfigMap` into the places where it is used.

**Comment by anishbista60** [comment]
can i worked on this ? 
@alicefr

**Comment by anishbista60** [comment]
@0xFelix 
sir, please don't feel angry .Accidently I created branch  inline-02( working inlining createConfig) on the top of inline-01(working on inline deleteconfigmap and deletesecret) rather than creating from main branch . so, it contain commit of inline-01 . 

so, iam unable to resolve that isssue which lead to closing of previous request

**Comment by 0xFelix** [comment]
Sure, I will not be angry, we're here to learn.

For the next time: You could have reused your `inline-02` branch respectively PR. You can always rebase and force push your own branches. So you could have rebased it on main and just dropped the unwanted commit. There is no need to close PRs.
