### ISSUE TITLE
Support for readinessProbe and livenessProbe

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1201]
Just like pods we should have the anbility to add readinessProbes to VMs.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

exec must not be supported (as it requires guest support which we don't want to rely on right now).

**Comment by stu-gott** [comment]
@fabiand AJust to clarify, are you picturing something that runs inside of the VirtualMachineInstance, or something that runs in the virt-launcher pod?

**Comment by fabiand** [comment]
I imagine that it will be about piggy backing readiness* and livenessProbe of the launcher pod.
Just like resources, this is something we would copy from the VM spec to the pod spec.

Just not the exec method.

**Comment by stu-gott** [comment]
Note to Developer:

If you start a VirtualMachineInstance and inspect the pod's manifest, each container will have a readienssProbe that looks something like this:

```yaml
      readinessProbe:                 
        exec:                          
          command:           
          - cat       
          - /tmp/healthy 
        failureThreshold: 5                   
        initialDelaySeconds: 2
        periodSeconds: 5 
        successThreshold: 2
        timeoutSeconds: 5 
```

The idea behind this issue is that a user should be able to define their own notion of a readiness probe (presumably a service running inside a VirtualMachineInstance) that can be used by Kubernetes to determine the health of a VirtualMachineInstance. Because of the nature of this probe, the `exec` method simply cannot be used (Kubernetes would attempt to run a command inside the virt-launcher pod, which won't do anything useful from the user's perspective) -- so only the network related probes do anything sensible here.

The mission here is to create a readinessProbe or livenessProbe stanza on a VirtualMachine Resource. This might go in the `DomainSpec` struct (found in `pkg/api/v1/schema.go`) or it might need to go in the VirtualMachineInstanceSpec (found in `pkg/api/v1/types.go`). We would not need or want to define our own versions of the readinessProbe/livenessProbe, instead we would want to consume the `Probe` object already provided by Kubernetes. (found in `vendor/k8s.io/api/core/v1/types.go`)

The idea would then be to add a block of code in `pkg/virt-controller/services/template.go` inside the `RenderLaunchManifest` method. The first thing to do would be to check if the VMI defined a ReadinessProbe, if it did that would need to be copied to the Pod spec being synthesized in that function (there already exists a ReadinessProbe on around line 255. that might need to become the default if a user defined one was not provided.) Since the exec form of probes is not useful, it should not be copied here.

Because the exec probe is not allowed, It would probably also be worth adding a Validating function in `pkg/virt-api/validating-webhook/validating-webhook.go`. e.g. a check inside the `ValidateVirtualMachineInstanceSpec` function.

And now the punch line: the above instructions will not work. If we did this and nothing more, the VirtualMachineInstance would be doomed to never start. The scheduling dilemma is due to the fact that KubeVirt is already using the Pod's readiness (which we just overrode to mean VMI's readiness) to determine if the pod is ready for a VM to be started inside it. This check occurs around line 372 of `pkg/virt-controller/watch/vmi.go`:

```
else if isPodReady(pod) && !isPodOwnedByHandler(pod)
```

The implementation of `IsPodReady` occurs in that same module. It essentially checks the status of every container in the pod to determine if the pod as a whole is ready (and thus ready to be handed over to `virt-handler`).

Because the readiness probe serves an essential purpose in terms of scheduling, we can't simply override it without providing some other means for virt-controller to be able to determine if a pod is ready to be handed over to virt-handler. The decision point here might be to change the current "readiness" probes to instead be "liveness" probes. (and only offer readiness probes from within the VMI spec), In other words liveness would be used to determine if a pod was ready to host a VM and readiness could then become a user-defined thing, where the current readiness probe would be the fallback.

Or it might be that the "IsPodReady" function needs to do something completely new to determine pod readiness.

Caveat either of those approaches: pod readiness is a longstanding assumption so there might be other subtleties to address if the rules are changed.

**Comment by nertpinx** [comment]
@stu-gott How about separating VM and Pod probes? Pod probes are taken care of by k8s, but VM probes could be taken care of  by KubeVirt since it handles VMIs. Yes, polling would need to be added in virt-handler, but KubeVirt could use both liveliness probe (e.g. see whether qemu process exists) and readiness probe (e.g. see whether qemu is responding). Disclaimer: these are simplest examples I could think of, they are probably bad. But the idea is that the probes don't need to be synchronized and user probes can be used however the user likes (of course without "exec" for now).
The downside I see is that we'd be re-implementing k8s logic which won't work in long term. Can't that logic be simply reused from kubevirt's codebase?

**Comment by fabiand** [comment]
Done by now
