### ISSUE TITLE
Local Volume provisioner ignoring storage size 

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#1218]
**Bug**
/kind bug

**What happened**:
The PVC created using CDI (using Local Volumes PV) are ignoring the size we pass in pvc spec, it just takes size equals to size of pv, which again is size of the disk for each pv
So I can see 5 PV and PVC of 39G, where the disk size of the node itself if 39G
this might be issue with local volume provisioner, but this affects the our workflow where VMs can virtually write more then which was allocated

**Comment by vatsalparekh** [comment]
so this also allows importing rhel image of a 1Mb pvc

**Comment by aglitke** [comment]
I am guessing this is expected behavior.  Note that the VM cannot consume more than it's disk size because it is writing into a raw file of the correct size.

**Comment by awels** [comment]
So this is behaving as expected, When you define a PV you specify the size of the PV. This is the total available space in the PV. PVCs map onto a PV one to one. So now if you make a PVC, and specify a size, kubernetes will look for PVs that can satisfy the request, and bind the PVC to the PV that satisfies the request. So this means the size you get can be larger than the size request if no PVs that match exactly are available.

Take this example:
I create 2 PVs, one is 5G, and one is 10G, then I create a PVC requesting 6G, I will get the second PV because its the only one that satisfies the request. But if I request a PVC with 5G, I will get the first PV since that one can satisfy the request. In either case I will get either 5G or 10G depending on which one satisfies the request.

**Comment by awels** [comment]
As for the local provisioner issue described, this is also expected. Because we are bind mounting a directory. each PV will be the size of the available space in that directory, and thus each request for a PVC that is smaller than the total available space in that directory will be satisfied by any PV from the local provisioner. If you want to actually have exclusive available storage for a PV, you will need to configure the local storage provisioner differently.

First create some mountable volumes of a particular size (partitions/lvs/whatever). Have those volumes mounted somewhere. Then change the config map for the provisioner, to map PVs to those volumes. At that point they will be exclusive space wise, since we aren't simply sharing the same directory.
