### ISSUE TITLE
Sig-code-quality: sonarcloud currently failing

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/kubevirt#12191]
**What happened**:
Sonarcloud is reporting this repo failing: https://sonarcloud.io/summary/new_code?id=kubevirt_kubevirt

We're failing in two areas: security (all vendor pkgs as best that I can see), and code duplications. 

**What you expected to happen**:
A beautiful green pass

**Comment by avlitman** [comment]
@EdDev @orelmisan Can you take a look and decide if that is something we need to fix?

**Comment by orelmisan** [comment]
This issue was raised in a community meeting that took place on June 26th.
Sonarcloud is complaining about a yaml file that is located under one of our vendored packages.

I've sent a [message](https://kubernetes.slack.com/archives/C0163DT0R8X/p1719414220164309) to our community's Slack channel in order to understand who is managing Sonarcloud's integration to KubeVirt.
I think we could mark the `vendor` directory as ignored (if it is possible to do in Sonarclound) and the issue will be solved.

**Comment by EdDev** [comment]
Or we can check if updating the relevant dependent packages is possible and resolve the problem.

> I think we could mark the vendor directory as ignored (if it is possible to do in Sonarclound) and the issue will be solved.

Why would it be safe to ignore vendored code in this case?
It is one thing that we cannot control the code directly and another that it is a real vulnerability.
We may need to:
- Update the dependency to fix this issue.
- Fix the issue at the dependent project and then update.
- Drop the dependent project and find a replacement.

**Comment by orelmisan** [comment]
The file in question is `vendor/k8s.io/apimachinery/pkg/util/managedfields/pod.yaml` which seems to me like an example file.
Sonarcloud is complaining that it does not meet some security requirements.
