### ISSUE TITLE
VirtualMachineInstance cannot launch when the VM name is too long

### ISSUE THREAD

**Issue by yanirq** [kubevirt/kubevirt#1222]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

*1) VM name longer than 63 characters* 

VirtualMachineInstance with a VM name that is longer than 63 characters cannot launch.
Status of the vmi is empty and it has no events : 
```
./cluster/kubectl.sh describe vmi <long_vmi_name> 
```

```
 Status:
 Events:  <none>
```
Virt-Controller logs : 
```
level=info timestamp=2018-06-25T12:36:15.631975Z pos=vmi.go:157 
component=virt-controller service=http reason="invalid label value: 
\"bbb123456789012345678901234567890123456789012345678901234567890123\": 
must be no more than 63 characters" msg="reenqueuing VirtualMachineInstance 
default/bbb123456789012345678901234567890123456789012345678901234567890123"

```
*2) UNIX socket path is too long*

Even when the VM name is shorter than 63 characters, the UNIX socket path built from it can be too long and get rejected by the virt-handler.
UNIX socket path must be less than 108 bytes.

```
 Warning  SyncFailed          58s   virt-handler, node01       server error. command Launcher.Sync failed: 
virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 
2018-06-25T11:11:03.026395Z qemu-system-x86_64: -chardev socket,id=charserial0,path=/var/run/kubevirt-
private/default/aaa123456789012345678901234567890123456789012345678901234567890/virt-
serial0,server,nowait: UNIX socket path '/var/run/kubevirt-private/default
/aaa123456789012345678901234567890123456789012345678901234567890/virt-serial0' is too long
Path must be less than 108 bytes')
```

**What you expected to happen**:
Successfully launch a VM when its name is too long.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a VM with a name that is longer than 63 characters.
2) Create a VM with a name that will create a UNIX socket path larger than 108 bytes.

**Comment by karmab** [comment]
do we want to launch a vm in this case or rather put a maximum length on hostname ?

**Comment by rmohr** [comment]
Hm, that's a completely arbitrary limitation which for instance also depends on the namespace length then. We should support the same length as pods does and especially not limit it because of something like a socket name.

Now that we have the vmi as long in the cluster as the pod exists and no external libvirt, we can now safely use the UID of the vm and not even add the namespace. That was not so easily possible in the past. @davidvossel FYI.

**Comment by fabiand** [comment]
+1 fur inheriting pod/kube limitations, as it's not easy to change it from our side.

Here a question would be if a viable woraround (we could recommend) would be to use labels i.e. `kubectl describe vmi -l 'domain=veeeeeeeeeeerrylooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnngggggggggggggggname'`

**Comment by fabiand** [comment]
@yanirq do you want to take the bug?

**Comment by yanirq** [comment]
label selector created here :
https://github.com/kubevirt/kubevirt/blob/11dbef363c895f2ed780d6ccb1f07bbd4ff8b5e6/pkg/virt-controller/watch/vmi.go#L554 

with a vmi.name longer then 63 characters will fail on label value validation : 

https://github.com/kubevirt/kubevirt/blob/11dbef363c895f2ed780d6ccb1f07bbd4ff8b5e6/vendor/k8s.io/apimachinery/pkg/labels/selector.go#L165

**Comment by fabiand** [comment]
I wonder if we really need identifiers which are longer than 63 characters.

My take would be:

- Identifier is a label and less than 64 chars.
- Descriptive title is an annotation and can be longer than 64 chars

The side effect is that the identifier can be used for selecting VMs, The descriptive title is only for display purpose.

**Comment by yanirq** [comment]
So going back to the discussion above , we might want to use the vm UID as an identifier (instead of its name)

**Comment by rmohr** [comment]
@yanirq yes I agree, let's go with uid folders.

**Comment by yanirq** [comment]
@rmohr @fabiand  
Will it be safe to say that we will not need the "Created by" annotation `kubevirt.io/created-by` any more  (which value hold the vm uid)  and use the domain label `kubevirt.io/domain`  against the vmi.UID (instead of vmi.Name) ?

**Comment by j-griffith** [comment]
Chiming in a bit late, I'd suggest that we up the limit to 253 characters for names to match K8's BUT that we do in fact continue to enforce the validation hook and disallow creation of resources with >53 chars.

Also converting the identifiers (ie socket name) to a UUID as well as using the UUID as a handle for access going forward would be ideal IMO.  I wasn't aware that this was something that was possible for us now.  Names are bad :)

**Comment by j-griffith** [comment]
I think converting to using UUID as a handle for things (including socket name) is something we should definitely do.  As far as the name length, I don't think 63 is actually arbitrary.  Also although K8's generally allows up to 253 characters for resource names that's not a rule (it can be less, I don't believe it can be more however and I don't have specific examples to share right now).

The limit of 63 characters is actually significant (as noted by some of the other bugs reported) due to the RFC spec for max length in DNS names.  My opinion is that it's best to enforce this via the validation hook, and fail creation.

Truncation is less than ideal IMO because it does lead to the potential of a non deterministic state.  It also has the potential to allow things like Name collisions rather easily.

It doesn't seem unreasonable to me to have a defined limit; the only thing missing perhaps is a very clear message on what the limit is.  My general opinion is that it's best to be explicit, remove as much ambiguity as possible and fail as early as possible.

**Comment by michalskrivanek** [comment]
+1 on using UUID

as for the name - well, we should also consider using a different field for "user name" as often people do want to use names not conforming to DNS limitations, with full UTF and special chars support

**Comment by yanirq** [comment]
@xsgordon  We are indeed talking about using UUID for internal handles only. 
Currently the handles are using the VM name with labels, by that we inherit the k8s labels limitations (63 characters) so using UUIDs in labels will remove this restriction.

Removing the labels obstacle, the VM will have the same limitation as other k8s resources  names ([maximum length of 253 characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/)) in general, but other limitations such as socket names or other areas can restrict us to a shorter VM.name 

If we do decide to go with a documented limitation, we will probably have to add it to our webhook validations.

**Comment by fabiand** [comment]
We need to keep in mind that UUIDs are pod-lifecycled as in they will change whenever there is a VM entity start/stop cycle (or in future probably live-migration).

This means that it's probably safe to use it in the node context, but not on the cluster level for referencing entities.
