### ISSUE TITLE
Hostname does not appear in describe vmi when its not provided in specification 

### ISSUE THREAD

**Issue by yanirq** [kubevirt/kubevirt#1225]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When creating a vmi with no hostname defined under spec, the hostname  should receives the vm name.

`kubectl describe vmi <vm_name> `  will **not** display  `Hostname:`  in output. 

**What you expected to happen**:
`kubectl describe vmi <vm_name> ` should display  `Hostname:`  in output since the hostname receives the vm name.

**How to reproduce it (as minimally and precisely as possible)**:
Create a vmi without a hostname specified in spec and use `kubectl describe vmi <vm_name> `

**Anything else we need to know?**:
More info about hostname and vm name (for DNS) :  
https://kubevirt.io/user-guide/#/workloads/virtual-machines/dns?id=creating-unique-dns-entries-per-virtualmachineinstance

**Comment by yanirq** [comment]
@rmohr  Im trying to think if this is really a bug. 
kubectl gets the vmi resource for description , and if the user didn't define the hostname then it shouldn't exists there. But, hostname gets the vm name in some areas. 
Do we want to update the vmi resource with hostname ?  or is  this wrong by design?
If kubectl describe vmi <vm_name> takes the resource as it is then it will need a hack to display the hostname.

**Comment by j-griffith** [comment]
@yanirq @rmohr I'm trying to understand why we would *not* want to always set a hostName (default to name)?  This sort of matches the behavior of Docker for example, if you don't provide the `--hostname` then the Container name is used by default.  This seems like a good expected behavior to follow no?

Or are we considering the different stage of VMI vs VM?  If that's the case then the field should probably not be available in the VMI at all.

**Comment by yanirq** [comment]
closed - NOT A BUG.
