### ISSUE TITLE
` [Serial]SRIOV VMI connected to single SRIOV network should have cloud-init meta_data with aligned cpus to sriov interface numa node for VMIs with dedicatedCPUs` fails due to memory issues

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12314]
**What happened**:

Test 
`[Serial]SRIOV VMI connected to single SRIOV network should have cloud-init meta_data with aligned cpus to sriov interface numa node for VMIs with dedicatedCPUs`
fails due to memory issues [1] when processing images, probably caused by virt-handler

issue seems to not only affect sriov, but others also [2]

/kind flake
/sig ci

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-kind-sriov/1810687123888541696
[2]: https://search.ci.kubevirt.io/?search=Unexpected+Warning+event+received&maxAge=48h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by dhiller** [comment]
@EdDev did your sig by any chance have the time to look at this issue?

/remove-lifecycle stale

**Comment by dhiller** [comment]
@phoracek do you happen to know whether someone is looking at this one?

**Comment by phoracek** [comment]
@dhiller I don't think so. The team was swamped finalizing work for the feature freeze. I'll sync with @EdDev next week and will make sure somebody's looking into this

**Comment by dhiller** [comment]
@orelmisan

**Comment by ormergi** [comment]
I am on it, will update soon

**Comment by ormergi** [comment]
The job failed due to the following warning:
```
Unexpected Warning event received: testvmi-89mqv,d5779a4c-8a99-481f-95e1-50078d670f15: failed to get image info: failed to invoke qemu-img: exit status 2: 'fatal error: runtime: cannot allocate memory
```
According to build-log the test actually passed, but failed due to the mentioned warning raised by the tests watcher.go that was called earlier in the test which is unexpected (I expect it to fail on the warning the when watcher was called).
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-kind-sriov/1810687123888541696#1:build-log.txt%3A6636 

@dhiller  Please note ([2](https://search.ci.kubevirt.io/?search=Unexpected+Warning+event+received&maxAge=48h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)) searches for warning events in general and not precisely the "cannot allocate memory" one

I didnt find test fail due to the same issue in the past 14 days in serachCI, but I found these the following jobs failed due to the same warning long time ago:
7/2024 https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12025/pull-kubevirt-e2e-arm64/1798988269409538048
9/2022 https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8481/pull-kubevirt-e2e-kind-1.22-sriov-nonroot/1572966014885302272

**Comment by dhiller** [comment]
@ormergi thank you for the investigation!

I didn't see any instance of this issue any more during the last two weeks, so I am going to

/close

this issue.
