### ISSUE TITLE
Cluster level CPU model

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1247]
In order to

a. be able to set CPU models on VMs
b. Make this transparaent to the user

the following **rough** plan is proposed

1. Add an VM API field to set the CPU family (virsh cpu-models x86_64) to one of the known ones by libvirt. If it is not supported by a node, then we fail there. End of story.
2. Expose the CPU families per node as labels
3. Modify the controller to set the correct selector to schedule VMs with a specific family only on nodes which support this family.

4. Investigate K8s compatible abstraction mechanism to make this less fine granular (comparable to ResourceClasses and Resources)

Step 4 is further out.

**Comment by fabiand** [comment]
@berrange @vladikr @michalskrivanek How does this look with your OS/oVirt hat's on?

**Comment by berrange** [comment]
It is not sufficient to only set a named CPU model. it is required to be able to also set various extra named flags to protect against security flaws.  You don't necessarily need to expose ability to set CPU flags to the user, but if you choose not to, then you must have code that knows how & when to set the required extra flags correctly.

NB, in openstack there are three settings:

cpu_mode=host-passthrough|host-model|custom
cpu_model=name of a CPU model when cpu_mode==custom
cpu_extra_features=list of extra features, when cpu_mode=host-model or custom

**Comment by michalskrivanek** [comment]
oVirt focuses on named models. We now have the ability to add or remove individual flags, but currently use a "friendly" name for end users in all cases
Also support host passthrough, but that's a minor use case since we then require host pinning and block migration for simplicity.

so far we added a new friendly name for each security flaw, but we're considering to rather use something like secure/insecure variant of each cpu family as those new flags seem to keep coming...

**Comment by fabiand** [comment]
@MarSik I think this has been addressed by the cpu labels on nodes and selectors on the kubevirt side?
