### ISSUE TITLE
MAC address change after VM reboot

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#1251]
/kind bug

**What happened**:
After shutting down and stating a VM again, I'm not able to ssh to the vm, it says no route to the host
But, I was able to login to the VM via `virtctl console`
Checking on the VM, I found that the MAC address in `ip a` was different then the one in `/etc/sysconfig/network-scripts/ifcfg-eth0`, and so `eth0` didn't get any inet addr, and network.service was also stuck.
**What you expected to happen**:
ssh to work fine
**How to reproduce it (as minimally and precisely as possible)**:
Start a vm, ssh to it, shut down and start it again, try to ssh again

**Comment by vatsalparekh** [comment]
Workaround that worked for this was commenting `HWADDR` in `/etc/sysconfig/network-scripts/ifcfg-eth0`, restarted the network service and `eth0` got address now, ssh also worked now

**Comment by fabiand** [comment]
This should be partially fixed by #1069

We'll then need a mechanism similar to the UUID generation, to interface mac addresses during first creation of a VM.

**Comment by SchSeba** [comment]
Just thinking we can use @booxter [PR-1213](https://github.com/kubevirt/kubevirt/pull/1213) and add the logic of creating a mac address (if the user not assign one) to the virt-controller and it will save it.
Then when the VMI start it will already have a mac address in the vmi object 

Other solution is to always generate the same mac-address for the interface.

**Comment by vatsalparekh** [comment]
@fabiand Actually I guess this is when the virt-launcher pod gets recreated, else if we just do `reboot` from inside the vm console, the mac stays the same

**Comment by fabiand** [comment]
@vatsalparekh correct. It's about the recreation of the domxml which is tied to the launcher.

**Comment by booxter** [comment]
I would agree with populating MAC address if not explicitly set. It helps with migration, it also enhances MAC discovery mechanisms; at this moment, the only way to consistently extract the VM MAC address is from inside the guest, which is not cross-platform.

**Comment by booxter** [comment]
Reopened since we don't persist MAC right now when rebooting unless it's explicitly specified in the spec.

**Comment by fabiand** [comment]
Here we probaly want something like an intitializer like we have for the firmware uuid, which takes the mac from a random set, a "defined pool", or maybe derives it from something. but in all cases, persists it in the spec.

**Comment by booxter** [comment]
@fabiand generating the MAC address may be a complication considering https://github.com/kubevirt/kubevirt/issues/1282 that may well mean that we can't configure a random MAC address and expect it to work in general case (unless we refactor our in-pod network setup into something more complex than what we have right now).

At least for happy path (no explicit MAC address set) it would make sense to allow SDN to pick a MAC address and then propagate it back into the spec. The problem is of course that there may be SDNs that will not retain IP address and/or MAC address when live migrating a virtual machine to another pod. In which case we may hit the issue again. (For what I understand, MAC address for OpenShift SDN is derived from IP address so at least it's stable as long as we retain IP address; but other SDNs may be not as conservative and allocate MAC addresses at random.)

**Comment by fabiand** [comment]
IIUIC then #1282 should be limited to the pod network. In that case we should adopt the MAC of the pod interface.

For any additonal network which has a non-pod network backend, we should be fine - in general. But for specific backends we might have specific constratints again - but we'll see that down the road.

In that sense: The MAC address generation should be backend specific, where righ tnow we could do

```
mac := if podNetwork then delegateMac \
            else generateWithSomeAlgo
```

**Comment by fabiand** [comment]
This feature is now present, a MAC address can be configured - and if the selected backend is supporting it, then it will even be used: https://github.com/kubevirt/user-guide/blob/master/workloads/virtual-machines/interfaces-and-networks.md#frontend

**Comment by ravidbro** [comment]
@fabiand I see that you closed the issue, but IIUC then in case the user doesn't put explicit MAC in the spec it will still change between VM restarts which create a new pod

**Comment by remram44** [comment]
The original issue is still a problem, I think this should be re-opened. It completely breaks cloud-init, and it does so in unexpected ways since the VM will work fine, including across reboots and migrations, until a stop/start re-creates the VMI with a different MAC address and the machine becomes unreachable.
