### ISSUE TITLE
arm lane: clustered failure

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#13436]
# What happened

Clustered failure detected: [1]

/kind flake
/priority critical-urgent

/wg arch-arm
/assign @zhlhahaha 

/sig compute

[1]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13252/pull-kubevirt-e2e-arm64/1862481259553361920

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

**Comment by zhlhahaha** [comment]
Hi Daniel,
It seems that the pull-kubevirt-e2e-arm64 job is working fine overall:
[Job History](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-arm64)

The failure appears to be specific to this PR: [#13252](https://github.com/kubevirt/kubevirt/pull/13252). It looks like the issue is related to an unsupported device in the QEMU binary. I'll take a closer look.

Thanks for pinging me!

**Comment by zhlhahaha** [comment]
Hi, Daniel, it is late today, I will keep looking this issue tomorrow.

**Comment by dhiller** [comment]
Hey Howard, thank you for fixing this!

**Comment by zhlhahaha** [comment]
> Hey Howard, thank you for fixing this!

No problem, it's my pleasure.
