### ISSUE TITLE
Guest shutdown from within the Virtual Machine

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#1406]
**FEATURE REQUEST**:
The ability for Virtual Machine to stay powered down after shutdown from within Virtual Machine, aka Graceful shutdown.

/kind enhancement

**Open questions**:
- How should graceful shutdown from within be reflected in Virtual Machine status?
- How should the cluster operator shutdown the VM gracefully?
- How should we treat Highly Available Virtual Machines? 
  - Where it should be started again?
  - How it should be reflected in the Virtual Machine status?
- Anything else?

What is you opinion: @michalskrivanek @rmohr @fabiand @xsgordon @stu-gott @davidvossel 

**Related issue**: #413

**Comment by petrkotas** [comment]
Please lets focus first on gathering relevant feedback and than work on possible solutions.

**Comment by petrkotas** [comment]
We also need a mechanism to detect the internal status of the Virtual Machine as a helper for detecting graceful shutdown.

Also the cluster admin have to be able to issue graceful shutdown to Virtual Machine just with issuing a command and the rest will take action from within the Virtual Machine.

As for the Highly Available virtual machine. Once it has been shutdown, it should be started on some other node, since ongoing shutdown signals issues with current node. This would require cooperation with Live Migration.

**Comment by davidvossel** [comment]
> The ability for Virtual Machine to stay powered down after shutdown from within Virtual Machine, aka Graceful shutdown.

We’ve overloaded the term “Graceful Shutdown” to mean different things depending on the context of the discussion.  To help with this discussion, here's an enumeration all the different ways I can think of that a VM's process terminates.

1. Graceful shutdown via ACPI when 'Running=false' and 'terminationGracePeriodSeconds' > 0
2. Immediate shutdown when 'Running=false' and 'terminationGracePeriodSeconds' == 0
3. Guest initiated shutdown triggered within the guest virtual machine
4. Qemu process crashes
5. Qemu watchdog is triggered
6. Host Node crashes (host environment goes offline)

Items 1 and 3 both involve "Graceful Shutdown" of the VM, but one is doing it at the cluster level and the other is performing the action without the cluster's knowledge at the guest level. 

For the sake of this discussion, I'd call what we're talking about here a **guest initiated shutdown**

>Also the cluster admin have to be able to issue graceful shutdown to Virtual Machine just with issuing a command and the rest will take action from within the Virtual Machine.

This is item 1. We have that today. 

> How should we treat Highly Available Virtual Machines

We essentially have HA virtual machines today.

If the a VM's qemu process stops for any reason and the VM has 'Running=true', then the VM controller will automatically respawns the the VMI somewhere else. We're leaving it up to the K8s scheduler to determine where the best location to schedule the VMI is. There are a lot of factors involved with this. For example, are their anti-affinity/affinity rules or is local storage in use.

## Declarative vs Imperative API conflict

Lets assume for a second that we figure out the proper way to determine that a guest initiated shutdown has occurred successfully because I think that's a fairly well understood problem set we ovirt has already proven for us. 

We have to decide from an cluster API level how we represent a VM that has both 'Running=true' set yet no VM process present because of the guest initiated shutdown.  This presents a conflict with the declarative nature of our API. We've declared 'Running=true' at the cluster level, but we want to not restart the VM when a guest initiated shutdown occurs. 

In this scenario the cluster should not attempt to set 'Running=false' to reconcile the state. Cluster users declare what they want, and the cluster reacts to that. The cluster does not react to the environment and declare what has happened in the VM's Spec section.

This use case puts us in a tricky situation when it comes to starting a VM in this scenario... We already have 'Running=true', so how does the user say at the cluster level that they want to start the VM again?

That question is the point of tension with this discussion and the thing that has held us back in the past. If we can come to a collective agreement on how to solve that, then the rest of this should be fairly simple.

**Comment by fabiand** [comment]
Fixed with #2070
