### ISSUE TITLE
VM memory validate should be more restricted

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#1502]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
Currently the parameter of memory is a string, the validation of the example below is PASS, after the VM is created, it be started and get into `running` status, but it's not a functional VM, it should be caused by the parameter `MEMORY=2048`.

```
$ oc process -n openshift vm-template-fedora -p NAME=fedora -p CPU_CORES=6  -p MEMORY=2048 | oc create -f -
```
The working one is:
```
$ oc process -n openshift vm-template-fedora -p NME=fedora -p CPU_CORES=6  -p MEMORY=2048Mi | oc create -f -
```

As an end user, I might run into the first situation, everything seems go fine but the VM is not functional.
I'd like to suggest to improve the validation of memory parameter.

**Comment by rmohr** [comment]
These kinds of problems should finally be fixable, now that #1278 is merged. We were not able to reject such invalid VMIs before. @cynepco3hahue we still may to be too lax regarding this specific case, since just a number would still be a valid unit.

**Comment by rmohr** [comment]
@gouyang oh, actually the value 2048 is valid and makes sense, it is just too small to make the OS successfully boot (but the qemu process is still happily simulating the VMI environment). If you connect via VNC you probably see it crashing because of not enough memory. `2048` literally means 2048 bytes whereas `2048Mi` means 2048 MebiByte (note power of two here) and `2048M` means 2048 MegaBytes (note power of ten here).

To gain more insight into if the OS successfully booted, the guest agent and liveness and readiness probes may help us in the future.

**Comment by gouyang** [comment]
Thanks for the explanation, okay to close this.

**Comment by rmohr** [comment]
#1724 should be the first step to help detecting such situations.
