### ISSUE TITLE
virt-handler is ready even if resources are not announced yet

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1509]
/kind bug

**What happened**:
Deployed kubevirt, and checked the node resources. kvm and tun were missing.

**What you expected to happen**:
The resource are available once handler is ready.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubevirt, and check resources right after deployment.

**Anything else we need to know?**:
This might get fixed with https://github.com/kubevirt/kubevirt/pull/1404

Failures: https://travis-ci.com/fabiand/traviskube/builds/84665559 https://travis-ci.com/fabiand/traviskube/builds/84662749 https://travis-ci.com/fabiand/traviskube/builds/84560826
Fixed with sleep: https://travis-ci.com/fabiand/traviskube/builds/84680083

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stu-gott** [comment]
On second thought, as stated, this issue is basically asking for a regression. On systems where a device isn't present, we can assume it will *never* be present. In such a case blocking startup of virt-handler (or reporting it as not-ready -- same thing) is the wrong course of action.

Instead of thinking of device plugins tying into the overall readiness of the pod, think of their capacity as more granular readiness flags. After all, that's exactly how Kubernetes treats them! VMI's that require unavailable plugins won't be scheduled on pods that can't support them.

I'm in favor of closing this issue, but am curious what others think. @fabiand? @rmohr?

**Comment by rmohr** [comment]
@fabiand by "ready", do you mean that virt-handler reported "ready" to the kubelet, or that it marked the node with it's schedulable label?

**Comment by fabiand** [comment]
I have to close this - Right now I can not provide enough details (as I don't have them anymore) to provide enough context. I should have provided enough informations up front.

Sorry for the noise.
