### ISSUE TITLE
vm and vmirs are redundant

### ISSUE THREAD

**Issue by ant31** [kubevirt/kubevirt#1527]
Hi, 

I've been using kubevirt and I found that having VM and VMIRS is a bit confusing and the distinction hasn't real benefit but complexify things. 

Unless I miss a important piece of knowledge: 
- VM are like VMIRS with replicas set to 1
- VMIRS are like VM with state=running  

I suggest to drop VMIRS and add the replicas field in the VM specs
As an alternative, I would do VMRS that manages multiple VM that manages on VMI

VMRS -> VM -> VMI -> Pod 

/kind enhancement

**Comment by rmohr** [comment]
> VM are like VMIRS with replicas set to 1

VM is more like a not yet existing `VirtualMachineStatefulSet` with replicas set to 1. Identity is cruicial. In case something is not right it potentially will not do anything until admins/users resolve issues.

One example: A single activated windows guest which relies on a consistent identity of the machine. If something is not  right with the machine manual intervention may be necessary.

> VMIRS are like VM with state=running

VMIRS are a pool of stateless VMIs. Guest identity does not play any role. Availability is the main purpose. It creates random-named VMIs. In order to guarantee availability it roughly provides the specified number of wanted replicas. Can also be more.

One example: cluster-autoscaling. If you run your (nested) k8s cluster in those vms and want to scale them based on demand. The machines get their information via cloud-init and autonomously register and de-register as nodes for the cluster. You don't care about hardware identity, just about provided resources and that you can cover spikes. 

> VMRS -> VM -> VMI -> Pod

Would indeed be a possiblity. However, since VMIRS simply don't care about identity and are only interested in running VMs (so VMIs),  the don't need that extra complexity. I think that this blurs the focus of what the entities are made for and introduces unnecessary complexity and challenges for both, KubeVirt controllers and the user.

**Comment by rmohr** [comment]
> I've been using kubevirt and I found that having VM and VMIRS is a bit confusing and the distinction hasn't real benefit but complexify things.

Maybe we can explain that better in the user-guide? It would be great to get some feedback on these passages: [When to use a VirtualMachine](https://kubevirt.io/user-guide/#/workloads/controllers/virtual-machine?id=when-to-use-a-virtualmachine) and [When to use a VirtualMachineInstanceReplicaSet](https://kubevirt.io/user-guide/#/workloads/controllers/virtual-machine-replica-set?id=when-to-use-a-virtualmachineinstancereplicaset).

**Comment by rmohr** [comment]
> That those two 'feature' are not exclusive.

Indeed. Still the VMIRS goes more into the direction of a `Deployment`, whereas the VM goes more into the direction of a `StatefulSet` with replica 1.

**Comment by rmohr** [comment]
Let me explain that a little bit more: Since the VM is about identity, we have to ensure that we hand out predictable names, bios UUIDs, ... to the VMIs. If e.g. the third replica `replica3` in this case would be stuck and we have specified that we want three replicas, we can't simply create another VM with name `replica4`. It would have a never-before seen identity then. In this case an admin/user will have to first resolve the issue with `replica3`, so that the pool can re-create `replica3`.

A VMIRS can simply say, oh two of my replicas have trouble and are stuck, I don't care let's just create two more VMIs with random identity.

**Comment by ant31** [comment]
Thank you, that's clear !
