### ISSUE TITLE
move migration controlling logic to virt-handler

### ISSUE THREAD

**Issue by mpolednik** [kubevirt/kubevirt#154]
Current migration implementation is moving towards having it's own MigrationController running as a separate service within it's pod. This issue is grounds for discussion about actually moving the logic to virt-handler itself and implementing it as another watch loop.

The main advantage of having migration as a watcher within virt-handler is that we can easily access migration status and metrics from domain/vm watch loop. Our experience has shown that to correctly reflect domain/VM lifecycle, migration plays important role. There is, at the moment, no code that *requires* access to migration status/data, but it will help us in the long run when we're making sure that VM phase really handles migrations well.

Another benefit is that we don't need multiple libvirt connections and event handlers. Having each bigger functionality connect to libvirt could pose issues to node scaling. That being said, having the watch in virt-handler shouldn't pose any issue for cluster scalability - main migration bottleneck is the migration itself, not it's management. Running 50 migrations barely makes any sense from network bandwidth's perspective.

Disadvantages:
- virt-handler becomes slightly bigger. Probably not a short-term issue, but code bloat in the long term could be a problem.
- Overlapping migration status with VM status logic. That is unfortunately not solvable on this layer.
- Not so kubernetes native approach.

Technical proposal:
- keep migration TPR
- create new virt-handler watch loop (pkg/virt-handler/migration.py)
- (?) initiate the loop in cmd/virt-handler.go while making sure that the migration informer can be passed to vm/domain informers (e.g. type MigrationController passable as arg to NewDomainController)
- for the migration informer, use libvirt API to initiate migrations (virDomainMigrateToURI3)

To decide:
- who creates destination pod?

Changes to suggested user flows:
Hopefully none. Migration is still created/stopped/monitored via TPR (kubectl create -f migration.json etc.)

Consider this as a quick write up and feel free to add another (dis)advantages or discuss the topic.

**Comment by rmohr** [comment]
@mpolednik thanks for sharing,

Here a few questions, so that I can better unerstand the need for this change.

 Is there anything specific you can point me to? What exactly are the situations where it is important that one virt-handler talks to another virt-handler, or one virt-handler talks to a libvirt on another host? As I see it, every virt-handler has access to the domain events and the vm cluster migration state. What else do you think is needed?

The next step I had planned is to let the target virt-handler mark the migration as failed or succeeded (only on the VM object). That is the only thing where I (as non migration specialist) really see a real need to do a change (especially thinking of p2p migrations here). I planned to start with that after #149 is merged.

What exactly is the benefit if virt-handler first takes the migration from the cluster, then spawns the pod and then waits until the cluster scheduler has scheduled and started the pod and then target node, in contrast to letting a central controler doing that?

Some definitive drawbacks: 
 * each virt-handler has to watch for migrations (which means 2*node more connections).
 * Instead of rolling out complex orchestration logic once to the cluster (it is mostly cluster related logic going on), we role it out 1*node times.
 * We need to tell our virt-handler how to talk to other virt-handlers directly (not via the apiserver in between, where we have good infra).

Could you share some concrete examples why what is needed?

**Comment by michalskrivanek** [comment]
@rmohr, let's put it the other way around - what are the benefits and drawbacks of the current kubevirt way? How do you see it handle more advanced scenarios where there is logic in higher layers in a more straightforward way? 

Either way, migrations are tightly coupled with lifecycle events and decisions and they can be easily handled as part of virt-handler. There is no need to increase the complexity so much.
Also note that not all logic is cluster-level, there are useful things to "orchestrate" at node level, low level tunables for actual migration performance (again tightly coupled to monitoring of it).

I do not think we need virt-handler to talk to other virt-handler directly, I don't think that's implied anywhere.

**Comment by rmohr** [comment]
@michalskrivanek I am open for changing anything which needs to be changed to enable features. All I want/need are concrete examples and use-cases where this is not sufficient and why it has to be done different (and I am sure the cases exist). I can't agree to something where I don't get the details. So please provide them and then we can work on a solution.

> I do not think we need virt-handler to talk to other virt-handler directly, I don't think that's implied anywhere.

Right, no one did. I assumed it.

> Either way, migrations are tightly coupled with lifecycle events and decisions and they can be easily handled as part of virt-handler.

As I already said: Could you share some concrete examples why what is needed?

> there are useful things to "orchestrate" at node level, low level tunables for actual migration performance (again tightly coupled to monitoring of it)

Just share them and then we will see.

**Comment by michalskrivanek** [comment]
@rmohr, so again, it shouldn't have been proposed/done that way in the first place. If you consider and review each part of migration flow you can see the need. 
Main reason is you do want to keep the migration logic close to the hosts involved in migration - for the sake of lifecycle notifications/changes. 
Highl level orchestration (what to migrate where) stays at cluster level, sure. I think the only change/argument in what Martin wrote is about the separate service.

**Comment by rmohr** [comment]
> @rmohr, so again, it shouldn't have been proposed/done that way in the first place. If you consider and review each part of migration flow you can see the need.

Again, if it is so obvious, it should be easy for you to come up with something which makes me understand the need.

The two virt-handlers see a VM (cluster representation) when it is migrating, they see the Domain (libvirt) and they see the events. If something goes wrong, they can update the VM (cluster).

Further, like for starting the VM, we can let virt-handler prepare storage and network before the VM migrates with states on the VM object.

What else do you need and why?

**Comment by mpolednik** [comment]
@rmohr 

Concrete examples:

* eventually handling backwards compatibility (updating VM XML before migration even starts)
* reporting that the migration has started (no libvirt event available at the moment, we would have to hope for lifecycle change -- which may not even come in case of post-copy); migration fine tuning (max time, max downtime etc.)
* above implies not having to explicitly ask for jobStats and detecting that the migration has stopped

Some clarifications:

* virt-handler never really needs to communicate with other virt-handler, it just needs to call virDomainMigrateToURI3 and monitor the migration on the source; having the virt-handler aware that the migration has started on the libvirt level allows it to monitor the migration properly and update VM phase accordingly
* destination pod can still be created via virt-controller, virt-handler will have to watch for that
* also consider how post-copy works: the migration is started with postcopy flag and then it is switched to postcopy after first iteration; do you expect to run another job for that? -> meaning the job may not really be the best construct for migration

Going over your drawbacks:
> each virt-handler has to watch for migrations (which means 2*node more connections).
What connections? The nodes will query apiserver anyway.
>Instead of rolling out complex orchestration logic once to the cluster (it is mostly cluster related logic going on), we role it out 1*node times.
What is the "complex orchestration logic"? Pod creation can still be handled via virt-controller, I don't understand what else do you refer to here.
>We need to tell our virt-handler how to talk to other virt-handlers directly (not via the apiserver in between, where we have good infra).
False. They will never talk directly.

This should've been proposed and discussed before implementation. It makes no sense to list concrete examples why some implementation is not ideal if the implementation was never properly discussed in the first place.

**Comment by rmohr** [comment]
So first on the drawbacks:

It is good that I misunderstood you there. I really thought that you also wanted to do more of the migration logic in the virt-handler.

Now to the examples:

> eventually handling backwards compatibility (updating VM XML before migration even starts)

That is an interesting point. Sorry that I have to ask for details again: Did you every have to update something which only the host daemon could know there, or could it also have been done somewhere else? Like for instance at the moment I am updating the domain xml before migration, to redirect spice traffic to the right IPs. That fits pretty well to the cluster level.

> reporting that the migration has started (no libvirt event available at the moment, we would have to hope for lifecycle change -- which may not even come in case of post-copy); 

Reporting in which sense and which granularity? It seems to be pretty much the same granularity which the current pod offers: Calling  through the libvirtapi a migration and basically reporting that the migration did yet neither succeed nor fail. And yes, the libvirt events should at the end be responsible for determining if a migration succeeded, but that has not really anything to do with starting the migration.

> migration fine tuning (max time, max downtime etc.)

Based on what is that done or is useful? Based on the source only? Based on statistics of network saturation, .... ? I have the feeling that all that  depends on the cluster state and both, source and target nodes. So I would rather have the opposite feeling, that when you want to really individualise it, you need a cluster wide view on that one.

Right now, virt-handler can completely focus on its own libvirt and the VMs it is responsible for. It does not even have the slightest idea where other libvirts  or nodes are running or how to connect to them.

Now if we change that, virt-handler will have to query more resources (maybe nodes, configs maybe to find out how to connect, or maybe we need to support some authentication schemes it can pass on to it's own libvirt, so that it can connect to the other libvirt ,...). I am not saying that this is what you are suggesting, but with the simple rule above, it can definitely not happen. The more we let virt-handler do, the harder it is, to lock down access later for virt-handler.

> This should've been proposed and discussed before implementation. It makes no sense to list concrete examples why some implementation is not ideal if the implementation was never properly discussed in the first place.

Sorry, but that is inappropriate and unrelated.

**Comment by mpolednik** [comment]
> Did you every have to update something which only the host daemon could know there, or could it also have been done somewhere else? 

I would prefer to say plain no here, but AFAIK the spice display network may be such case. Let's try @phoracek (do mentions work cross project?). It's worth mentioning that any host-specific knowledge can eventually be *sent* to a cluster management tool, not everything may make sense to be done in such way though.

> Reporting in which sense and which granularity? It seems to be pretty much the same granularity which the current pod offers: Calling through the libvirtapi a migration and basically reporting that the migration did yet neither succeed nor fail. And yes, the libvirt events should at the end be responsible for determining if a migration succeeded, but that has not really anything to do with starting the migration.

You will also want to monitor the migration - progress, iteration, dirty rate... as that information can then be used to present an estimate about migration's health. See [virDomainGetJobStats](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetJobStats). Somewhat practical yet hypothetical racy scenario:

Preconditions:

1. user creates new migration TPR, virt-controller creates destination pod and starts migration job
2. the migration should be changed to post-copy after first 

Flow:

1. The migration starts.
2. The migration has already did an iteration.
3. virt-handler's domain watch loop gets lifecycle event (v1.Migrating from top of my head?).
4. virt-handler starts querying the libvirt about jobStats, possibly catching n'th iteration of the migration.
5. *Someone* switches the migration to post-copy as we already succeeded with the first iteration.
6. Migration end can be detected by a libvirt event.

BTW how does the jobStats (let's say dirty rate) reach user? Migration TPR, separate monitoring?

> Based on what is that done or is useful? Based on the source only? Based on statistics of network saturation, .... ? I have the feeling that all that depends on the cluster state and both, source and target nodes. So I would rather have the opposite feeling, that when you want to really individualise it, you need a cluster wide view on that one.

You need cluster wide view (which in kubevirt is AWESOME as it can be "queried" by a virt-handler), but do the actual settings in virt-handler. It's done to, well, improve migrations. :)

I personally would *love* to have virt-handler (or any DaemonSet'ish thing) to have more functionality rather than moving everything to a single/replicated cluster-wide entity. Maybe this could be discussed (or dismissed) in parallel.

Please accept this smiley face as an apology for the inappropriate paragraph: 😺  :)

**Comment by rmohr** [comment]
> It's worth mentioning that any host-specific knowledge can eventually be sent to a cluster management tool, not everything may make sense to be done in such way though.

Right, but that is the case for both solutions. Some more naturally fit on the cluster and some more naturally on the host.

Regarding to the post copy switch, I see again not much difference if an extra entity is doing it, which is connected to both hosts, or if one host gets an extra role.

> BTW how does the jobStats (let's say dirty rate) reach user? Migration TPR, separate monitoring?

The rough plan is, like the kubelet does, exposing metrics on a REST endpoint which can then be collected by different tools (e.g. prometheus, for the scheduler, for migrations, ...). Further if you are using cAdvisor, cAdvisor can then also scrape virt-handler to collect the metrics for other tools when they are polling cAdvisor. It might also be possible that virt-handler only exposes the minimal metrics necessary for kubevirt, and the whole picture is only exposed by an extra metric service, following the kubelet/cAdvisor model.

Since virt-handler also sees when a VM is migration, it would then also include these metrics. 

> You need cluster wide view (which in kubevirt is AWESOME as it can be "queried" by a virt-handler)

Since it seems to me like there can be many things in the cluster involved, it is one of the reason why I did not want to have it on the virt-handler side. virt-handler has a lot of responsibility already, and I want it narrowed down to nursing VMs it is responsible for, whil they are running on its node (that already includes a lot of storage and networking).

Regarding the post-copy switch, the flow is always the same, no matter if it is done in virt-handler or in an extra spawned entity. The cluster wide entity can do it as good as virt-handler. Also remember, that the cluster wide entity knows how to connect  to both libvirts, it can gather metrics of the migration too. 

With the extra entity we get a clear separation of concern (host boundary for virt-handler, one needs cluster wide info, the other not, ...).


> I personally would love to have virt-handler (or any DaemonSet'ish thing) to have more functionality rather than moving everything to a single/replicated cluster-wide entity. Maybe this could be discussed (or dismissed) in parallel.

I don't think we need an extra discussion, the thread is about that, right? We just need to collect data, on why we should do it.

What do you mean by single/replicated cluster-wide entity? MigrationController will always be there. It just starts a job which does the migration, opposed to somehow triggering virt-handler to do the same thing. We have isolated logic inside a pod which does the migration, that's it. Just to make sure we talk about the same things.

**Comment by michalskrivanek** [comment]
@rmohr, you do not want to do low-level libvirt polling remotely. Not in time-critical flows like migration handling, and it's debatable to use such thing in any flow where you actually care about response time and reliability.
In this particular case you're pushing complex interactions into things which do not need to be complex and they work best when they are not. That's what I see as quite an issue for future.

**Comment by michalskrivanek** [comment]
as for exposing the metrics that makes sense, a single service is again probably better to minimize the need to query/poll some source multiple times

**Comment by rmohr** [comment]
@michalskrivanek 

> In this particular case you're pushing complex interactions into things which do not need to be complex and they work best when they are not. That's what I see as quite an issue for future.

I am not sure I am doing that. I see advantages and disadvantages in both scenarios.

> you do not want to do low-level libvirt polling remotely. Not in time-critical flows like migration handling, and it's debatable to use such thing in any flow where you actually care about response time and reliability.

What exactly are you doing at the moment in vdsm? How often are you polling? What are your actions regarding making it more reliable and what are the time dimensions regarding the response time we need?

With other words, from your experience: Are you interfering with the migration and "stabilize" it somehow? Is it mostly about feedback if the migration progresses at all? How time critical is this post-copy switch? It does not seem so time critical when reading documentation on this ...

**Comment by michalskrivanek** [comment]
>>    In this particular case you're pushing complex interactions into things which do not need to be complex and they work best when they are not. That's what I see as quite an issue for future.

> I am not sure I am doing that. I see advantages and disadvantages in both scenarios.

ok, so let's start listing the advantages and how is the current way more resilient and simple.
I do think I have enough experience with simple design evolving into complex code in oVirt. And here even the starting point seems to be "not simple". Hence it's a warning sign for me.

>>    you do not want to do low-level libvirt polling remotely. Not in time-critical flows like migration handling, and it's debatable to use such thing in any flow where you actually care about response time and reliability.

> What exactly are you doing at the moment in vdsm? How often are you polling? What are your actions regarding making it more reliable and what are the time dimensions regarding the response time we need?

currently it is
- polling for progress/metrics and applying the logic, every 10s IIRC. That's not something I would like to replicate, nowadays there is a libvirt support for some of those metrics to be replaced by events which is obviously better. Then each of this cycle we optionally adjust parametes based on policy (e.g. downtime, bandwidth)
- lifecycle event reaction, immediate. 

> With other words, from your experience: Are you interfering with the migration and "stabilize" it somehow? Is it mostly about feedback if the migration progresses at all? How time critical is this post-copy switch? It does not seem so time critical when reading documentation on this ...

it's both. regular stat monitoring doesn't need to be "quick", and that's ok, I do expect that being done separately along with other metrics. But for "stabilizing it" and also for immediate lifecycle decisions I believe it should be as close to the source as possible. E.g. when migration finishes(or is switched to post-copy mode) you do want to know about that in virt-handler ASAP, ideally in the same event loop as other events related to that VM but unrelated to migration are detected properly. Simple (and naive) example is immediate crash right after migration finishes, but things get more complicated when you add guest shutdowns, hotplugs.

**Comment by fabiand** [comment]
Up to now it sounds to me as if _one_ of the main reasons to have the migration logic within the virt-handler is locality.
It sounds as if the migration logic shoul dbe part of the virt-handler because of timing and statistics reasons.
To me this does not imply that it must be a part of the virt-handler code, in stead to me it sounds as if we are looking to have the migration logic _close_ (in the sense of local) to the source virt-handler and libvirt instance, to avoid that stats/metrics need to be pushed across the cluster. We can easily achieve this by scheduling the migration pod alongside the source virt-handler - then both would be local to each other. cAdvisor could be used for metrics, and because they are offered on the same host, there should at least be only few network related concerns.

As said, this seems to be just one of the problems discussed here. There might be others.

**Comment by michalskrivanek** [comment]
keep in mind the locality matters even in the sense of multiple access to the same resource. Simply put, we can't really query from different clients on the same host and have the same performance, we need to carefully choose when and what information we need and try not to need them at other places.

As for other problem - what I mind the most is the complexity in that "... scheduling a migration pod alongside ..." part. Scheduling? a pod per migration?

**Comment by fabiand** [comment]
Closing this issue for now, as migrations are dropped atm and thus the bug is not applicable anymore.
