### ISSUE TITLE
Ability to Cancel Live Migration

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1631]
> /kind enhancement

Related to #1550

Users need the ability to cancel an in-flight live migration job.  Cancelling the job will have to be a best effort attempt as there will always be a race condition between when the migration completes and when the cancel operation is received.

**Comment by davidvossel** [comment]
@vladikr @rmohr @fabiand  We should discuss how an admin invokes canceling a migration and how the result of that request is conveyed. 

I think the action needs to remain declarative, meaning the user declares they want to cancel the migration job, and the system makes a best effort attempt at satisfying that request. I also think the action needs to be tied to the migration job and not the VMI. 

The idea I had for this is to allow the user to toggle a "cancel" value on the Migration Object's spec via a PATCH. The validation webhook can ensure this option is only toggled during an update, and that once toggled it can never be untoggled. When the migration controller sees this option is set, it attempts to stop the migration using whatever internal mechanism we want.

For reporting whether or not the migration was cancelled, we could use a condition. The end result would be a migration with "Phase: Failed" and a condition indicating the migration was cancelled. A migration with "cancel=true" on the spec with the "Phase: Succeeded" would mean the VMI migrated despite our attempts at cancelling the job. 

thoughts?

**Comment by fabiand** [comment]
It feels a little odd right now, but DELETE is not an option, as we probably want to migration informations even after the migration was canceled.

**Comment by cynepco3hahue** [comment]
@fabiand How long do we want it? Will we create some CRON job that will remove all migration objects after some time?

**Comment by fabiand** [comment]
> @fabiand How long do we want it? Will we create some CRON job that will remove all migration objects after some time?

Well, I thought we have direct support for https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/ ;)

Seriously: So, eitehr we keep them until they are removed by $something (time, higher mgmt) or DELETE is okay enough, because the events contain enough information for the UI and other tooling.

IOW: We might not need to keep it around after completion, if the events logs provide enough informations.
But having an object is a more structured and defined approach to gather details.

**Comment by cynepco3hahue** [comment]
I think a well-structured event must be enough, at least we do not have migration objects under the oVirt and OpenStack.
If migration succeeded, I think only migration duration and a destination node is interesting and if it failed duration and the reason why it failed(from the controller or from libvirt)

**Comment by fabiand** [comment]
If that's sufficient, then cancellation could be a DELETE, which looks
natural to me.

**Comment by davidvossel** [comment]
> @fabiand How long do we want it? Will we create some CRON job that will remove all migration objects after some time?

the migration objects are deleted when the VMI is deleted. We could choose to garbage collect finished migration objects after 24hrs or something if we wanted. 

> If that's sufficient, then cancellation could be a DELETE, which looks
natural to me.

I suggest deciding on the UI/UX flow for creating and canceling migrations before committing to a backend implementation. Ii could be that DELETE of the migration object will suffice, and we'll discover the migration was canceled via the VMI's status section or some prometheus event... or it could be that the UI finds it useful to track the migration object.  Just make sure the backend solution is cohesive with the use workflow.

**Comment by fabiand** [comment]
The reason why I was considering delete is actually UX - "CLI UX".

As a user, using the CLI, I'd assume to be able to cancel a migration by
deleting the migration entity.
Editing the migration object to i.e. set `cancel: true` feels not intuitive
- to me at least.

The status could be kept as a condition on the VMI.

To cycle back: I agree that it should be UX driven, but to me UX is also a
CLI flow.

**Comment by michalskrivanek** [comment]
@fabiand 
it needs to be available after completion, for that a garbage collect or explicit DELETE on finished object would be good -assuming that another migration would overwrite it we would always have at most one.
but if the cancellation is done using the same mechanism (DELETE) then we can have a case when you issue a cancel but the migration actually succeeds before it can be canceled, and you'd lose migration stats. For that "cancel: true" would be a better way, even if not that intuitive. You could refer to the migration object for tracking progress, results (stats on success or failure) and trigger cancellation (and possibly other operations, e.g. for long ongoing migrations you may want to "switch to post-copy" explicitly)

**Comment by fabiand** [comment]
Yes, I do understand.

The question is if enough informations could be retrieved from events and
logs.

But I also udnerstand that an object would be nicer for tracking.

**Comment by michalskrivanek** [comment]
well, migration is not anything you can lose track of. IIUC events are not really that reliable, for that a state (some sort of state) is better to have on the entity itself.

**Comment by lizsurette** [comment]
> To cycle back: I agree that it should be UX driven, but to me UX is also a CLI flow.

+1. I believe the flow should be the same whether it's CLI or UI. I agree with others that it should be revolved around the VM from a user's perspective rather than the migration job. I think we want to take away the need of having to even know about the migration job from the user if we can. I would expect something like this:

1 - Identify a VM to migrate, specify which Node to migrate it to.
2 - Monitor the migration progress of the VM, in this use case, choose to cancel the migration of this VM.
3 - Monitor the cancellation of the migration for this VM, once complete notice that the VM is still running on the original Node.

I think that any errors with respect to the migration should be reported within the context of the VM as well and stored in the VM events history.

If it's helpful, here is what we've been thinking about with respect to a flow on the OpenShift UI side, but again I do think it should be a similar VM-focused flow on the CLI side...

User identifies a VM, chooses to migrate:
![screen shot 2018-11-01 at 3 31 46 pm](https://user-images.githubusercontent.com/208455/47874992-b051bd00-ddeb-11e8-9e54-3f679c3ad36c.png)

User defines destination Node (goal would be to ultimately support multi-select from the UI as well to make it easier to migrate VMs in bulk):
![screen shot 2018-11-01 at 3 32 09 pm](https://user-images.githubusercontent.com/208455/47875020-be074280-ddeb-11e8-969e-be9b0ab2d7d1.png)

User monitors the migration process...I'd expect an action in the kebab would be to cancel the migration at this point:
![screen shot 2018-11-01 at 3 32 26 pm](https://user-images.githubusercontent.com/208455/47875042-cfe8e580-ddeb-11e8-9642-b019b55795f9.png)

User sees that the migration has been successful (or maybe it has been canceled), but the VM is back up and running on the new Node:
![screen shot 2018-11-01 at 3 32 41 pm](https://user-images.githubusercontent.com/208455/47875268-7f25bc80-ddec-11e8-91d0-95de3c521a61.png)

**Comment by michalskrivanek** [comment]
> I think a well-structured event must be enough, at least we do not have migration objects under the oVirt and OpenStack.

that is incorrect for oVirt at least, I do not know the details of Openstack. 
You need to have an entity to query for the results, stats, progress.
Events are fine for reporting progress, you don't care much if you loose one if that's a periodic report. But the state (migration state) and result stats need to be available for queries later, both for succesful and failed cases

**Comment by fabiand** [comment]
We discussed this a bit off-list.

Two key takeaways:
- Kubernetes _in general_ does not provide historic data
- The UI wants to show historic data
- DELETE is the 'natural' way to remove a desired state iow cancel a migration

The suggestion we have:
- Cancel a migration by DELETE the migration object.
- For successful migrations, all the details and events are still maintained for some time after the migration is done on the migration object.
- If historic data is needed, the a service should collect the data that is needed by the UI. I.e. in this case a service could collect all migrations which come and go (cancelled or succeeded or failed or …) and provide this data to the UI. We already have a similar service for searching templates. An alternative would be to use the Kubernetes audit log.

**Comment by davidvossel** [comment]
> If historic data is needed, the a service should collect the data that is needed by the UI. I.e. in this case a service could collect all migrations which come and go (cancelled or succeeded or failed or …) and provide this data to the UI. We already have a similar service for searching templates. An alternative would be to use the Kubernetes audit log.

The migration object can provide this historical data, which is why I'm still hesitant about using DELETE for the cancel operation. 

The migration object represents a single attempt at a migration, and it contains all the information about what occurred as a result of that attempt (success, failure, cancelled, etc...)  Those objects are a VMI's migration history and that history is directly tied to the VMI's lifecycle. When a VMI is deleted, all the migration objects are automatically cleaned up.

**Comment by rmohr** [comment]
> The migration object can provide this historical data, which is why I'm still hesitant about using DELETE for the cancel operation.

I don't know. Why should the runtime provide historical data? You could argue the same way that you need a "v1/namespaces/<namespace>/pods/mypod/stop" rest-call instead of using DELETE, because you want to see afterwards for a few days on the pod itself how fast it terminated, or want to extract the logs 3 days after you stopped the pod. The same for VMIs, VMs, ... 

In my opinion monitoring and analysis should strictly be separated from runtime operations (and yes we need to catch up here a little bit, more prometheus metrics, ...). Otherwise we can never use DELETE for anything.

**Comment by michalskrivanek** [comment]
@rmohr that's a good point, but please make sure the monitoring is 100% reliable. it cannot be done as best-effort only as the logic on top of these basic actions is going to depend on it.

**Comment by rmohr** [comment]
> @rmohr that's a good point, but please make sure the monitoring is 100% reliable. it cannot be done as best-effort only as the logic on top of these basic actions is going to depend on it.

For as long as the object exists the UI can reliably follow it's changes. You and I for instance talked about making attempted restarts visible on the object while they are going on. That makes sense. Also it has a meaning if an object got deleted from the cluster and finally disappeared, the UI can consistently interpret that.

 Another things are historical events or recent events of interest (e.g. warnings): They are always best-effort. We have no influence on that (event stream simply is best-effort to for instance not overload the cluster if it is already unhealthy). The UI can never use that to determine an actual state of the cluster. It can only associate it with existing objects and make the event visible if it is interesting for the user.

Finally as a third lane we have log-aggregation (different than showing the logs in the UI of currently running things) and metrics collection: They are independent of the runtime , probably hard to interpret for the UI and normally mostly make sense to be visualized or analyzed in extra web-portals (kibana, graphana, ...) or by extra tools (alertmanager, ...). As far as I have seen, the openshift UI normally provides links to the external tools in the appropriate places.

I don't think that we have more to offer here.

Things like the [metrics API](https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/#the-metrics-api), the [audit log](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) or e.g. visualizing alertmanager alarms  probably also makes sense to display to a degree to users, but we would only provide the metrics. If this is then available for the UI or not, is not really something which `kubevirt/kubevirt` can influence.

**Comment by michalskrivanek** [comment]
I would differentiate between the last attempt and full history of actions. I agree that we shouldn't maintain full history "ourselves" and we indeed would have to rely on metrics for display purposes. But the result of last action is something different, that needs to be reliable. It can also be part of the object (so it goes away when object is removed), that's fine as well as once the object is removed the any potential associated flow is irrelevant and we again can just show historical data.

But then let's go back to the immediate latest result - if we do not want to keep it in the migration object, would it make sense to update VM with it?

For context in libvirt/oVirt you get the same behavior, the migration "task" is transient and there would be nothing to refer to after it's finished successfully or canceled,and so there is a callback. That "persists" the resulting data in the VM object for backend to pick up when needed - which is typically immediate as a reaction to lifecycle change of the VM. There's no need for a history, just for the most recent attempt.

**Comment by davidvossel** [comment]
> I don't know. Why should the runtime provide historical data? You could argue the same way that you need a "v1/namespaces//pods/mypod/stop" rest-call instead of using DELETE, because you want to see afterwards for a few days on the pod itself how fast it terminated, or want to extract the logs 3 days after you stopped the pod. The same for VMIs, VMs, ...

That might not be a perfect analogy.  Pods VMI and VMs are workloads. Once you delete those objects you no longer care about those workloads or their state. The Migration object is tracking a single attempt to transition a workload. That migration object is tied to the lifecycle of the workload. As long as the workload persists, I think the migration object *might* maintain value for us.

Here's what I want to sort though.

If we need to maintain a full history of migration attempts for the UX, then I suggest we keep every migration object and let the VMI controller garbage collect them when the VMI is deleted. Metrics are just sampling the state of the system at a give point in time. If we need a detailed history for the UX, then for accuracy I think we'll need to maintain that in the runtime. 

If we only need information about the last attempted migration, then the UX can gather that information today in the VMI's status section. We store enough information in the status section to derive everything we need to know about the last migration.

If we can answer those questions, then I think we can definitively say whether or not Deletion of the Migration object is a good idea or not.

**Comment by rmohr** [comment]
> That might not be a perfect analogy. Pods VMI and VMs are workloads. Once you delete those objects you no longer care about those workloads or their state. The Migration object is tracking a single attempt to transition a workload. That migration object is tied to the lifecycle of the workload. As long as the workload persists, I think the migration object _might_ maintain value for us.

I think it is a pretty good one. For as long as you don't cancel/delete something in Kubernetes you very often see the previous attempts, so you kind of have a failure history, but cancel/delete means that you most of the time remove the history. I am not sure I understand why I would care more about an old migration in the runtime, than I would care about a Pod being evicted. In both cases everything can have been well, or not.

> If we need to maintain a full history of migration attempts for the UX, then I suggest we keep every migration object and let the VMI controller garbage collect them when the VMI is deleted. Metrics are just sampling the state of the system at a give point in time. If we need a detailed history for the UX, then for accuracy I think we'll need to maintain that in the runtime.

I did not see any reason so far why we would want a detailed history in that sense, if you explicitly cancel a migration. If it runs  to success/failure it stays there. Even for e.g. load-balancers which do automatic migration, a cancel by users is not really interesting for them. Regarding to metrics, yes they are only specific points in time, that is why metrics and logs need to be collected while things are running.

From my point of view, I do not even understand why the last migration needs to be part of the vmi. Events are not reliable, but they should be reliable enough for ux hints. Collected metrics, logs and events should give a reasonable picture about the migration history.

**Comment by fabiand** [comment]
Along the lines of Roman's last comment:

>  For as long as you don't cancel/delete something in Kubernetes you very often see the previous attempts, so you kind of have a failure history, but cancel/delete means that you most of the time remove the history.

and

> […] why we would want a detailed history in that sense, if you explicitly cancel a migration. If it runs to success/failure it stays there.

IOW: There are two basic paths for a Migration object after it got created: a) It will complete (fail or succeed) b) An external party cancels it while it is running or deletes it after it completed.
In either case: The object does not go away without user-interaction or after laying around for some time.
Specifically in the case we are discussing here - cancellation - the object is there when the user performs an operation (cancellation) on it, thus it also has the ability to observe the object.
In the other case - when the objects automatically run to completion - then a user can still observe the outcome (aka historical data), because the objects remain (for some time at least).
In short: In any case, an external party can have the knowledge why an object left the cluster.
The gap is only that this knowledge is not maintained over time. But to me this longer term history is not not something that the runtime requires to operate.

Now, otoh I do see that a UI would want this data. I see two ways:
1. `/cancel` subresource like we have for restart in order to let cancel a migration (It will run to complete, and will stay in the cluster)
2. An extra service which provides a configurable history on migration objects (maybe others as well?), we could use DELETE for migration objects, the UI would get historical data for this new service

I'm in favour of (2), as this makes the flow so CLI-natural, and for the UI to work nicely we keep additional data.

Side note on:

> Events are not reliable, but they should be reliable enough for ux hints. Collected metrics, logs and events should give a reasonable picture about the migration history.

The UI can also watch objets, which _is_ reliable. But: The history displayed in the UI might be independent of the runtime of the UI itself, which requires something like (1) or (2).

**Comment by rmohr** [comment]
Exactly, for normal flows we keep the history. Just when you want it to go away it would be removed.

> * `/cancel` subresource like we have for restart in order to let cancel a migration (It will run to complete, and will stay in the cluster)
> * An extra service which provides a configurable history on migration objects (maybe others as well?), we could use DELETE for migration objects, the UI would get historical data for this new service

I don't want to build in things and work around the usual DELETE semantic just in case someone comes up with a use-case which so far no one provided.

I don't see the need for a new service. Events, metrics and logs should provide a consistent enough picture. I don't think that we pretend that running as an admin (migrations are for admins) a k8s cluster in production makes any sense without proper metrics and logs collections. If you cancel something in the runtime and need to further analyse what's going you always need that. I still did not see why the other thing is needed in a more pressing manner than when anything else is deleted in k8s. Please just tell me that. Just because UX wants to display it, is for sure no good reason.

**Comment by michalskrivanek** [comment]
@rmohr scheduling needs the information about at least the latest failure. I do not think we need full history, just the most recent attempt

**Comment by fabiand** [comment]
> I don't see the need for a new service.

The service I was speaking about can be tied to the UI. I don't see a need for it in the runtime.



>  scheduling needs the information about at least the latest failure.

I'm not sure if we need a tight coupling. Instead: I can imagine that a component like nod eproblem detector has a kubevirt plugin in order to monitor certain events (like migration failures) to then eventually taint nodes on certain conditions.

**Comment by michalskrivanek** [comment]
sounds ok to me then

**Comment by davidvossel** [comment]
> An extra service which provides a configurable history on migration objects (maybe others as well?), we could use DELETE for migration objects, the UI would get historical data for this new service

i'd really encourage us not to create another service that needs to maintain a history of runtime state... We're talking about creating another stateful app here. Where does this state live? How is made highly available? My immediate reaction is that this is unnecessary complexity. 

If the migration object history is important to us, keep the objects around until the VM is destroyed. 

> Failure and success are not deleted. Only if it is cancelled.

And that's the problem I have with using delete to cancel migrations. We might be deleting a successful or failed migration object. There's no guarantee the migration is canceled. It could have succeeded/failed at the moment we post the delete.

**Comment by fabiand** [comment]
My point was that I do not see any immediate need to kepe historic data in the runtime.
If a component like i.e. a UI does need a comprehensive history, then it should record the reqquired state histories. The same is true btw for core Kubernetes.

However, I spoke to @jelkosz and it looks like the events we raise will be enough for now.

**Comment by fabiand** [comment]
WOOT!!!
