### ISSUE TITLE
Investigate DataVolume CRD autodetection and deprecate DataVolume feature gate

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1638]
> /kind enhancement

KubeVirt's DataVolume integration is currently feature gated. The original though behind this feature gate was it protected users from a feature that was still in the process of stabilizing. Since then CDI has stabilized to the point we should consider removing the feature gate.

In order to remove the feature gate, we'll need logic in virt-api and virt-controller to dynamically detect when the DataVolume crd is introduced, and enable DataVolume integration once the crd is present.

For virt-controller, this means creating a DataVolume shared informer with a custom ListWatch that acts as a no-op until the DataVolume crd is detected. Once detected, the ListWatch should for a resync and begin listing and watching the DataVolume objects.

For virt-api, this means toggling whether or not we accept VMI and VM definitions referencing DataVolumes based on if the DataVolume crd is present.

**Comment by rmohr** [comment]
> Once detected, the ListWatch should for a resync and begin listing and watching the DataVolume objects.

Let's try to not do such things inside the listwatcher. How about the following for our controllers:

 * Listen for specific changes (e.g. feature gate added/removed from config map, new CRD registered)
 * Invoke a callback, which stops controllers which are affected by that change (using the stop channel)
 * restart them (that ensures that e.g. initial chache syncs and other small details will work properly)

So, instead of wrapping listwatchers and implicitly toggling them on or of,  let's restart the controller with a different listwatcher.

**Comment by rthallisey** [comment]
Now that we have the kubevirt-operator, it might make sense for it to handle this since it falls under the jurisdiction of component orchestration.  We should coordinate on a design for this because orchestration is going to require good status reporting so both the CDI operator and the cluster-admin are aware that if DataVolumes are enabled, the operator will bubble up a message like "I'm waiting for CDI to create the DataVolumes CRD". 

cc @slintes

**Comment by rmohr** [comment]
> "I'm waiting for CDI to create the DataVolumes CRD".

With the dynamic client we can any time detect if CDI got installed or removed (group discovery). I would love if we have a dynamic approach which enables/disables CDI support dynamically. VMIs which were started when CDI was present would still continue to function, not yet started VMIs would fail.

**Comment by davidvossel** [comment]
> With the dynamic client we can any time detect if CDI got installed or removed (group discovery). I would love if we have a dynamic approach which enables/disables CDI support dynamically. VMIs which were started when CDI was present would still continue to function, not yet started VMIs would fail.

dynamic meaning without restarting virt-controller work queue?  i'm not sure how that's possible since we have to populate the datavolume informer cache once CDI is detected

**Comment by rmohr** [comment]
> dynamic meaning without restarting virt-controller work queue? i'm not sure how that's possible since we have to populate the datavolume informer cache once CDI is detected

queue restart or even fully restarting virt-controller is all fine. I just don't want to see something like the need for manual intervention from an admin.

**Comment by davidvossel** [comment]
> queue restart or even fully restarting virt-controller is all fine. I just don't want to see something like the need for manual intervention from an admin.

yep, agreed.
