### ISSUE TITLE
Creating VM with custom PCI address for VirtIO disks fails

### ISSUE THREAD

**Issue by kbidarkar** [kubevirt/kubevirt#1668]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
Creating VM with custom PCI address for VirtIO disks fails.

VM creation fails with custom pciAddress for virtio disks, with the below message as seen from the "oc describe vmi <vm-name>"

```
Status:
  Conditions:
    Message:               server error. command Launcher.Sync failed: virError(Code=27, Domain=20, Message='XML error: Invalid PCI address 0000:04:10.0. slot must be <= 0')
---

Events:
  Type     Reason              Age                From                                                   Message
  ----     ------              ----               ----                                                   -------

Warning  SyncFailed          7s (x12 over 18s)  virt-handler, cnv-executor-kbidarka-node2.example.com  server error. command Launcher.Sync failed: virError(Code=27, Domain=20, Message='XML error: Invalid PCI address 0000:04:10.0. slot must be <= 0')
```

Cannot provide/attach  domain xml file from virt-launcher as it does not exist.

**What you expected to happen**:
VM creation should work successfully with custom pciAddress for virtio disks.

**How to reproduce it (as minimally and precisely as possible)**:
Specify custom pciAddress for virtio disk as mentioned below:

spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
          pciAddress: 0000:04:10.0
        name: registrydisk
        volumeName: registryvolume

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.9.3", GitCommit:"2f54966f09376152585818f0b50e0b03b5badc71", GitTreeState:"clean", BuildDate:"2018-10-24T07:47:22Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.3.0-4-1-gd572420", GitCommit:"2f54966f09376152585818f0b50e0b03b5badc71", GitTreeState:"clean", BuildDate:"2018-10-24T07:50:46Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-26T12:30:09Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-26T12:30:09Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

```
- VM or VMI specifications: VM specification.
- Cloud provider or hardware configuration: VM

- OS (e.g. from /etc/os-release):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
This is a valid error from Libvirt. 

On `q35` machine type, pci addresses for a virtio disks with a `bus` > 0 will be placed on a `pcie-root-port` controller, which has only one slot allowed.  Trying to set `0000:04:10.0` will result in an error...
On the other hand, setting an address with a `slot` > 0 on `bus` 0 should work: `0000:00:17.0`

I don't think we can replicate all of the libvirt's validation logic for pci addresses in KubeVirt.

The bug here is that I've mistakenly forbidden setting pci addresses on slots 0,1,2 - according to libvirt documentation, these are reserved, but not on `q35`
Due to this, it's currently not possible to set addresses such `0000:04:00.0`
I'll propose a fix.

**Comment by fabiand** [comment]
A few things:

1. It is okay that libvirt prevents setting that specific address. The reason is given in the error message
2. KubeVirt is following libvirt's logic - this nothing we need to implement on our layers
3. We can improve the "lcarity" of the error message (i.e. we should drop ` server error. command Launcher.Sync failed:` which is not very useful to the user) - and limit it on the important part.

In words: For validating addresses we want to rely on libvirt, thus we need to become good at exposing the errors which are caused.
In general 8and this is obvious) we will also not support to set something which is not supported by libvirt.

**Comment by fabiand** [comment]
Thus to me the action item is to improve how we expose libvvirt error messages.

**Comment by vladikr** [comment]
> Thus to me the action item is to improve how we expose libvvirt error messages.

The error message is important too, but the most pressing issue is to remove the slots validation from pci addresses at all. Without removing it, users won't be able to set addresses in a form of `0000:XX:00.0` on `q35`
