### ISSUE TITLE
Derive Pod minimum requirements from CPU and Memory in VM spec

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#167]
Pod's can have [resource requirements](https://kubernetes.io/docs/api-reference/v1.5/#resourcerequirements-v1) and namespaces can have [limit ranges](https://kubernetes.io/docs/tasks/configure-pod-container/limit-range/).

Whenever a VM get's a CPU and Memory, then we could map it to the appropriate pod resource requirement.
This would allow the scheduler to "see" and consider those.

**Comment by michalskrivanek** [comment]
should this be part of management or should kubevirt derive it from VM definition? There are more resources which are interesting for pod definition. Which part would do that if not management?

**Comment by rmohr** [comment]
Would be nice if we could model at least these two the same way on the VM object, [like it is then on the Pod](https://kubernetes.io/docs/tasks/configure-pod-container/limit-range/) and just copy it over. virt-handler can then map it to domain xml.

**Comment by rmohr** [comment]
@michalskrivanek I would say that a high level managment plane can set them on the VM.

**Comment by michalskrivanek** [comment]
@rmohr it's ok, but then you need the logic of understanding the VM definition and what it means for the Pod in virt-controller, depends how far we want to go with container restrictions, but ultimately most of the things the VM use can be expressed in pod restriction/mapping, so it may become quite complex for virt-controller.

**Comment by mpolednik** [comment]
Not sure if it's actual memory limit on the namespace, but mentioning this for consideration:

Since the VM (or QEMU) process would be the one running inside the pod/namespace, how do we handle QEMU's overhead? 2GiB VM may require 2.1 GiB mem (arbitrary value). I believe the attempts to calculate the overhead exactly failed.

**Comment by rmohr** [comment]
@michalskrivanek Right. I see three possible layers here:

 1) kuberntes native ones which we can copy over 1:1 to the pod
 2) not antive ones, which we could add to an annotation section on the VM, which we can the copy over to the pod. Additional scheduler extensions are responsible for interpreting them. (kubevirt basically gives you an extension point)
 3) where no scheduling extension is wanted or required, labels can be assigned to nodes and labels can be placed accordingly on the VM. These lables are then copied over to the pod

Affinity is another topic and can also be easily handle by copying affinity rules over and modifying them slightly, since they also exist in kubernetes.

**Comment by michalskrivanek** [comment]
@rmohr - ad 1. - how do you want to copy them? I'm not sure even the simple ones map 100%, subset of them perhaps, e.g. CPUs when you look at "total number of vCPUs" but there is always going to be more fine grained setting/definition of CPUs, e.g assignment to NUMA nodes. Even the memory is not 1:1 as mpolednik points out.
Perhaps it doesn't matter and we just interpret and copy the few we think make sense in the right way. I'm just pointing out it shouldn't go out of proportions if someone expects a tightly locked down/configured POD fitting the VM.

**Comment by fabiand** [comment]
Setting an upper level for resource consumption is probably to hard, as the kubelet would enforce the memory limit on the node level explicitly.

We can start with `requests` for now which [can be used](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-ram-container/) to specify the minimum amount of memory and cpu required.

**Comment by fabiand** [comment]
@mpolednik yes, the overhead is a concern (/cc @berrange here).

However, as stated in my previous comment - we can start to express our minimum requirements (which is the ram and cpu requirements of the vm). It's a start, and it's better than today, because today we are limited to 512MB RAM per pod iiuic.

**Comment by michalskrivanek** [comment]
we did work on some nice algorithm calculating the overhead more accurately in oVirt, that can be reused...
but yeah, 1:1 for cpu and memory is a start, but eventually we'll likely need a proper scheduler and more things in annotation or somewhere...

**Comment by fabiand** [comment]
Yes, I agree - We also need to look at a different scheduler.

Despite that it might make sense to leverage this low hagnging fruit.

**Comment by cynepco3hahue** [comment]
@fabiand Hi I have some questions regardings this issue
- We do not have CPU type under VM Domain Spec, do we want to add it?
- I see that libvirt supports specific memory unit types, do we have some file to place such constants?
```
var int Kib = 1024
var Mib int = math.Pow(Kib, 2)
...
```

**Comment by MarSik** [comment]
You do not need a separate scheduler for this. There is no reason to keep the VM spec and pod spec numbers the same. The pod specification can simply ask for all the required memory including the overhead.

**Comment by MarSik** [comment]
We can even implement overcommit this way. Just use the pod memory size for the minimal required memory and a separate resource counter (we do not have the support yet iirc) for tracking the overcommit memory.

**Comment by cynepco3hahue** [comment]
@MarSik I do not sure about it if we do not put some memory request for VM pod, how Kubernetes will know to distribute VM pods among nodes without memory starvation.
For example, I started VM with 1GiB of memory on a node with 2GiB of memory, but from the `describe` command I can see that node memory request equals to `0%`, so kubernetes can start additional number of VM's on this node, but in case if one of VM's will start to utilize all memory, other VM's will have memory starvation. So I believe at least for memory we need to specify `requests memory`(I believe it will be similar to our `Max scheduling memory to start VM's`).

**Comment by fabiand** [comment]
In this issue we can start simple: We just request the same memory amount in the pod which got assigned to the VM. Over the long run we can see how we can learn how much overhead is introduced in addition to this.

**Comment by MarSik** [comment]
@cynepco3hahue The current oVirt tracks two separate memory metrics.

- overcommit memory - this is the maximum a VM can get, the total can be higher than physically present and we should use a new resource for this (if/once kubernetes has the support for those)
- minimum guaranteed memory - this is what the VM always needs to have and we should use this value + the qemu overhead as the initial value for the POD.

With regards to qemu overhead: Currently oVirt uses fixed 65MB overhead per VM. The more precise computation depends on multiple other metrics.

I suggest we start with POD memory = VM memory + 65MB as it has proven to be a good enough average approximation. We can continue from there.

**Comment by michalskrivanek** [comment]
why not the new estimation code by milan, that's way more accurate

**Comment by michalskrivanek** [comment]
I really do not see a point of going with wrong code when we already know it's complicated to get it right. If we do not get it right in this PR then it's better if we do not set anything at all until we have time to do it properly. Bad code tends to stick...

**Comment by MarSik** [comment]
Because we do not even use it in the engine atm, we do not know what will happen there and it is way more complicated to implement it in go than just the empirical + 65 MB. Otherwise it would be of course better.

**Comment by michalskrivanek** [comment]
my point is that going with 0 is better than 65, as it may mislead people that it actually means something. But it is way off for a long time. Rather start with a simple match VM size== POD size with a clear TODO that overhead is missing.

**Comment by MarSik** [comment]
On the other hand, going with 65 will allow you to use the full memory with basic VMs, going with 0 will definitely won't. You are right that kubevirt is going to be less forgiving here, because we aren't hard capping the VM in oVirt.

**Comment by fabiand** [comment]
What about handling the optimization of the overhead issue in a separate issue?

Regardless of how this value is determined, we'll see still need the basic functionality which is covered in this issue in place to apply it.
Let#s also move the discussion of the value to the new issue.

**Comment by sahid** [comment]
The memory reserved for overhead should be configurable, can't we have a general option per host to reserve an amount of memory which means that the host is returning it's memory minus what is reserved? The operator can monitor and update this value according the swap on hosts. The problem is that depending of the number of vCPUs threads and activities, devices states, the overhead will be different. So moving the problem in host avoid that to deal about calculating an overhead per requests.

It's interesting to consider using the quota but I can see some limitations. I understand that you want first a basic support but if we can already think of what will be needed we could avoid that rework at some point.

All the resources are not going to be only quantitative and the resources have hierarchies (NUMA) how that is going to be described?  (I'm not familiar with k8s).

**Comment by fabiand** [comment]
The overhead will be configurable (IIUIC from all the parties) there is just some disagreement of what the number should be  :) Maybe we want to offer a way to plug in different mechanism to determine the number.

The overhead depends on the number of (at least) VMs, and we know that it even depends on [devices](https://rwmj.wordpress.com/2017/04/28/how-many-disks-can-you-add-to-a-virtual-linux-machine-contd/). Thus to me it does not look beneficial to move this to the host.

Resource monitoring is performed by the kubelet or one of it's (future) device plugins.

Is there any string reasons why you'd want to move it to the host, @sahid ?

**Comment by sahid** [comment]
> Is there any string reasons why you'd want to move it to the host, @sahid ?

There is no way to determine an exact number - Trying to guess per request depending of the VM spec does not seems right. It depends of too many factors and then what about hotplug?

My idea is just a global amount of memory reserved on hosts. avail = free - reserved

I guess It's more beneficial to report the exact resource a host can address to the scheduler. An other reason is that the users may run some third-party services which also consume memory. Having a tunable on host would provide for operator an instrument to reserve memory depending of workload.

**Comment by mz-pdm** [comment]
Sahid Orentino Ferdjaoui <notifications@github.com> writes:

> There is no way to determine an exact number

Right.

> Trying to guess per request depending of the VM spec does not seems
> right. It depends of too many factors

It's still much better than no qualified guess at all.

> and then what about hotplug?

Hot plug isn't part of a VM overhead.  If you know VM resource
requirements in advance, you can just allocate them.

> My idea is just a global amount of memory reserved on hosts. avail = free - reserved
>
> I guess It's more beneficial to report the exact resource a host can
> address to the scheduler. An other reason is that the users may run
> some third-party services which also consume memory. Having a tunable
> on host would provide for operator an instrument to reserve memory
> depending of workload.

It may make sense to reserve resources for third-party services.  But
otherwise keeping free resources “just in case” or even to cover VM
overhead may mean resource wasting.  I'd prefer to see schedulers
handling the load and re-arranging the running objects appropriately
rather than trying to adjust the limits manually as needed at any given
moment.

Anyway, reserved resources and VM overhead should be kept separate –
reserved host resources are not a good substitute for the latter.

**Comment by sahid** [comment]
I'm not agree on saying that "It's still much better than no qualified guess at all" If we can't be exact, we don't do. But we should provide some ways for operators to deal with it and make it clear.

**Comment by davidvossel** [comment]
The VM API redesign in #606 helps move this forward.

The new way of expressing cpu/memory requirements on the VM api closely maps to the Pod's request limits. It should just be a matter of taking the VM requirements, adding the overhead padding, and placing those values on the VMs pod.

**Comment by fabiand** [comment]
Fixed with #673
