### ISSUE TITLE
"Configurations VirtualMachineInstance definition with guestAgent should have attached an guest agent channel by default" is N/A

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1702]
/kind bug

**What happened**:
Tets is skipped?

**What you expected to happen**:
Test is not skipped.

**How to reproduce it (as minimally and precisely as possible)**:
Expand the table here https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/
and look for the testcase.

**Anything else we need to know?**:
Not sure if it's a bug that there is N/A. Is it?

**Comment by petrkotas** [comment]
I went through the logs, so I will summarize my findings.

1) Skipped guest agent test is not bug. The skipped tests are for windows, which is fine, since currently there is no way of testing the guest agent on windows.
2) The N/A is indeed a bug, but not in the testing code. The N/A test an old version I had in development phase, it never made to the master. 

Started investigation about the 2).

**Comment by fabiand** [comment]
The automation which identified this bug does ignore skipped tests.
However, it does not differentiate between merged and unmerged PRs.

Instead it looks for the most often appearing failing cases.

WRT 2 - It can well be that the bug in the development code lead to the
many falures.
I'd recommend to look at the most recently merged PR to see if the bug
still exists.

**Comment by petrkotas** [comment]
There is no bug in the development code. It was just change in the label of the test. What I believe is happening, is that tests try to run nonexistent test and thus result in N/A.
From the code perspective, the failing test is not present.

**Comment by fabiand** [comment]
True! The test case is not there anymore.

And the jobs I checked there the new *attached a guest* was not failing.

Closing this one.

Thanks for checking.
