### ISSUE TITLE
Define supported CPU models and validate VM.spec.cpu.model

### ISSUE THREAD

**Issue by yanirq** [kubevirt/kubevirt#1760]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

Related to https://github.com/kubevirt/kubevirt/pull/1721#issuecomment-441564441 

Now that we are introducing scheduling virtual machines on nodes according to CPU model (https://github.com/kubevirt/kubevirt/pull/1721) by matching the vmi.spec.cpu.model to supported cpu models on nodes (nodes are labelled by [NFD Libvirt](https://github.com/ksimon1/node-feature-discovery-libvirt) [WIP]),  we need to define and validate the cpu models that can be set on a VMI spec according to the CPU map provided by libvirt. 

One reason for that need is if the CPUNodeDiscovery feature-gate will be enabled (disabled by default) 
and a vmi.spec.cpu.model wont match existing labels on nodes (due to a typo for example), the error on vmi / virt-launcher will be a general FailedScheduling message.
(In case the CPUNodeDiscovery feature-gate is disabled,  the error message we would get is a libvirt error for a wrong model)

**Comment by yanirq** [comment]
Adding @rmohr @fabiand  @MarSik  to the discussion : 
- Is this a valid need ? 
- If implemented, what is preferable : open API, validation web-hooks ?

**Comment by MarSik** [comment]
libvirt no loger defines names for all combinations of features ([1]). I think we want to define custom kubevirt CPU model + flags/features combinations, expose them using NFD and use them in virt-launcher.

There are couple of data fields we need:
- Human readable name for the "model"
- Base model + extra features (+ their mode) for libvirt domxml
- Base model + extra features for nodeSelector (compatible with NFD)
- Model for NFD created labels (unique model identifier)

Since this needs to be visible both to NFD and virt-launcher, we should probably create either a CRD (one per model?) or at least a ConfigMap.

A feature gate should be used to switch between pure libvirt, libvirt + custom and custom only models (this would allow extending or limiting per product needs).

[1] For example see SSBD security related flag that must be forced: https://www.redhat.com/archives/libvir-list/2018-May/msg01562.html

**Comment by MarSik** [comment]
As to the validation question:

- libvirt model validation can't be done without libvirt which is only accessible from virt-launcher. But an admission controller could inherit from kubevirt/libvirt base container (without starting the daemon even) to get access to the data
- custom model validation in my proposed direction can be done from anywhere as CRDs and ConfigMaps are easily accessible

**Comment by fabiand** [comment]
> libvirt no loger defines names for all combinations of features ([1]). I think we want to define custom kubevirt CPU model + flags/features combinations, expose them using NFD and use them in virt-launcher.

+1

Each component should individually tell what CPU families it accepts or exposes. Individually.
Then we can have another mechanism which is syncing these two parts.

So, for KubeVirt, let's explicitly state what CPU families are supported, and validate that we only accept then.
It is then another problem to sync this between KubeVirt and NFD.

And this is actually true for CPU features as well: Each component should state exactly which feature sit is consuming/exposing, then we have a mechanism to sync multiple components as needed.

>     * libvirt model validation can't be done without libvirt which is only accessible from virt-launcher. But an admission controller could inherit from kubevirt/libvirt base container (without starting the daemon even) to get access to the data

We can parse the cpu map in some other component as well I suppose.

**Comment by fabiand** [comment]
There are two sides: A producer/provider of CPUs and consumer, using CPUs.

The VM is the CPU consumer, as the VM is using the CPUs of a host.
The NFD is the CPU producer, as it's exposing what CPUs are offered on a given host.

For the consumer we should define which CPUs it can _in general_ consume from a host. (i.e.f or qemu x8664 we should list what CPUs are supported at all!). We can define this by validating/permitting only the CPUs which we know will work with our x8664/q35 VMs.

For the producer we should define what CPUs it can produce provide, based on the host CPU informations. NFD will "define" this by exposing the supported CPUs of the ndoe it's running on.

Then, finally, the integrator can choose from both sets, which CPUs he would like to support in the cluster. But this is anohter step.

All I am trying to say is that
- NFD should have a well defined set of names it can potentially expose.
- VM should define a well defined set of names it can potentially consume.

It's about agreeing on the exact names, nothing else - in order to avoid things like ´conroe` vs `Conroe` vs `Intel Controe` vs `Conroev2`.

**Comment by MarSik** [comment]
Do not forget what I raised above: The integrator might want to define **artificial names** that define a combination of the above. Scheduling is a separate affair (NFD, pod) from VM configuration (domxml). 

And all sides could simply agree to load the list of supported combinations from the environment. The integrator is then responsible for taking both sides into account and only describing valid combinations.

A matter of validating the VM definition during save against the supported list and libvirt domcapabilities is a technical detail.

**Comment by fabiand** [comment]
For the CPU features

I assume that we go with something like:

```
model: Conroe
features: [msr, pae, mce, cx8, apic, sep, mtrr, pge]  # Just an example!
```

**Comment by MarSik** [comment]
Actually, I was thinking about something like (also an example):

```
kind: CpuModel -- if we decide on CRD
name: Intel Conroe (secure) -- Human readable
id: conroe-secure
nodeLabels: -- scheduler hints
  feature.node.kubernetes.io/cpu-model-conroe
  feature.node.kubernetes.io/cpu-feature-ibrs
libvirt: -- domxml hints
  model: conroe
  features:
  - feature: virt-ssbd
    policy: force -- [1]
  - feature: ibrs
```

VM.spec.cpu.model would then reference conroe-secure and virt-launcher would properly convert it to the right domxml and nodeSelectors.

[1] https://www.redhat.com/archives/libvir-list/2018-May/msg01562.html

**Comment by MarSik** [comment]
Just to make one point clear. The disctinction between scheduler and libvirt layers is intentional and needed. The mailinglist link [1] above shows a case where a feature must be forced even though the host is not exposing it.

**Comment by fabiand** [comment]
This is fixed.
