### ISSUE TITLE
Fedora vmi console got stuck at "[  OK  ] Started Login Service."

### ISSUE THREAD

**Issue by duyanyan** [kubevirt/kubevirt#1847]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind bug

**What happened**:

```
# oc get pod
virt-launcher-vmi-fedora-27znw         2/2       Running   0          5m        10.128.0.111
# oc get vmi
NAME         AGE
vmi-fedora   5m
# oc describe vmi vmi-fedora
Name:         vmi-fedora
Namespace:    kubevirt
Labels:       kubevirt.io/nodeName=dev-test
              special=vmi-fedora
Annotations:  <none>
API Version:  kubevirt.io/v1alpha2
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2018-12-15T05:03:25Z
  Generation:          1
  Resource Version:    178612
  Self Link:           /apis/kubevirt.io/v1alpha2/namespaces/kubevirt/virtualmachineinstances/vmi-fedora
  UID:                 c0917da1-0026-11e9-9a46-80c16e6c5154
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:        virtio
        Name:         containerdisk
        Volume Name:  registryvolume
        Disk:
          Bus:        virtio
        Name:         cloudinitdisk
        Volume Name:  cloudinitvolume
    Machine:
      Type:  
    Resources:
      Requests:
        Memory:                      1024M
  Termination Grace Period Seconds:  0
  Volumes:
    Container Disk:
      Image:  kubevirt/fedora-cloud-container-disk-demo:latest
    Name:     registryvolume
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
    Name:  cloudinitvolume
Status:
  Node Name:  dev-17.rhev.lab.eng.brq.redhat.com
  Phase:      Running
Events:
  Type    Reason            Age              From                                              Message
  ----    ------            ----             ----                                              -------
  Normal  SuccessfulCreate  6m               virtualmachine-controller                         Created virtual machine pod virt-launcher-vmi-fedora-27znw

  Normal  Created           5m (x2 over 5m)  virt-handler, dev-test  VirtualMachineInstance defined.

  Normal  Started           5m               virt-handler, dev-test  VirtualMachineInstanced started.
# virtctl console vmi-fedora
Successfully connected to vmi-fedora console. The escape sequence is ^]
                                                                       [    0.000000] Linux version 4.18.16-300.fc29.x86_64 (mockbuild@bkernel04.phx2.fedoraproject.org) (gcc version 8.2.1 20180801 (Red Hat 8.2.1-2) (GCC)) #1 SMP Sat Oct 20 23:24:08 UTC 2018
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.18.16-300.fc29.x86_64 root=UUID=01043a6a-fca2-4a1d-af0c-3463a132e851 ro no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8 LANG=en_US.UTF-8
----------------------------------8<-----------------------------------
[  OK  ] Started NTP client/server.
[    9.103485] [drm] Initialized bochs-drm 1.0.0 20130925 for 0000:00:01.0 on minor 0
[  OK  ] Started System Security Services Daemon.
[  OK  ] Reached target User and Group Name Lookups.
         Starting Login Service...
[  OK  ] Started Login Service.
```
**What you expected to happen**:
console works normally

**How to reproduce it (as minimally and precisely as possible)**:
Create a fedora vmi with kubevirt/fedora-cloud-container-disk-demo:latest

**Anything else we need to know?**:
1. cluster: deploy openshift 3.11 on a centos physical host by openshift-ansible
2. Can not reproduce the issue with fedora image kubevirt/fedora-cloud-container-disk-demo:v0.11.0 and cirros image.
3. Can not reproduce the issue on openshift cluster setup on openstack 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.12.0-alpha.1
- Kubernetes version (use `kubectl version`): v1.11.0+d4cacc0 
- VM or VMI specifications: https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vmi-fedora.yaml
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:

**Comment by duyanyan** [comment]
I deployed a new openshift+kubevirt+sriov env on another sriov capable machine and I can't reproduce the issue any more. So I think it may relate to the hardware. Let's close the issue. Feel free to reopen it when meet the issue again. Thanks

**Comment by booxter** [comment]
I've hit this issue on my new SR-IOV hardware. This happens with Fedora, whether it's attached to SR-IOV or not; but Cirros boots fine and I can log into the console. I'll investigate more.

**Comment by booxter** [comment]
I finally have an explanation of what's going on here.

It turns out that with newer guest kernels, boot process may get stuck if the guest doesn't have enough entropy generated for it. This happens all the time during Fedora boot process. A workaround is connecting to the guest via VNC and moving your mouse a bit, which gives enough pseudo-entropy for RNG to produce output and unlock boot process.

It seems that it started happening in recent kernels: https://marc.info/?l=linux-kernel&m=152471887030737&w=2

There are several Red Hat bug reports for this, some closed for public:
https://bugzilla.redhat.com/show_bug.cgi?id=1639840
https://bugzilla.redhat.com/show_bug.cgi?id=1593843

A solution is to add `rng` device to VMI manifest:

```
spec:
  domain:
    devices:
      rng: {}
```

At the very least, we should probably add `rng` to all Fedora examples. Also, `user-guide` should be updated to describe this behavior in the section about `rng`. Finally, we may want to consider adding the device by default to all VMIs to avoid similar bug reports in the future: while the issue can not be easily reproduced with Cirros or Alpine due to different services started as part of their boot process, there may be in-guest payloads that would still require entropy, at which point they could also be stuck. And since this behavior will be seen in all fresh kernels, it may be a sensible default for Linux guests.

**Comment by booxter** [comment]
adding rng to fedora examples: https://github.com/kubevirt/kubevirt/pull/2429
