### ISSUE TITLE
Qemu instances are killed if the Libvirt pod goes down.

### ISSUE THREAD

**Issue by stu-gott** [kubevirt/kubevirt#196]
Our current approach leverages Libvirt inside a container. This libvirt process starts qemu instances as virt-handler requests them. Since this libvirt container originally started those processes, if that pod goes down or is restarted each qemu instance it created is also killed.

In the normal workflow, this is not an issue. If Libvirt stays running, so will each qemu instance. If the libvirt pod needs to be updated, an admin can simply evacuate the host before updating. The concern here is error/edge cases. If libvirt were to crash for some reason, each qemu instance spawned by it would be terminated.

Possible mitigation strategies include:

1) Adding systemd to the libvirt container (so that the pod will continue to run even if the libvirt process terminates--and systemd will restart it). This doesn address the case where the pod itself goes down for some reason.
2) Make the virt-launcher pod responsible for starting the qemu process. This will require some changes to our qemu-kvm wrapper script and some glue on the virt-launcher side. This obviously increases the complexity of our approach a bit so we'll need to ensure this mechanism is robust/secure if we choose this approach.

**Comment by michalskrivanek** [comment]
its likely systemd, not libvirtd. I think you run it within the pod as well? 
It would be best to leave this on libvirt to provide the right container which suites them.

**Comment by davidvossel** [comment]
I'm just getting caught up to speed with this project, so it's possible there is some context I'm missing. However, my first inclination to this issue is that we shouldn't be running libvirt in a container.

Have we considered starting libvirt natively on the parent host using systemd similar to how the docker daemon and the kubelet agent are managed?

Under normal operation (libvirt not in a docker container), libvirt isn't coupled with the VM processes, meaning if libvirt crashes/restarts it shouldn't be taking down any VMs with it.  In a container, if libvirt is pid 1 and pid 1 crashes, everything that is a child of that pid goes down with it.  Outside of the container if libvirt crashes, the children are inherited by systemd. 

Having all the VMs tied to the life-cycle of the libvirt container seems like a bad idea.

**Comment by stu-gott** [comment]
The context for our current approach is that we're trying to minimize the system requirements imposed on the host system--in order to reduce friction for deployment. One goal is to be able to deploy KubeVirt on Minikube. Also mandating the requirement that the host system needs to be running (a specially configured) libvirt kind of gets underfoot.

Incidentally the project started out with libvirt running on the host system--and there's one small caveat to running in that configuration. We have an emulator script that's responsible for locating the virt-launcher pod, changing cgroups/namespaces and launching qemu. This script must be placed on a specific path on the host system (/usr/local/bin/qemu-x86_64).

That said, your concerns and conclusions are well founded! If libvirt is pid 1 and libvirt stops running for any reason, then "unscheduled lifecycle events" occur for all child processes--including VMs. This leads to the two mitigation strategies suggested earlier in this thread.

1) If the libvirt container is running with systemd, then libvirt can start/stop normally if needed. While this does allow greater latitude in terms of starting/stopping libvirt (e.g. crash recovery), it's still true that if the systemd process in the container stops, the same problems you mentioned manifest.

2) The lifecycle of the qemu process ideally should be tied to the virt-launcher pod--since by definition that pod exists to host the qemu process. The most direct way to accomplish that is to have the virt-launcher process be responsible for actually starting qemu. This means that the responsibility of the qemu emulator script needs to change. Instead of changing namespaces/cgroups and running qemu, it would need to send the proper command line arguments to virt-launcher. This comes with its own complexities and concerns of course--and it's not a perfect solution. I'm pretty sure that if the libvirt pod were to restart, it's going to lose track of currently running VMs--which is only 1 step better than having the VMs crash...

Anyways, just trying to shed some light on the decisions that led us to the current state.

**Comment by stu-gott** [comment]
To clarify, in the second case, the intent would be to send the qemu command line args to the virt-launcher daemon via e.g. socket. virt-launcher would fork/exec the qemu process. This would in fact sidestep the child inheritance issue we currently have with libvirt because qemu would be started in the pod it was supposed to be a part of all along. (of course this creates other caveats we would need to deal with).

**Comment by fabiand** [comment]
Yes, if libvirtd is running in a container, then VMs are tied to the life-cycle of the container, and this is obviously a drawback.

But it's also clear that KubeVirt should be an add-on to Kubernetes, and this has the constraint, that we need to ship all dependencies in containers, as we can't make assumptions on the underlying hosts (i.e. that libvirtd is present or configured in a specific way).

And yes, systemd moves tihs particular problem around, but it also improves the situation a little.

So, that's [status quo](https://www.youtube.com/watch?v=t-8K8Hj8bxE), limited by the features available today. To me this state is sufficient for now - in our pre-alpha stage.

On the long run we probably want to understand what exactly is killing the VMs in our case. Is it implicit when the container is getting killed? Or part of the cleanup process of the kubelet or runtime? Are there differences between container runtimes?
I'm saying that we probably want to get a complete understanding, to be able to understand how we can solve it right.
One thing to note here is that other Kubernetes workloads might also have the requirement of keeping long-running processes alive, even if the container or pod goes down. I.e. expensive compute tasks.
Maybe that's a lever for us to get this into Kubernetes.

Another approach could be to inject qemu into the host and launch the process there - but that's not so nice, because we move a binary into a suburb (host fs) which is neither controlled nor owned by us.

**Comment by fabiand** [comment]
With the decentralized approach, there will not be a single pod responsible for all VMs, the critical chain is now kubelet, container runtime. But IIRC both are not cilling wrkloads if they go down themselfes.

**Comment by fabiand** [comment]
With the decentralized approach, there will not be a single pod responsible for all VMs, the critical chain is now kubelet, container runtime. But IIRC both are not cilling wrkloads if they go down themselfes.
