### ISSUE TITLE
VMIs with delegated IPs are stopped by the kubelet if kubelet is restarted

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2076]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

When connecting the VMI via `bridge` mode and IP delegation to the pod network, CNI status checks fail and as a consequence the kubelet stops all containers of that pod when the kubelet is restarted.

I checked it on k8s 1.10.4 and k8s 1.13.3. I *think* that the hint in the logs is this:

```
Mar 04 09:28:43 node01 kubelet[29530]: W0304 09:28:43.167534   29530 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "virt-launcher-vmi-nocloud-v4j2m_default": Unexpected address output
```

I did not try it with ovn-cni, crio, just flannel.

**What you expected to happen**:

The VMIs should not be killed by the kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ cluster/kubectl.sh create -f cluster/examples/vmi-nocloud.yaml
$ cluster/kubectl.sh create -f cluster/examples/vmi-slirp.yaml
$ cluster/kubectl.sh get vmis
NAME          AGE   PHASE     IP            NODENAME
vmi-nocloud   15s   Running   10.244.0.32   node01
vmi-slirp     1m    Running   10.244.0.31   node01
$ cluster/cli.sh ssh node01
$ sudo systemctl restart kubelet
$ cluster/kubectl.sh get vmis
NAME          AGE   PHASE     IP            NODENAME
vmi-nocloud   34s   Failed    10.244.0.32   node01
vmi-slirp     1m    Running   10.244.0.31   node01
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dankenigsberg** [comment]
/topic network
Can you set it, @SchSeba?

I'd appreciate if we can make `masquerade` our default, so that only people who cannot work behind NAT suffer from this bug.

**Comment by phoracek** [comment]
@rmohr thanks for reporting that, I will look into it.

**Comment by davidvossel** [comment]
> I'd appreciate if we can make masquerade our default, so that only people who cannot work behind NAT suffer from this bug.

This is proposing to change an API default to work around a bug. We can have that discussion, but we need to be clear on what this involves. 

Changing an API default like this has the potential to impact more users than this bug. Since this would be an API breaking change, it would mean a bump in the API version. bumping the api version has a ripple effect across multiple projects. In addition to this, users who depended on the default pod interface binding then have perform some manual steps to reconfigure their VMs to ensure they continue behave as expected.

we should avoid doing something like this if at all possible.

**Comment by davidvossel** [comment]
also, it would be nice to know if this impacts crio or is isolated to docker.

**Comment by dankenigsberg** [comment]
> This is proposing to change an API default to work around a bug

The current default disallows live migration. As such, I don't like it as a default regardless of this bug.
I'm not sure that this consists of an API breakage; it is a change of behavior. But clearly it is likely to break user expectations, and deserves careful considerations.

We should look for a workaround, as `bridge` is a valid use case for us, and it has to survive kubelet restart.

**Comment by phoracek** [comment]
The problem is: On the first setup, kubelet runs CNI, gets back IP of the pod, all is good. After that we move this IP address to VM. Next time kubelet starts, it tries to sync pods, calls CNI status method, no IP is returned (hello VM) and therefore it fails.

I tried to fool kubelet and it worked: I set an adress (1.2.3.4/32, yay) on eth0 of virt-launcher pod and the pod survived restart. However, it now reports 1.2.3.4 as pod's address.

I want to try this: Rename eth0, create dummy eth0 interface and give it original eth0 IP and MAC addresses. It should not affect the network, but it should give kubelet expected address. What do you think @davidvossel @rmohr

**Comment by davidvossel** [comment]
> I want to try this: Rename eth0, create dummy eth0 interface and give it original eth0 IP address. It should not affect the network, but it should give kubelet expected address. 

It's unclear to me if this method will mitigate the issue for all possible CNI plugins.  For example, when the CNI status method is called, what logic is being executed to return the status? Is that logic CNI plugin specific, or something generic?

**Comment by phoracek** [comment]
CNI has `ADD`, `DEL` and `CHECK` calls. `ADD` returns list of created interfaces with their name, IP, MAC.

`CHECK` takes configuration that was previously passed to `ADD` and result of `ADD`. `CHECK` should validate that current state of pod's network matches requested state. 

My educated guess would be that kubelet fails on this check. I will try to investigate whether this is the case or if there is some check on the kubelet side.

**Comment by phoracek** [comment]
Great, the check is done by kubelet, we know what to work around :) It just reads eth0 address and exposes it on the pod object. Therefore all we need to do is to create eth0 interface on the host and give it the IP. Thoughts @davidvossel? Sorry for the confusement in the previous comment. 

https://github.com/kubernetes/kubernetes/blob/2d956389dc57fb1715d1832b2d22c042de59bd1d/pkg/kubelet/dockershim/network/plugins.go#L226

**Comment by phoracek** [comment]
As @SchSeba pointed out offline, we can't really replace eth0 with a fake interface since it could in theory affect CNI `DEL` of some plugins.

If someone has running CRIO instance, could you please try to reproduce the bug? My laptop has troubles running cluster/os-3.11.0-crio.

**Comment by fabiand** [comment]
Side note: IIUIC SLIRP would not be suffering this issue, Is this correct @phoracek ?

**Comment by davidvossel** [comment]
>Therefore all we need to do is to create eth0 interface on the host and give it the IP.

doesn't that assume that all CNI plugin CHECK functions only look for the IP of eth0? I'm not sure we can make that assumption.

**Comment by rmohr** [comment]
On Wed, Mar 6, 2019 at 11:21 PM David Vossel <notifications@github.com>
wrote:

> Therefore all we need to do is to create eth0 interface on the host and
> give it the IP.
>
> doesn't that assume that all CNI plugin CHECK functions only look for the
> IP of eth0? I'm not sure we can make that assumption.
>

Hm, I am not sure, but I think I saw the CHECKs from the CNI plugins
already failing all the time. Just on kubelet restarts, as Petr discovered,
the kubelet does this one-time-check again and because it can't determine
the IP it stops the pod. I think all CNI plugins always create eth0 by
default in k8s. That's the expectation. But if we e.g. use multus we would
have to do the same trick for every device and create a dummy device with
the original name. Can that be?

**Comment by phoracek** [comment]
@davidvossel sorry for the confusion, I later found that it is not the CHECK what fails, it is code hardcoded in kubelet/dockershim. It looks for eth0 and reads its IP, so it is later exposed in the Pod state.

I'm not sure if the same check happens on CRIO (is dockershim under CRIO or a different branch?).

@rmohr I don't know whether the CHECK is used at all in Kubernetes, but if it is, moved IP address should definitely cause its failure.

The issue is, that if we create this fake interface, we could break CNI DEL logic of some plugins. If a plugin does some magical handling of the interface before its removal and it expects **insert your eth0 veth interface specific attribute**, it might break.

Multus just exposes assigned addresses in Pod's annotation, kubelet does not know about any of this. So unless there is similar check after restart on Multus side, it should not fail. Worth a try though.

Ok so, CNI DEL of some plugins might have problems even now with the IP address removed. By introducing a fake dummy interface, we might make it even worse. I don't have any proof that this causes a problems though. Can you think about any other way how to fool kubelet? I will create PR for the dummy hack in the meanwhile.

**Comment by phoracek** [comment]
@fabiand that's right, SLIRP and masquerade should not touch the IP address

**Comment by dankenigsberg** [comment]
> If someone has running CRIO instance, could you please try to reproduce the bug? My laptop has troubles running cluster/os-3.11.0-crio.

I bet @myakove or @duyanyan can help with that.

**Comment by duyanyan** [comment]
I tested on the OCP3.11(crio). I restarted the node service instead of restarting kubelet. I didn't meet the issue.
```
$ oc get pod -o wide -w
virt-launcher-vmi-nocloud-vdd9t   2/2       Running   0         3m        10.131.0.25   cnv-executor-yadu14-node1.example.com   <none>
virt-launcher-vmi-slirp-4sgqz   2/2       Running   0         2m        10.131.0.26   cnv-executor-yadu14-node1.example.com   <none>
virt-launcher-vmi-nocloud-vdd9t   0/2       Running   0         3m        10.131.0.25   cnv-executor-yadu14-node1.example.com   <none>
virt-launcher-vmi-slirp-4sgqz   0/2       Running   0         2m        10.131.0.26   cnv-executor-yadu14-node1.example.com   <none>
virt-launcher-vmi-slirp-4sgqz   2/2       Running   0         2m        10.131.0.26   cnv-executor-yadu14-node1.example.com   <none>
virt-launcher-vmi-nocloud-vdd9t   2/2       Running   0         3m        10.131.0.25   cnv-executor-yadu14-node1.example.com   <none>
```

**Comment by dankenigsberg** [comment]
@duyanyan, could you also try killing the kubelet process on the host? At least for docker, that's where the relevant code is.

**Comment by phoracek** [comment]
@duyanyan thanks for testing it

Proposed fix: https://github.com/kubevirt/kubevirt/pull/2100

**Comment by renner-osi** [comment]
Has any discussion been had around allowing the virt-launcher pods to pass the various CNI created interfaces into the virtual machine without interference? 

In testing and use over last months we've seen https://github.com/kubevirt/kubevirt/pull/1534 and https://github.com/kubevirt/kubevirt/pull/1621 .

 I see above that some use cases depend on the bridge so maybe this is not desirable. My team and I are now facing issues with the bridge once again eating control plane packets like LLDP and LACP which has me wondering if the bridges utilization versus allowing the domain definition to use PCI passthrough is worth it ? Wouldn't the above issue be mitigated as well without moving and mac addresses or IPs around ? The other thing that comes to mind in reading this issue is that some CNI's specifically record and depend on the mac address which im not certain will be possible with dummy interface.

**Comment by dankenigsberg** [comment]
> Has any discussion been had around allowing the virt-launcher pods to pass the various CNI created interfaces into the virtual machine without interference?

@booxter starting to work on that for sriov. I would like to do that also for bridges, by passing a tap device from qemu directly to the host bridge. We do not have immediate action items for that. If this is what you want, maybe you can file an issue about it.

**Comment by npu21** [comment]
@rthallisey has this issue resolved?

**Comment by rthallisey** [comment]
yes: https://github.com/kubevirt/kubevirt/pull/4552

**Comment by fzu-huang** [comment]
@rthallisey  in `bridge` mode we will rename `eth0` and recreate a new `eth0` (dummy) , this might  affect CNIDel , has this problem resolved?

**Comment by fzu-huang** [comment]
Even set pod ip on a fake `eth0` is dangerous,  if we connect vm from its host by route, such as:
```
192.168.3.3 dev xxxx scope link  # 192.168.3.3 is pod IP
```
Packet will be receive by this fake `eth0`  and response in container, but not VM,  and telnet 192.168.3.3 22 will be `connection refused` by container.
