### ISSUE TITLE
With containerized libvirt, SIGKILL only reaches the emulator, not qemu

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#210]
When a VM does not shut down, you can normally destroy a VM via libvirt. It will send a SIGKILL to qemu, to make sure it is stopped. However, in the containerized version, SIGKILL is only sent to the emulator and therefore never reaches the qemu processes.

I am not yet sure, why this works on the host.

**Comment by fromanirh** [comment]
@rmohr please use @fromanirh next time. With "the emulator" you mean the program listed in the <emulator> section of the domain XML, right?

**Comment by berrange** [comment]
I wonder if this is due to the way the QEMU wrapper script runs. Currently the wrapper script exec's bash sudo, which then runs QEMU. So you always still have the bash process and the QEMU process running. SIGKILL will get delivered to the bash process. In my PR, https://github.com/kubevirt/kubevirt/pull/242  the qemu wrapper script is changed so that bash exec's QEMU, so once QEMU is running, bash is gone. Thus SIGKILL will get delivered straight to QEMU as the lead process

**Comment by fabiand** [comment]
Wasn't this issue fixed by using the traps, @rmohr? (and now superseded by @berrange 's change)

**Comment by rmohr** [comment]
@fabiand right it was. I think we can close this one. Related discussion about PIDs, signals and process inheritence continues in #28.
