### ISSUE TITLE
make test after bazel changes not accurate

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#2127]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

'make test' with bazel returns cached results. Developers who are working on unit tests aren't receiving feedback that is accurate to the tests they are developing.

**Comment by rmohr** [comment]
@davidvossel could you post an example where it was not accurate? Bazel has a full view on all dependencies of tests. It should only rerun tests if "something" (no matter what, test dependency like an image, a single line of code) changes.

**Comment by rmohr** [comment]
I did some tests and everything looks correct to me.

**Comment by rmohr** [comment]
ok, see it. The issue seems to be that the tests are picked up by introspection by ginkgo, so no visible dependencies ...

**Comment by rmohr** [comment]
Ha, this is a funny issue. Got the reason: It happens when e.g. `dns_suite_test.go` in the `dns` directory is has `package dns` and a file with the actual tests like `resolver_test.go` is in package `dns_test`, or the other way round.

That is also the reason why goveralls does not pick up the tests. We have some test packages where everything is right, and some where we have an import mix. I will post a fix tomorrow.
