### ISSUE TITLE
How to access the graphical console(vnc) using noVNC

### ISSUE THREAD

**Issue by yinjingjiu** [kubevirt/kubevirt#2339]
Dear friend
    Kubevirt is an excellent project, I am using it. When I start the VM via kubevirt, I found an API.
    -----
    wss://192.168.4.102:6443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm/vnc
    -----
    How can I connect to vm using novnc?
    Thanks in advance.

**Comment by SchSeba** [comment]
Hi @yinjingjiu there is a specific reason you want to use noVNC?

I general we support a vnc connection and also console one using the `virtctl` command.

Example:
`virtctl console centos`
Or
`virtctl vnc centos`

you can download the CLI from the release page https://github.com/kubevirt/kubevirt/releases/tag/v0.17.0

**Comment by yinjingjiu** [comment]
> 您好@yinjingjiu有一个特殊原因要使用noVNC吗？
> 
> 我一般我们支持vnc连接，也使用`virtctl`命令控制一个。
> 
> 示例：
> `virtctl console centos`
> 或
> `virtctl vnc centos`
> 
> 您可以从发布页面下载CLI https://github.com/kubevirt/kubevirt/releases/tag/v0.17.0
Dear @SchSeba 
I want to access in the browser, But I don't know how to use this api.
Can you give me a suggestion? thanks.

**Comment by SchSeba** [comment]
Hi @yinjingjiu what platform are you using (openshift/k8s) ?

I am not sure if you can access the vnc using only novnc because the url is under the k8s api so you will need to send the kubeconfig for authentication and authorization.

I know that we support vnc in the browser in the openshift-ui related to this PR https://github.com/kubevirt/web-ui/pull/36

maybe @mareklibra can help you?

**Comment by yinjingjiu** [comment]
Dear @SchSeba  @mareklibra  
    I am using k8s, I have never used openshift, Can you teach me how to access a virtual machine in a browser? 
    Thank you very much.

**Comment by slintes** [comment]
Hey @yinjingjiu, did you consider to use the kubevirt web ui? It's a UI which you can install on top of the current openshift UI, with support for for virtual machines, including console/vnc connections. See https://github.com/kubevirt/web-ui.

**Comment by yinjingjiu** [comment]
Dear @slintes , Thank you for your help, I want to implement a vnc connection myself, but using kubevirt web ui requires openshift support. I don't currently plan to use openshift .

**Comment by mareklibra** [comment]
Hi @yinjingjiu , the novnc connects to a WSS provided by kubevirt via k8s API subresource.
There's no magic, just a couple of steps to pass. Please have a look at `kubevirt-web-ui` implementation:
- entry point: https://github.com/kubevirt/web-ui/blob/master/frontend/public/kubevirt/components/vmconsoles.jsx
- connection details are prepared [here](https://github.com/kubevirt/web-ui/blob/bfb856bc3c4dc23908f80a7c9da2dc957172a3ee/frontend/public/kubevirt/components/utils/resources.js#L41). Please note, our application proxies connection to k8s API (and so to the VNC WSS) due to `same-origin-policy`. Not sure if your application is in similar situation.
- Dig deeper to [VmConsoles](https://github.com/kubevirt/web-ui-components/blob/9db34ed60c5b4fb7ad01fbcbe102bdf69ee5bf75/src/components/VmConsoles/VmConsoles.js#L87), 
- till you reach actual novnc use within [VncConsole](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/src/VncConsole/VncConsole.js) component, check the tear up/down steps there.

The code uses React but I believe it's understandable even without deeper React knowledge.

**Comment by yinjingjiu** [comment]
@mareklibra thank you for your help, I was inspired.  you are a star

**Comment by slintes** [comment]
that sounds like your question is answered, can we close this? :slightly_smiling_face:

**Comment by yinjingjiu** [comment]
Thanks to every teacher for their help.🙂

**Comment by wavezhang** [comment]
I wrote a tool called [virtVNC](https://github.com/wavezhang/virtVNC) that helps kubevirt users connecting vms using noVNC .🙂

**Comment by slintes** [comment]
@wavezhang that sounds awesome!
I'm wondering if we should try it and maybe blog about it?
@fabiand @codificat wdyt?

**Comment by fabiand** [comment]
That's really awesome!
And yes, blog sounds pretty good fit for it, as having VNC access is
usually a common request.

>

**Comment by codificat** [comment]
Great indeed, thanks for sharing.

@wavezhang if you are willing / available to contribute a blog post about it I'd encourage you to. FYI there are some [guidelines](https://github.com/kubevirt/kubevirt.github.io/blob/master/GUIDELINES.md) on how to contribute content (including blog posts), and you can look at some [sample PRs](https://github.com/kubevirt/kubevirt.github.io/issues?q=label%3Asize%2FL+label%3Akind%2Fblog+is%3Aclosed) for inspiration.

In any case we'd be happy to try it ourselves and either review the contributed blog post or add one of our own.
/cc @iranzo @ptrnull

**Comment by wavezhang** [comment]
OK, I'll add a blog post later.
