### ISSUE TITLE
the vmi can never be deleted.

### ISSUE THREAD

**Issue by linqingping** [kubevirt/kubevirt#2491]
when I create vm the pod unschedulabe ，when I delete vmi the vmi can never be deleted

**Comment by linqingping** [comment]
![image](https://user-images.githubusercontent.com/20528139/61274358-3ed16780-a7de-11e9-8880-50749e13e0c2.png)
![image](https://user-images.githubusercontent.com/20528139/61274385-4b55c000-a7de-11e9-822e-132a048cb165.png)

**Comment by rmohr** [comment]
@linqingping from the snippet you shared, I can see `Error from server: etcdserver: request is too large`. That sounds like there is an issue in the cluster. Is everything else working normally for you?

**Comment by linqingping** [comment]
![image](https://user-images.githubusercontent.com/20528139/61339381-26aa2880-a870-11e9-8ac5-14550572d4c9.png)
Other work is normal

**Comment by rmohr** [comment]
Hm, ok so let's approach this a little bit structured:

 1) The pod is not schedulable, but apparently ol the other ones are. Does the network attachment definition exist in the namespace of the VMI?

 2) could you schare your vmi definition? What in theory could be the reason on why it can't be deleted: There is an object limit of 1M per default in etcd. So it might be the case that the whole VMI object is almost exactly one 1M big. Now when you do a delete, the k8s apiserver adds more data to the object and then an asynchronous delete is performed. Maybe the additional data make the object bigger than 1M?

 3) It would be great if we can analyze your scenario, but in order to get rid of the VMI, you can probably do the following: First edit the VMI and delete all finalizers from it. Then do a force delete.

**Comment by rmohr** [comment]
@linqingping the reason finally that the nework attachment definition did not exist?
