### ISSUE TITLE
Convert to use the libvirt-go-xml APIs

### ISSUE THREAD

**Issue by berrange** [kubevirt/kubevirt#264]
Many of the libvirt APIs require use of XML documents for input or output. Currently KubeVirt has created a set of structs to represent the libvirt domain XML schema in pkg/virt-handler/virtwrap/api/schema.go

This is essentially duplicating a mapping that is already defined in the libvirt-go-xml file, but with less coverage of the domain schema. Rather than continuing to reinvent the wheel, we need to just use the libvirt-go-xml package directly.

**Comment by mykaul** [comment]
@berrange - with the intention of using XML end-to-end, including storing it in etcd, etc.? (I really dislike all the conversions between XML/YAML/JSON/whatever...)
I hope there's an easy, consistent and sane way to save XML in etcd though. Perhaps embedded in something (for example, VM name and some other items need to be copied from the XML?)

**Comment by berrange** [comment]
No, the XML is purely an internal thing for virt-handler to communicate with libvirtd. Every other part of KubeVirt must always use the higher level JSON/YAML description, because we must abstract away details of any host paths / resources.

**Comment by mykaul** [comment]
This is exactly what we are (finally) doing in oVirt. The Engine sends as much as possible complete XML and VDSM resolves on the host what it has to. But having it in XML as much as possible end-to-end seems to ease the work of adding new features from top to bottom, in many cases.

(See https://gerrit.ovirt.org/#/q/project:vdsm+branch:master+topic:engine-xml-mapping-storage for storage, https://gerrit.ovirt.org/#/q/project:vdsm+branch:master+topic:vm-devs-xml for the devices and https://gerrit.ovirt.org/#/q/project:vdsm+branch:master+topic:engine-xml for the infra. to do it).

**Comment by berrange** [comment]
oVirt has a different architectural model than we are aiming for here. We cannot expose the libvirt XML to anywhere outside the virt-handler because it compromises security of the entire system.

**Comment by rmohr** [comment]
@mykaul Also not that a difference to oVirt is, that virt-handler (daemon on the host) gets VM specifications with the same structure like a user posts them. So in the KubeVirt case you translate everything in the latest possible moment to XML from a public facing API, whereas the latest work in oVirt tries to translate from the public API to libvirt XML as soon as possible, and getting away from intermediate formats between the public API and the libvirt XML. If i understand the effort correctly.

**Comment by fabiand** [comment]
IIUIC Engine now tries to complete the final runtime specification (domxml) as soon as possible.
Thus now (with engine xml), vdsm is not adding significant parts to the xml representation on the host anymore (IIUIC). This is the significant change for me: The XML is created as early as possible in a single place. With a detailed control over the content.

With KubeVirt you are actually forced to do the same: Because a consumer (like Engine) is not allowed to change the low-level (internal-only!) spec of a VM, a consumer is required to submit a complete specification up front. And like in oVirt the consumer has the complete control.

One technical significant difference is obviously that a consumer has not the host-level control over the VM specification anymore (i.e. setting paths or specifying a pci address), but this is okay and intended.
It's the responsibility of KubeVirt to provide the right cluster level abstractions to enable the same or similar functionality as oVirt - and other consumers - has.

**Comment by mykaul** [comment]
The main reason I like the libvirt XML to be provided as soon as possible (from the topmost layer) is the breeze to add new features. Unless there's a need for further processing (host devices, storage connections, secrets, etc.), those are simple changes on the top layers and nothing to integrate with on the lower layers. Inc. no need to update them to consume the new features.
We are already seeing the benefit today in oVirt. Enabling a new switch (for example, for disks to report errors to the VMs or pause) is a matter of simple change on the Engine, and VDSM does not care about it.

**Comment by berrange** [comment]
The virt-handler is providing a trusted layer which acts as a security barrier between the unprivileged, untrusted tenant user, and the privileged, trusted libvirtd service. We must have an explicitly controlled mapping between the high level k8s exposed JSON/YAML, and the low level libvirt XML - any kind of generic 'passthrough' will inevitably lead to security flaws. Exposing new features to the tenant users will always require explicit work to enable in the virt-handler mapping code - this is an unavoidable requirement to maintain a strong security boundary. In many cases such mapping will be quite straightforward, so should not cause unreasonable time delays in features becoming available to users for simple things.

**Comment by fabiand** [comment]
@mykaul if KubeVirt would allow a way to provide the XMl from the topmost layer, how would it know how libvirt is run?
I.e. if it uses pod networking, or host networking? if it runs privileged enough to perform NFS mounts?
It is running in it's own pod and might not even see devices which it could be asked to passthrough.

And I do understand that it looks charming to just passthrough the xml, because oyu do not need to run after features. In oVirt this works, because it's a trusted chain from Engine down to vdsm.
In KubeVirt the chain of trust starts at the API server, and eny input to it needs to be verified.

Last note - Even if we'd allow bypassing the kubevirt spec, then it would still be a conflict of interest, because the domxml expects libvirt to work as directed to, but in kubevirt other assumptions are made.

**Comment by fabiand** [comment]
#273 provides some additional details on this topic.
