### ISSUE TITLE
Migrate TPR to CRD before k8s 1.8

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#284]
https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/

**Comment by fabiand** [comment]
Instead of moving to CRD, we actually considered to directly go with a User API Server and Api Server aggregation, as tracked in #205 .

CRD only provide little validation (if it has landed), no RBAC integration, and we'd need a separate API server for non-restful endpoints like a console stream.

Thus closing this ticker in favor of #205
