### ISSUE TITLE
Network barrier when use macvlan

### ISSUE THREAD

**Issue by lixiaocheng18** [kubevirt/kubevirt#2925]
Hello
When I use macvlan cni,  it can work on k8s normal pod. As shown in illustration:
![image](https://user-images.githubusercontent.com/7879970/70371402-7f588b80-190d-11ea-9e63-1f5a194e2af6.png)

But when I create VirtualMachine and use "virtctl start debian",  then I use "virtctl console debian" enter the console, I found the Internet doesn't work. As shown in illustration:

![image](https://user-images.githubusercontent.com/7879970/70371470-597fb680-190e-11ea-897a-126fc067cb77.png)

Anyone know what happen? Thank you.

**Comment by zakkg3** [comment]
Same case here, works on normal pods. but not in the VM
master of the macvlan iface
I did a tcpdump on the iface master of the macvlan iface and then ping vlan outside, i can see the packet going out and then the reply... but this reply is not fw to the vm... then i found this:
https://superuser.com/questions/1205346/macvtap-interface-created-on-top-of-macvlan-interface-of-a-docker-container-cann
`If you will add any other interface on bottom of macvlan. For example bridge or other macvlan/macvtap interface, it will transfer any traffic from it to external network, but not the reverse side. Because it is catching traffic only for self mac-address.`
`You should use macvlan/macvtap interfaces only if it endpoint.`

**Comment by maiqueb** [comment]
I think that you might be interested in PR #2935 , which adds a macvtap binding mechanism, that will plug the char device part of macvtap into the VM, effectively achieving what you're after.
