### ISSUE TITLE
persistentVolumeClaim Disk supports qcow2 format

### ISSUE THREAD

**Issue by biliwewe** [kubevirt/kubevirt#2947]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What you expected to happen**:

Currently the disk is also required to be in raw format, I want to reduce the disk image size,What should i do, ask for help.

Thanks in advance.

**Comment by biliwewe** [comment]
If it is a Windows vm, the win.img disk file is too large, Can someone give me some advice?

**Comment by rmohr** [comment]
@awels @mhenriks maybe you have some ideas? I find it in general more and more appealing to also support qcow2. We have the security checks already in place for other volume types which support qcow2.

**Comment by awels** [comment]
AFAIK the main reason we picked just raw is simplicity. Using one raw disk per PVC allows us to use k8s build in storage mechanisms like snapshotting instead of having to invent our own.

There is no reason you cannot have a sparse raw disk, so I am a little confused about the benefits of qcow2 with regards to disk space. We currently default to non sparse disks because most storage providers will give you a PVC of exactly the requested size and filling it completely when creating the disk makes sense. The notable exception is if you are using local storage (hostpath, local volume) type storage where everything is shared. It should be feasible to specify that you want sparse disks though.

@aglitke any other reasons for not supporting qcow2 disks?

**Comment by anencore94** [comment]
@awels 
I think when using thin-provisioning-block-device or cephfs pvc, the storage provider does not give all the requested size at once. But the backend storage will fill more and more until the requeseted size as using vm.
Thus qcow2 image may save more backend storage resources.
