### ISSUE TITLE
Acquire / generate and deploy x509 certs for libvirtd and QEMU

### ISSUE THREAD

**Issue by berrange** [kubevirt/kubevirt#298]
To secure the host side network services (serial port, spice, vnc, migration, nbd, etc) QEMU needs to be given x509 certificates, to allow TLS to be enabled. 

When deploying libvirtd on the compute node, this involves either acquiring or generating a set of certificates specifically for that host. Then /etc/libvirt/qemu.conf needs some modification to enable use of TLS for the various services.

Similarly to allow secure remote access to between libvirtd daemons during migration, libvirtd itself needs to be configured with TLS certificates when deployed onto a compute node. The --listen flag should be given to libvirtd to turn on its TLS network listener socket.

Ideally there would be some standardized service for requesting TLS certificates in k8s.

Rather than waiting for this, however, we should initially just generate a self-signed certificate authority and have the entrypoint.sh for the libvirtd POD auto-create the needed certificates. This is of course insecure, but it at least lets us enable TLS everywhere, so that our codebase can rely on everything being TLS secured. We can drop in a better way to acquiring/generating the certs at an arbitrary later time.

This illustrates how to do this for libvirtd (similar steps for QEMU are needed):

Generating the CA cert & putting it in  a k8s secret:

http://libvirt.org/git/?p=libvirt-kube.git;a=blob;f=manifests/libvirt/makesecret.sh;h=fc518fe03f075cc432af36070255fbce9954aa89;hb=HEAD

Generating the per-host certs:

http://libvirt.org/git/?p=libvirt-kube.git;a=blob;f=images/virtd/entrypoint.sh;h=b14319e38bad248f87b05792999a71cdad94f6ed;hb=HEAD

**Comment by fabiand** [comment]
I actually wonder if the securing of the communication channels could be delegated to i.e. <http://istio.io> or <http://linkerd.io>.

But I don't have the full picture yet.

The benefit of using a service mesh like this would be - if it provides the functionality we need - that we can monitor data flows between components using these mesh components.

**Comment by berrange** [comment]
Delegating security puts that 3rd party service in the position of trust which is a real downside IMHO. Attack that one 3rd party and you compromise everything. Encryption needs to be fully end-to-end so should be done from QEMU & libvirt right from the start so there's never any clear text from the moment traffic is sent by the app in question

**Comment by rmohr** [comment]
+1 for enabling TLS everywhere in our code asap.

I think Kubernetes has already everything in place we need, to let it act as an authority. See https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/.

So our pod would create a custom certificate, based on the example in the doc, or like in the link provided by @berrange. Then the pod would send the sign request to the apiserver. An automated process can sign the certificate, and the pod can download it. Finally we start our service.

We can also watch for pod stops, and revoke the certificates.

Since 1.6+ it is even possible to assign unique tokens per pod, which belong to the same service account: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/. That brings us almost to where we need to be at the end. Because, we have to make sure, that once we have revoked a certificate of a pod, which we don't trust anymore, that we have also revoked the account token, so that the pod does not just try to get a new certificate signed. However, I don't think that we can assign unique tokens in combination with a DaemonSet ...

**Comment by berrange** [comment]
The k8s doc looks promising, but I'm not sure it supports everything we need. In particular we need *different* certificates for libvirtd and QEMU despite them being in the same POD (and thus having the same IP addr / DNS name). This involves getting sub-CAs and using one sub-CA to issue certs for each libvirtd, and one sub-CA to issue certs for each QEMU.

Note it also says the CSR needs manual approval in k8s right now and that if you want automation you have to write something to automate it yourself, so that'd be another task to deal with.

**Comment by rmohr** [comment]
Regarding the sub-CAs, yes I don't think that would work right now. There is only the one master CA.

> Note it also says the CSR needs manual approval in k8s right now and that if you want automation you have to write something to automate it yourself, so that'd be another task to deal with.

Looks like there exists an alpha auto-approver for specific groups in the [kube-controller-manager](https://kubernetes.io/docs/admin/kube-controller-manager/). It is also mentioned here: https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/#approval-controller.

**Comment by rmohr** [comment]
So we currently have four components which would need certificates: libvirtd, qemu, virt-api and virt-handler.

/cc @admiyo FYI.

**Comment by fabiand** [comment]
Yes, you have a point @berrange  8with starting with own components).

But if we look at KubeVirt as a distributed service, then a mesh service can be seen as an internal implementation detail - like reusing a library in classic development.

**Comment by rmohr** [comment]
@fabiand as far as I have seen, they are smart and flexible proxies, decoupling your application requirements from infrastructure. They don't secure anything per definition. You would still have to create and supply the configs. So even, for whatever reason, we would want to adopt such a framework, it is in my eyes not really realted to this ticket. Further, since we are a k8s addon, I don't see any reason, why we would want a flexible application layer, to abstract away the k8s infra.

**Comment by berrange** [comment]
I don't think the library analogy is a good fit because you have very different trust relationships between a library loaded into your local process, vs a networked mesh. It is more akin to saying that in a bare metal world we should just assume the network admin has configured IPSec to secure the communications. They may have done, but that doesn't mean you should trust them to have done that. It is stil sensible to run TLS to get true end-to-end encryption, removing the assumption that your network administrator is trustworthy.

**Comment by fabiand** [comment]
@rmohr I did not check istio, but I was referring to https://linkerd.io/features/tls/

But yes, I don't ponder on this point anymore :)

**Comment by rmohr** [comment]
With #663 not relevant anymore.
