### ISSUE TITLE
Suggestion - support make cluster-sync CI prow lanes

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3078]
/kind enhancement

We are vendoring cluster-up folder of kubevirtci, in order to run cluster-up and cluster-sync make targets.

cluster-up has prow lanes that test it as part of kubevirtci.
but when adding code to kubevirtci it might cause make cluster-sync to break on some lanes,
causing us to not able to bump-kubevirtci gracefully without breaking cluster-sync on some lanes which is mandatory for development routine and tests.

should we create lanes on kubevirtci which will allow us to vendor kubevirt and then bump kubevirtci there and apply the suggested PR and test make cluster-sync ?
or any way we should address this ?

atm the real situation is that if we bump kubevirtci, 
sriov will break its make cluster-sync
k8s-1.17.0 which has broken sync will work again
ocp-4.3 which has broken sync will stay broken

thanks

**Comment by rmohr** [comment]
> atm the real situation is that if we bump kubevirtci,
> sriov will break its make cluster-sync
> k8s-1.17.0 which has broken sync will work again
> ocp-4.3 which has broken sync will stay broken

Normally we build the cluster and always tested them against kubevirt/kubevirt before merging. Yes that should be more automated, but I don't know why people stopped testing their changes.

**Comment by rmohr** [comment]
> sriov will break its make cluster-sync

That should not have happened and is really bad.

> k8s-1.17.0 which has broken sync will work again

That one is still wip and did never work so far. That is why we never enabled reporting for it.

> ocp-4.3 which has broken sync will stay broken

OCP lanes also don't run on kubevirt/kubevirt because even if you tested them properly during provisioning they stop working sooner or later and we didn't get past that.

**Comment by dhiller** [comment]
First of all: this should be a kubevirtci issue, not a kubevirt issue.

Regarding k8s-1.17 my understanding was that we agreed on collecting data from the k8s-1.17 lane in order to fix the provider?

That the sr-iov lane is broken is really bad, agreed. And this is blocking us, that's true. But now that the situation is like it is we either have the option of reverting the changes on SR-IOV provider or work on fixing the sr-iov provider (which is already in the works and nearing completion AFAIU). I'd vote for the latter.

Regarding ocp/okd: There's ongoing work moving testing of okd/ocp towards openshift-ci. I know, this is taking very long now, but I'm confident it will be completed sooner or later and then we may not need the okd/ocp providers any more.

**Comment by oshoval** [comment]
ok thanks, 
Roman if you want we can continue the conversion that was paused on the google chat, or to close this issue if you guys prefer

just thought about a simple (maybe even script that will be run manually)
that people will be able to test their new kubevirtci  code doesnt break cluster-sync on kubevirt
(for the status once we fix the syncs)

thanks

**Comment by oshoval** [comment]
@dhiller 
"Regarding k8s-1.17 my understanding was that we agreed on collecting data from the k8s-1.17 lane in order to fix the provider?"

make cluster-sync works after bumping (not merged yet because it blocked on the effort that is ongoing with the sriov as you said), and i am not totally in the loop beside, sorry
