### ISSUE TITLE
Add kubevirt_vmi_memory_total_bytes metric

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#3081]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

**What you expected to happen**:
virt-handler expose `kubevirt_vmi_memory_total_bytes `metric
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
@wavezhang any chance that you can provide a patch?

**Comment by ArthurSens** [comment]
Hello @wavezhang! I was tackling this issue and I was wondering if Kubernetes pod metrics could be enough for this...

Could you share a use-case for this particular metric?

**Comment by wavezhang** [comment]
@ArthurSens You mean pod memory request or pod memory limit or real-time pod memory usage? None of them are accurate

**Comment by ArthurSens** [comment]
Yes, I was thinking about something like [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) or [metrics-server](https://github.com/kubernetes-sigs/metrics-server).

They are not accurate indeed, but usually, they are enough for alerting or giving a good idea about memory usage. Is there a particular reason for having an accurate metric about total memory available for a VMI?

**Comment by ArthurSens** [comment]
hi @wavezhang 

Keep track of memory usage percentage to know if the VMIs deployed are being over-dimensioned or under dimensioned for a particular use case

* `kubevirt_vmi_memory_available_bytes` - Would be available memory for the VMI, coming from [DOMAIN_MEMORY_STAT_AVAILABLE](https://github.com/kubevirt/kubevirt/blob/3f59446934da55e3e17e3e8f1ee659ee794ce966/vendor/github.com/libvirt/libvirt-go/domain.go#L374)
* `kubevirt_vmi_memory_unused_bytes` - would be unused memory by the VMI, coming from [DOMAIN_MEMORY_STAT_UNUSED](https://github.com/kubevirt/kubevirt/blob/3f59446934da55e3e17e3e8f1ee659ee794ce966/vendor/github.com/libvirt/libvirt-go/domain.go#L373)

Examples of usage for these metrics:
* `(100 * kubevirt_vmi_memory_unused_bytes) / kubevirt_vmi_memory_available_bytes`
  * Will give how much memory(percentage) is not being used in comparison with the total memory available for each VMI

Was that what you had in mind? But again, I think that both metrics can be substituted by Pod memory metrics... if you could point a use-case where the pod memory metrics are not enough, that would help a lot

I think it's doable after #3568 gets merged since memBallooing might be required for this.
