### ISSUE TITLE
Add more workload and infrastructure metrics

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#3385]
/kind enhancement

**What happened**:
We should expose more workload and infrastructure metric in order to detect infrastructure problems earlier.

**What you expected to happen**:
Ability to detect infrastructure issues issues

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

* Implement a metric for virtual machine instance migration convergence time - A Migration metric, to track how long it takes for a virtual machine instance to migarte.
* Implement metric to expose VMI phases
* Implement a metric for number of virtual machine failures - 
* Implement virtual machine instance age metric - A VMI metric, providing a number (seconds?) reflecting the runtime/age of the VMI

**Comment by Biswajitghosh98** [comment]
Hello ! I would like to take up this issue. Please provide me some pointers on where and how to start 😊

**Comment by animeshk08** [comment]
Hi @danielBelenky @fabiand
I am Animesh Kumar a junior year student at NITK, Surathkal, India. 
Thank you so much for providing this project idea. I would be interested in working on this as a part of Community Bridge.

Since the tool is new to me I am currently exploring the demo. Please help me in getting started with this idea. Also, if possible point me to some suitable issues which can help me in understanding the work and the code-base.

Let me know if you prefer some other medium of communication(`e.g slack, irc, mail`) with respect to this discussion.

**Comment by Dhiraj240** [comment]
@xprxprx   I have applied on community bridge and messaged you on slack for more information. You can check my portfolio here at https://dhiraj240.github.io/
