### ISSUE TITLE
Why replica is 2 for all kubevirt deployments

### ISSUE THREAD

**Issue by gyliu513** [kubevirt/kubevirt#3445]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

After kubevirt was deployed, I found all of the deployment replicas are set as 2.

```console
root@gyliu-dev1:~/kind-res# kubectl get pods -n kubevirt
NAME                               READY   STATUS    RESTARTS   AGE
virt-api-d987bf766-b2nbw           1/1     Running   0          3h48m
virt-api-d987bf766-xjk28           1/1     Running   0          3h48m
virt-controller-58654dfd97-6flg7   1/1     Running   0          3h47m
virt-controller-58654dfd97-k6d75   1/1     Running   0          3h47m
virt-handler-4dpzt                 1/1     Running   0          3h47m
virt-handler-dntsn                 1/1     Running   0          3h47m
virt-operator-7689fc6db4-7jvp8     1/1     Running   0          3h49m
virt-operator-7689fc6db4-q8zl4     1/1     Running   0          3h49m
```

What is the benefit of this? But it do bring some trouble to me, when I want to check log, I do not know which pod I should check.

Here setting replica as 2 https://github.com/kubevirt/kubevirt/blob/release-0.29/pkg/virt-operator/creation/components/deployments.go#L177

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@gyliu513 the advantage is, that if one node goes down, that you will experience pretty much no downtime. It is in general tricky to find the right values for everyone here, but just consider scenarios where you have a small or bigger outage on the network. This can lead easily to situations where you loose one of our control pods, but starting on another node does not work since you may not be able to pull images.

Having said that, there exists #3365, which is tracking the need to customize our deployment. It is definitely valid to tailor our deployments to your cluster need.

**Comment by gyliu513** [comment]
Thanks @rmohr , good to see going to support customize the deployment.
