### ISSUE TITLE
Kubevirt does not work on microk8s

### ISSUE THREAD

**Issue by viorelcanja** [kubevirt/kubevirt#3495]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I followed the tutorial to start a simple VM on kubevirt on microk8s. The VM is scheduled but immediately transitions in the Failed state.

**What you expected to happen**:
I expected the VM to transition to Running.

**How to reproduce it (as minimally and precisely as possible)**:
Install microk8s , install kubevirt, deploy a simple vm.

**Anything else we need to know?**:
Kubevirt expects to find the launcher-sock socket in /var/lib/kubelet/[rest of path] but in this setup the socket is going to be created in /var/snap/microk8s/common/var/lib/kubelet/[rest of path]. I created a symlink /var/lib/kubelet -> /var/snap/microk8s/common/var/lib/kubelet/ to validate this and the VM starts as expected.

**Environment**:
- KubeVirt version (use `virtctl version`):
v0.29.0
- Kubernetes version (use `kubectl version`):
v1.18.2-41+b5cdb79a4060a3
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rajha-korithrien** [comment]
I have an identical problem when deploying against a Kubernetes cluster that was built via the RKE project. My cluster deployment specifies `--root-dir` for kubelet of `/opt/rke/var/lib/kubelet` which then causes the `launcher-sock` socket to be missed because the `pods` directory is not where kubevirt expects.

There is a similar problem with k3s #2676 

It might be nice if kubevirt could detect the `--root-dir` in use by kubelet, or allow it to be configured?

**Comment by condaatje** [comment]
Hoping to re-open this issue - kubevirt does not work with the default workflow on microk8s still

**Comment by condaatje** [comment]
this didn't fix the issue:

`ln -s /var/lib/kubelet/ /var/snap/microk8s/common/var/lib/kubelet/`
