### ISSUE TITLE
virt-controller can modify KubeVirt CRs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#3512]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

virft-controller has all rights on all kubevirt.io resources. This means that if someone gets access to the virt-controller service account, that person can delete KubeVirt or "upgrade" unobserved to a flawed kubevirt version.

**What you expected to happen**:

Let's move the KubeVirt CR into its own resource group. Something like `operator.kubevirt.io` or explicitly mention all resources which virt-controller should be able to modify.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
> Let's move the KubeVirt CR into its own resource group. Something like operator.kubevirt.io or explicitly mention all resources which virt-controller should be able to modify.

unfortunately, moving the KubeVirt CR to another operator group at this point is a fairly complex endeavor.

The simplest approach is to pick exactly what kubevirt.io APIs virt-controller is allowed to access. This is what we're doing for all our other components such as virt-api and virt-handler, so it's a consistent pattern we already use.


The change involves updating the virt-controller rbac in the ```pkg/virt-operator/creation/rbac/controller.go``` file. There's an entry that looks like this the following 

```
                        {
                                APIGroups: []string{
                                        "kubevirt.io",
                                },
                                Resources: []string{
                                        "*",
                                },
                                Verbs: []string{
                                        "*",
                                },
                        },

```

That needs to be replaced with an entry that targets exactly the api's virt-controller needs access to. ```pkg/virt-operator/creation/rbac/apiserver.go``` has examples of how targeted access to kubevirt.io should look.

**Comment by yuhaohaoyu** [comment]
Hello, I think I have an initial fix to this problem following David's suggestion. I need permission to push code. 

Currently, the rule for the API group `kubevirt.io` in the definition of the `ClusterRole kubevirt-controller` in `pkg/virt-operator/creation/rbac/controller.go` is
|Resource API   | API Group             | Verbs |
| ----          | ---                   | ---   |
|*              | kubevirt.io           | * |

I changed the the rule specification code to specify 3 rules for specific custom resources, as below:
|Resource API   | API Group             | Verbs |
| ----          | ---                   | ---   |
|vm, vmi             | kubevirt.io           | get, list, watch, patch       |
|vmireplicaset            | kubevirt.io           | get, list, watch, patch       |
|vmim           | kubevirt.io           | create, get, list, watch, patch       |
|vmpreset       | kubevirt.io           | list, watch   |
|kubevirt       | kubevirt.io           | get, list, watch      |

I added a block to tests/access_test.go essentially runs the command
`kubectl delete vm --as system:serviceaccount:kubevirt:kubevirt-controller` 
for the 8 verbs against the 6 target service objects. 


I did not deal with other API groups with `kubevirt.io` extension, their rules are defined right now as:
|Resource API   | API Group             | Verbs |
| ----          | ---                   | ---   |
|*              | snapshot.kubevirt.io  | * |
|*              | cdi.kubevirt.io       | * |

**Comment by yuhaohaoyu** [comment]
Correction: 
`kubectl delete vm --as system:serviceaccount:kubevirt:kubevirt-controller`
-->
`kubectl auth can-i delete` vm --as system:serviceaccount:kubevirt:kubevirt-controller`

**Comment by yuhaohaoyu** [comment]
The open PR #4298 (with aim to improve this issue) just managed to pass all the functional test. 

As a summary, the effort to refactor the RBAC rule of the `kubevirt-controller` ClusterRole with regard to the access of the resources in the `kubevirt\.io` API group did not find a more restrictive substitute. Not aware of the development history, the CI tests and life-cycles of VM, VMI appear to be heavily dependent on the existing rule (`*` for `resources` and `*` for `verbs`) setting. 

Through the functional testing process (CI) in the scope of this PR, I learnt a few loose relationship of the specification of the rule(s) and some functional tests. They are explained as below:

Before the PR, all CI tests pass: 
| Rules tmp-name | API Group | Subject | Verbs |
| ---- | ---         | ---                   | ---   |
| *orig* | kubevirt.io             | *           | *  |

Refactoring that allow `cluster-deploy` script to bring up the `kv`, but fails 22 functional tests in the 3 `e2e` CI tests. The failed tests were in `vm_test`, `vm_watch_test`, `subresource_api_test`, `expose_test`, `pausing_test`. 
| Rules tmp-name | API Group | Subject | Verbs |
| ---- | ---         | ---                   | ---   |
| *rule1-A* | kubevirt.io             | *           |  get, list, watch, patch, update, create  |
| *rule1-B* | kubevirt.io             | kv, vm, vmi, vmirs, vmipreset, vmim     |  get, list, watch, patch, update, create, delete  |

Note there are not many room for tweaking the specification between the *orig* rule and *rule1* rule. To log the tweaking briefly, we used these loosely defined terms, 
| Term | Stands for|
|---|---|
| *6-verbs* | a specification of verbs that including `get, watch, list, patch, update, create` |
| *7-verbs* | a specification of verbs that including `get, watch, list, patch, update, create, delete` |
| *8-verbs* | a specification of verbs that including `get, watch, list, patch, update, create, deletecollection` |
| *6-subjects* | a specification of rule subjects that including `kv, vm, vmi, vmirs, vmipreset, vmim` |

With these terms the rule tweaking is logged as below
| Id | rule1-A subj. | rule1-A verb | rule1-B subs. | rule1-B verb | Failed tests |
|---|---|---|---|---|---|
| 1 | * | 6-verb | 6-subj | 7-verb | 22 fails (vm_test, etc.) |
| 2 | * | 7-verb | 6-subj | 7-verb | 2 fails (id: 3145, 4642) |
| 3 | * | 8-verb | 6-subj | 8-verb | 2 fails |
| 4 | * | 8-verb | 6-subj | * | 2 fails |
| 5 | * | * | 6-subj | 7-verb | 0 fail |

The main conclusion from this table is that in order to keep the current CI tests, the rule has to use `*` for both the `resources` and `verbs` fields in the code.

The secondary findings (not explained) are:  
1. In term of specification of the verbs in a RBAC rule, "*" covers more than the 8 verbs {"get", "list", "watch", "patch", "update", "create", "delete", "deleteconnection"}. Is there any other verb we have declared? 
2. In term of specification of resource subjects in the RBAC rule in the kubevirt.io API group, "*" appears to be a superset of {vm, vmi, vmrs, vmpreset, vmim, kv}.

Following the minimalism practice, there is no reason to merge this PR. The code changes are:
- `pkg/virt-operator/creationg/rbac/controller.go` : to leave trace of this attempt. 
- `pkg/virt-operator/creationg/rbac/operator.go` : cleanup, no functionality change. 
- `tests/acctest_test.go` , `tests/acctest.go`: a fast test targeted the rule in discussion.
