### ISSUE TITLE
[flakey CI] failing to bring up IPv6 lane cluster

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3569]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

IPv6 kind lane often fails during deployment.

Example failed run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3543/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1272424717042585600

Log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3543/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1272424717042585600/build-log.txt?Expires=1592227713&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=UncucjlFaIewoR4U4xkAOIL3wr3kVY2Ozjn5mDluu8ZuRSpv7HrC50QsAtmq1RL36FupmKQaTnycqzNlWZooJ05EjYXL5AnOPmCQzLRLSj2BYUWckKAl6vIVG%2Bx%2BAYv%2FO17fJktHlKMIi33u%2FCk2kC9c%2BjE06uw9f%2BdYIABbq2kQi5BD3UXsh45caAZMM8hdI%2FESm6ae6cq7QR8sDpajQtVL7ySokwzQMzuIY6qMNrZsNmXEhBF3nY6m5LbR9c78ZgMvs4dUxWvJODkpsAAtwU79tFEDps2Fat%2BVQpfqQx6FlI9glNlf9aLf0xgLV7csB9NvQ3qH3B%2BHD%2Fw7HlYMMA%3D%3D

**Comment by oshoval** [comment]
Hi, I would suggest please that we clean the loopback devices in cluster up/down as we discussed,
in case finding the root problem would take more time, since this ipv6 lane is mandatory and PRs are stalled badly with this problem. (and then continue of course to find the root problem)
Thanks

**Comment by maiqueb** [comment]
> Hi, I would suggest please that we clean the loopback devices in cluster up/down as we discussed,
> in case finding the root problem would take more time, since this ipv6 lane is mandatory and PRs are stalled badly with this problem. (and then continue of course to find the root problem)
> Thanks

Please allow me to really understand what's happening here. 

By now, I know that the `losetop` call in the [disks-images-provider code](https://github.com/kubevirt/kubevirt/blob/master/images/disks-images-provider/entrypoint.sh#L30) is referring to the hosts where the nodes are deployed, and not to the k8s node. This means it will return (and configure) a loop device on the host where the k8s nodes are deployed. It has worked so far because we had 100 loopbacks [pre-provisioned](https://github.com/kubevirt/kubevirt/blob/master/manifests/testing/disks-images-provider.yaml.in#L123) in the k8s node, and as such, their names matched.

Now that this has executed past 100 times, we see that we're creating `/dev/loop101`, which doesn't exist on the k8s node. Hence, the following error shows up in the disks-images-provider container logs:
```
converting cirros image from qcow2 to raw, and copying it to local-storage directory, and creating a loopback device from it
losetup: /local-storage/cirros.img.raw: failed to set up loop device: No such file or directory
```

I'm suspecting the `losetup -f ` call is somehow not namespaced (looking for an available configured loopback directly using the root namespace), while the configuration side of losetup is.
