### ISSUE TITLE
Improve container build times

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#392]
Currently the containers are built unconditionally and sequentially. This can easily be improved to be conditionally and parallel to save us some time.

**Comment by rmohr** [comment]
We can also use --cache-from from newer docker versions. That allows us to simply download the latest released kubevirt containers and use them as build-cache.

**Comment by ifireball** [comment]
@rmohr , @fabiand why do we first build go binaries and then warp them in containers? why not just build containers?

Also, not that docker is essentially a build dependency, can we build all the containers locally instead of in vagrant?

**Comment by fabiand** [comment]
@ifireball I'm not sure you understand, but you do need a binary to run it inside a container.

**Comment by ifireball** [comment]
@fabiand yeah, but you can build the binary as part of the container build process.

**Comment by fabiand** [comment]
First - I'd close this isues, as it's to broad and unspecific.

To me it look slike an unusual thing to do the binary build during the container build.

**Comment by fabiand** [comment]
Closing this issue, but we can cotninue the build discussion ;)

**Comment by rmohr** [comment]
@ifireball yes building them locally and having an extra container repo where we push the builds to makes sense. For single-node setups it might be more complicated than what we do right now, but for CI or multi-node setups it makes sense. I think we even have somewhere an issue regarding to introducing a local container registry for that purpose.

**Comment by ifireball** [comment]
@fabiand building the binary during the container build process seems to be a common thing. this is what both s2i and Docker multi-stage build seem to aim at.

@rmohr yeah, in CI I can even make that a shared registry, and then I suddenly get multi-host caching... but I'll need a way to know that a certain container image was built from the same sources as another image (Tagging by git sha will not work because the CI runs with a different sha each time)

How reproducible are Go builds? is running the same compiler on the same sources in different times produce the same binary? If not it will be hard to ge any benefits out of layer or image caching.
