### ISSUE TITLE
Support for additional architectures

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#395]
We might want to build KubeVirt for [arm64 and ppc64le (as requested)](https://github.com/kubevirt/kubevirt/pull/384#issuecomment-325285624) as well.

- [ ] Multi arch support for binaries
- [ ] Reflect arch in containers
- [ ] minikube on desired arch
- [ ] vagrant and tests on desired arch

**Comment by mpolednik** [comment]
How does arm64 make sense when KVM barely works there? How is kubernetes doing on those architectures? We should not do the mistake of building for architectures that don't really work (where working means running docker, KVM, kubernetes). I'm not sure about vagrant *right now* either, because it's gonna be slow (emulated) and ppc64le doesn't have nested virtualization. Not sure about arm in this regard.

**Comment by fabiand** [comment]
This ticket is intentionally named to support additional architectures, without naming them.
It's to keep in mind that we should consider this in our tools, build systems, and ci.

I'd also put it up to discussion what arches we need to support - and who implements this support - but so far arm64 and ppc64le were explicitly requested (see the added link).

**Comment by fabiand** [comment]
To stretched atm, closing this.
