### ISSUE TITLE
VirtualMachine VM rename VM update should succeed

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#3974]
/kind bug
/triage build-officer

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3883/pull-kubevirt-e2e-k8s-1.18/1292970397448278016

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@enp0s3 we found a bug here. Have a look at https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3883/pull-kubevirt-e2e-k8s-1.18/1292970397448278016/artifacts/k8s-reporter/pods/1_kubevirt_virt-controller-5666d5dfbd-sgjgp-virt-controller.log:

The relevant error:

```
{"component":"virt-controller","kind":"","level":"error","msg":"Updating api version annotations failed","name":"testvminp9h9zdxtjnbnsdgmg9x6995vrx88dm9vwptqdjg2j7bd5zt","namespace":"kubevirt-test-default","pos":"vm.go:172","reason":"admission webhook \"virtualmachine-validator.kubevirt.io\" denied the request: Modifying a VM during a rename process is not allowed","service":"http","timestamp":"2020-08-11T02:16:52.647958Z","uid":"85296cc1-5c44-4475-a362-4f7ef85d0b86"}
```

I think the issue is that it can happen that a rename request is actually happening before the VM-controller itself did an initial reconcile on the VM. The VM-controller itself should not be blocked when it tries to modify the metadata or the status.

**Comment by enp0s3** [comment]
PR #4102 should fix this issue
