### ISSUE TITLE
pull-kubevirt-generate lane doesnt detect changes in directory due to the generate

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4041]
/kind bug

**What happened**:
pull-kubevirt-generate should detect if directory isnt clean
after running `make generate` 
locally running the `make generate-verify` target
it does find that we have a problem, because there was a direct update of cluster-up folder
which is venored

so there are two problems here
1. make it detect the changes again
2. move the change that it detect to kubevirtci and do a bump as we always do

**Comment by danielBelenky** [comment]
I think that the problem is that `make` actually executes each target in a separate subshell and the environment in which `check-git-tree-state` is being executed doesn't get the updates from `generate`. Maybe there's a way around this using some Makefile magic but I don't think that we should invest too much time in it at this point.

I've sent a PR to work around this in the job: https://github.com/kubevirt/project-infra/pull/598/files
I think that we can remove the dedicated `generate-verify` make target and just use separate targets.

**Comment by oshoval** [comment]
ok, or to please consider the refactor i created once of travis, where all snippets are in the same file, and you can run one / list / all of them with arguments to the script https://github.com/kubevirt/kubevirt/pull/3524

**Comment by oshoval** [comment]
Fixed by 
https://github.com/kubevirt/kubevirt/pull/4066
