### ISSUE TITLE
Support CNI IPAM DNS config

### ISSUE THREAD

**Issue by rootfs** [kubevirt/kubevirt#4267]
/kind enhancement

**What happened**:
CNI IPAM DNS strings not passed to the VM
**What you expected to happen**:
Currently the VM DNS config comes from launch pod as seen [here](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/virtwrap/network/common.go#L337). This prevents an IPAM DNS config passthrough when a VM solely uses Multus network.

Please use IPAM DNS config when the VM only uses Multus network

@phoracek 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ravidbro** [comment]
@rootfs in case that you are using whereabouts or static CNIs, there is an option there to configure also DNS servers

**Comment by rootfs** [comment]
@ravidbro yes, i added DNS nameservers in whereabouts, but it is not picked up by the launcher Pod.

**Comment by ravidbro** [comment]
Then maybe the direction should be a bug there.

**Comment by rootfs** [comment]
@ravidbro see [this](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/virtwrap/network/common.go#L337)

**Comment by rmohr** [comment]
/assign @phoracek 
Maybe you can have a look?

**Comment by CL0Pinette** [comment]
Hello,

I see this issue has been closed but the underlying issue is still there.
Is there any workaround for it ? If not what would be the best implementation to add this.

From what I read in the code, we could get if a networkInterface is a multus one or not right before starting the dhcp server by looking at the `l.vmiSpecNetwork` https://github.com/kubevirt/kubevirt/blob/174e2b197b038b8d73f526c216db97bf6eab04fe/pkg/network/setup/podnic.go#L105
However I don't see how we could get the dns field from the multus annotation. If you have any idea, I would gladly implement it.
