### ISSUE TITLE
Terminating virt-launcher pod does not update VMI status

### ISSUE THREAD

**Issue by salanki** [kubevirt/kubevirt#4502]
/kind bug

**What happened**:
When a virt-launcher Pod enters Terminating state, ie. due to the underlying host having crashed the VMI still reports a status of Running.

**What you expected to happen**:
The VMI status should also reflect that the VMI is terminating.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a VMI
- Kill the kubelet and docker on the host, or shut off power to the host if on-prem

**Anything else we need to know?**:
This is easily fixed by checking for `metadata.deletionTimestamp` on the Pod. If one is set, update the VMI status to Terminating.

**Environment**:
- KubeVirt version (use `virtctl version`): master as of 2020-11-01
- Kubernetes version (use `kubectl version`): 1.18

**Comment by rmohr** [comment]
Can you check the ready condition of the VMI in this case? You should see that the readiness condition was flipped to `False` and the reason should be `PodTerminating`. This should happen as soon as the k8s control plane tries to delete the unresponsive pods.

We explicitly don't update the VMI status to `Terminating`.  This does also not happen on such Pods. If you look at the pod spec you will see that they are also still in Running phase. This does not happen because we want to preserve the last known state.

**Comment by rmohr** [comment]
https://github.com/kubevirt/kubevirt/pull/4398 implemented that. Your master state should already have that.

**Comment by salanki** [comment]
Ok. I guess that is not shown in “kubectl get vmi”. It would be useful to have it there as a one stop shop for checking that VMIs are up.

**Comment by rmohr** [comment]
> Ok. I guess that is not shown in “kubectl get vmi”. It would be useful to have it there as a one stop shop for checking that VMIs are up.

It indeed would be. I think we may want to introduce a special `serverside` printing subsection in the VMI status. Sadly for CRDs we don't have the same independent serverside printing flexibility like built-in APIs have.
