### ISSUE TITLE
virt-api depends on spice proxy ip in manifest

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#457]
The virt-api requires the spice proxy ip in it's manifest. This can be an issue, because this ip might not be available at deployment time.

There should be a different way to provide/retrieve the needed informations.

**Comment by cynepco3hahue** [comment]
@fabiand I think we can try to fetch node IP where spice-proxy runs and use this information, does it good enough?
Also, interesting if can we make spice work without proxy? Because if to take the analogy to Ovirt, spice proxy specified only if needed by a user on VM level.

**Comment by fabiand** [comment]
Yes, we can do a lookup of the spice proxy (using an FQDN i.e.).

Enabling direct spice access is also possible, but a large new topic :)

**Comment by rmohr** [comment]
Hi there,

> Yes, we can do a lookup of the spice proxy (using an FQDN i.e.).

Just make sure that you don't intend to use kube-dn to provide anyting DNS related, since kube-dns runs inside the cluster. We only need the proxy when one wants to connect from outside the cluster to our VMs.

> Enabling direct spice access is also possible, but a large new topic :)

If you are inside the cluster network (pod or nods), you can use the proxy, or just ignore it. In both ways you can connect to the VMs without any issues. Also right now, in both scenarios the endpoints are not yet secured.

> The virt-api requires the spice proxy ip in it's manifest. This can be an issue, because this ip might not be available at deployment time.

To solve this, we can either use a ConfigMap, which allows dynamic update, or one can restart virt-api with the right IP involved. Both would work, the ConfigMap would be the long-term solution. Note that e.g. looking up external IPs on a service wouldn't ultimately help us either, since the external service IP is not necessarily the IP which allows users to reach the service.

**Comment by rmohr** [comment]
Also: Maybe, in the not so near future, we might want to allow people to specify their own proxy IP per namespace? What do you guys think?

**Comment by johnlevon** [comment]
@rmohr re ConfigMap, are you suggesting that during deployment we build a ConfigMap with the value being the IP of the spice proxy, and modify virt-api such that it picks up this data via a mounted volume?

When you say "dynamic update", who do you expect to be doing the updates? As part of spice-proxy (re)deployment?

In terms of refreshing the virt-api process, do you see something like configmap-reload as the right option, or something else?

**Comment by fabiand** [comment]
> > The virt-api requires the spice proxy ip in it's manifest. This can be an issue, because this ip might not be available at deployment time.
> 
> To solve this, we can either use a ConfigMap, which allows dynamic update, or one can restart virt-api with the right IP involved. Both would work, the ConfigMap would be the long-term solution. Note that e.g. looking up external IPs on a service wouldn't ultimately help us either, since the external service IP is not necessarily the IP which allows users to reach the service.

**Comment by rmohr** [comment]
> @rmohr re ConfigMap, are you suggesting that during deployment we build a ConfigMap with the value being the IP of the spice proxy

For our default manifests in kubevirt/kubevirt yes. If it is present, use the value, if not, then provide connection details without the proxy IP.

> , and modify virt-api such that it picks up this data via a mounted volume?

Either that and watch the directory (since kubelet does periodic synces), or directly asking the API (maybe a watch?), since we are a k8s native app.

> When you say "dynamic update", who do you expect to be doing the updates? As part of spice-proxy (re)deployment?

Whenever we see a ConfigMap update, update the config value in virt-api. I don't think that this is related to spice-proxy redeployments. An admin might want to change the IP, when she changes the network infrastructure.

> In terms of refreshing the virt-api process, do you see something like configmap-reload as the right option, or something else?

We can have an app-config object, which allows multi-reader/single-writer access (to make sure that we sync between go routines). When we then observe a change on the config map via one of the ways above, we can update our app-config.

I hope that shows a few possible ways. I think the dynamic reload mechanism is not that important just for the proxy config, but in general a pattern which will help us with propagating cluster config changes.

**Comment by rmohr** [comment]
Spice proxy is removed for now.
