### ISSUE TITLE
VM stuck Scheduled on btrfs: failed to detect root mount info of containerDisk

### ISSUE THREAD

**Issue by dren-dk** [kubevirt/kubevirt#4590]
/kind bug

**What happened**:

Exactly as reported in #3119, but now running kubevirt v0.35.0.

The virt-launcher pod has status Running, but the VMI remains in phase Scheduled after a while the pod fails.

The output of the mount command from the compute container is:

```
[root@win10 /]# mount
/dev/sda1 on / type btrfs (rw,relatime,space_cache,subvolid=197697,subvol=/@/var/lib/docker/btrfs/subvolumes/e99b5d626799682bdce13703924b5db691e8c778c4472fcc1a4b7405180963d1)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
/dev/sda1 on /dev/termination-log type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/containers/compute/cce11bdf)
/dev/sda1 on /etc/resolv.conf type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/docker/containers/8c994c51d266570fe21e657674399840d3b16928739d866397f8325a64c2b21b/resolv.conf)
/dev/sda1 on /etc/hostname type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/docker/containers/8c994c51d266570fe21e657674399840d3b16928739d866397f8325a64c2b21b/hostname)
/dev/sda1 on /etc/hosts type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/etc-hosts)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/sda1 on /run/libvirt type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/volumes/kubernetes.io~empty-dir/libvirt-runtime)
/dev/sda1 on /run/kubevirt-ephemeral-disks type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/volumes/kubernetes.io~empty-dir/ephemeral-disks)
/dev/sda1 on /run/kubevirt/container-disks type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/volumes/kubernetes.io~empty-dir/container-disks)
/dev/sda1 on /run/kubevirt/sockets type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/453ef05b-a84e-4355-ba24-1bc911ce0bab/volumes/kubernetes.io~empty-dir/sockets)
10.0.37.222:6789,10.0.37.221:6789,10.0.37.223:6789:/volumes/golden-virtual-machines/win10 on /run/kubevirt-private/vmi-disks/boot type ceph (rw,relatime,name=k8s.golden-virtual-machines.win10,secret=<hidden>,acl,wsize=33554432)
tmpfs on /run/kubevirt-private/secret/secret-volume type tmpfs (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)
```

* The nodes that are unable to start the VM use btrfs
* Nodes with overlay2 run VMs just fine.

**What you expected to happen**:

I would really like to be able to use btrfs as I have another workload that would benefit a great deal from having block-level copy-on-write as offered by btrfs, so being able to run VMs on nodes with btrfs would be nice.

**How to reproduce it (as minimally and precisely as possible)**:

Use btrfs as the root file system of host, add it to k8s as a node and schedule a VM on it.

**Anything else we need to know?**:

See #3119 for details, all are unchanged, except for having upgraded to kubevirt v0.35.0.

**Comment by rmohr** [comment]
> See #3119 for details, all are unchanged, except for having upgraded to kubevirt v0.35.0.

Just to clarify this: It worked for you before on btrfs? Which version was that?

**Comment by dren-dk** [comment]
Nope, I never had it working on btrfs.

**Comment by rmohr** [comment]
Hm, we had a lengthy discussion about a detail in here: https://github.com/kubevirt/kubevirt/pull/3124#pullrequestreview-375692235. Maybe we took the wrong route there.

**Comment by dren-dk** [comment]
Sorry about dropping the ball wrt. testing the original issue, we were quite busy around the time the fix was released and with the workaround in place, it wasn't an immediate priority.

I have a more readily available test setup for this issue now, so let me know if there's any more data needed.

**Comment by vasiliy-ul** [comment]
Since recently I've looked at the code related to containerDisk, I can share my findings here. Probably it might be usefull. Unfortunately I dont have a ready test setup with btrfs to check it. In current implementation the full path to the disk file is built by parsing `/proc/<pid>/mountinfo` and extracting different mount points info from there:

```
$ grep btrfs /tmp/mountinfo 
2545 1152 0:25 /@/var/lib/docker/btrfs/subvolumes/73f599843c89c363939d571c4750f75b306f88641186ccf64f8600f44cd2a48a / rw,relatime master:1 - btrfs /dev/sda1 rw,space_cache,subvolid=10136,subvol=/@/var/lib/docker/btrfs/subvolumes/73f599843c89c363939d571c4750f75b306f88641186ccf64f8600f44cd2a48a
2564 2547 0:25 /@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/containers/compute/fa1d5b16 /dev/termination-log rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/containers/compute/fa1d5b16
2565 2545 0:25 /@/var/lib/docker/containers/c57f80ddeac3cd940032c905aacda0ab199f65dbb5affc38645bda4ebbb95900/hostname /etc/hostname rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/docker/containers/c57f80ddeac3cd940032c905aacda0ab199f65dbb5affc38645bda4ebbb95900/hostname
2566 2545 0:25 /@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/etc-hosts /etc/hosts rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/etc-hosts
2568 2545 0:25 /@/var/lib/docker/containers/c57f80ddeac3cd940032c905aacda0ab199f65dbb5affc38645bda4ebbb95900/resolv.conf /etc/resolv.conf rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/docker/containers/c57f80ddeac3cd940032c905aacda0ab199f65dbb5affc38645bda4ebbb95900/resolv.conf
2569 2545 0:25 /@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/libvirt-runtime /run/libvirt rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/libvirt-runtime
2570 2545 0:25 /@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/infra-ready-mount /run/kubevirt-infra rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/infra-ready-mount
2571 2545 0:25 /@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/ephemeral-disks /run/kubevirt-ephemeral-disks rw,relatime - btrfs /dev/sda1 rw,space_cache,subvolid=257,subvol=/@/var/lib/kubelet/pods/1ca8dce4-a49e-45be-935f-3947f8f738fe/volumes/kubernetes.io~empty-dir/ephemeral-disks
```

From my observation there are potentially two issues:
1. Wiith btrfs subvolumes the output of the `mountinfo` contains leading `/@` symbols for all mounts. Those prevent from building a valid target file path. Perhaps a quick fix for that might be smth like below (`pkg/virt-handler/isolation/isolation.go`):
```patch
                                DeviceContainingFile: record[2],
-                               Root:                 record[3],
+                               Root:                 strings.TrimPrefix(record[3], "/@"),
                                MountPoint:           record[4],
                        }, nil
```

2. Another issue is about device major/minor. In the example above they are the same for all the btrfs subvolumes in the system: `0:25`. That is because a subvolume is not a separate block device. Therefore I assume that `func (r *realIsolationResult) ParentMountInfoFor(mountInfo *MountInfo) (*MountInfo, error)` will not return the proper info. Since it uses the device major/minor `DeviceContainingFile` to find the parent mount, it will return the first match and likely it will not be the one needed.

**Comment by Omar007** [comment]
I don't think this is actually solved. The problem is still present on 0.38.1.  

Going through the MR that supposedly fixed/closed this issue, it seems it has only hacked around it for systems where people have set up all their subvolumes in a 1-to-1 hierarchy on a subvolume named `@` below the default/top-level (id=5) but has not actually implemented support for btrfs. 
I.o.w., it only covers a setup where you have created a btrfs filesystem with a subvolume named `@` directly at the top-level and any/all other subvolumes on a 1-to-1/nested mapping underneath that `@` subvolume. So you end up with subvolume `@` being mounted at `/` and any potential other subvolumes such as `@/home` to be at `/home`, `@/var/lib/kubelet` to be at `/var/lib/kubelet`, etc. 
Only in this exact this situation/setup will stripping `/@` work and result in the path you can use to access it on the host system. It does not actually solve the subvolume problem or properly implement support for btrfs. 

If you haven't set it up exactly like that (e.g. when you didn't group it all under a subvolume named `@` but something/anything else) or when you're not using a nested/1-to-1 hierarchy (e.g. a flat hierarchy instead; subvolume `root` mounted at `/`, subvolume `home` mounted at '/home', subvolume 'kubelet' mounted at `/var/lib/kubelet`, etc) it will still fail with similar errors (just with other paths). 
The main issue here is that first path in mountinfo shows you the path in relation/context of the btrfs device/filesystem, NOT in relation to the mountpoint or root (`/`) of the host machine.

**Comment by vasiliy-ul** [comment]
Hi, @Omar007 . Probably you are right. The fix was based only on one specific host configuration. You can refer to the comments in that PR. That concern was discussed and we just agreed to apply it as a starting point. Do you have ideas how to implement it in a more generic way?

**Comment by Omar007** [comment]
I don't have a good grasp on how it's currently implemented in KubeVirt so I'd have to take a better look at the implementation but I get the feeling it's currently not properly using/parsing mountinfo. 

This is also the first time I've looked at mountinfo in this context so I might be completely wrong but to me it looks like that if you want to retrieve the mountpoint/path for something that is mounted at a different location/in another mount namespace, you can't rely on the information from a single mountinfo since it says nothing about mountpoints elsewhere. 
It looks to me like you probably need to first retrieve the device (field 9, /dev/mapper/root0 in my example) and path (field 4, /root/var/lib/.... in my example) for the mountpoint in your own mount namespace first (field 5, / in my example), then use that information to look up mountpoint in the other mount namespace based on that device and path information.

**Comment by Omar007** [comment]
I had a bit of time to look into this. It looks like KubeVirt is currently written as if this is something to handle and test in a way that is unique or would differs per filesystem but the way to process this should, from what I can tell based on the mount namespaces documentation, be the exact same regardless of filesystem and only depend on whether it's a private, shared or slave mount (and maybe not even that but this is going beyond what I was capable of reading in about an hour).  

I'm not sure how everything is working together but stepping backwards through the code starting from the error message, it looks like the logic to fix is contained within the files `isolation.go` and `isolation_test.go`.
