### ISSUE TITLE
Reduce virt-handler GET PVC api calls

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#5024]
While auditing the API calls virt-handler makes, I found two instances where we are performing GETs on every PVC attached to a VMI during every reconcile loop.

`hostdisk.ReplacePVCByHostDisk(vmi, d.clientset)` will perform a GET on every pvc to determine if it is a block pvc.
https://github.com/kubevirt/kubevirt/blob/3f2fdf3f22e0ac710ee4d6f9c3d92eb047c430f7/pkg/virt-handler/vm.go#L2042

```_, shared, err := pvcutils.IsSharedPVCFromClient(d.clientset, vmi.Namespace, volName)``` will perform a GET on every pvc to determine if it has RWM access mode. 
https://github.com/kubevirt/kubevirt/blob/3f2fdf3f22e0ac710ee4d6f9c3d92eb047c430f7/pkg/virt-handler/vm.go#L1925

we should find a way to cache this information so every a VMI pops on the reconcile loop it doesn't cause numerous PVC get calls.

**Comment by davidvossel** [comment]
@mlsorensen i'm not 100% certain, but there's a chance this could be related to the performance issue you experience with virt-handler at scale. other than that, The VMI informers we use for virt handler should be pretty efficient given they only sync changes related to the specific node and not all VMIs.

**Comment by mlsorensen** [comment]
I see. I was just about to open a ticket.  I got a report today that virt-handler accounts for 12% of all API use in one of our clusters.

As a total tangent, I also got this message but have no context on it yet. When I get more concrete information we can create an issue, I have no idea at this point if it's a real problem.

```kubevirt requests rate without resourceVersion set (even though they use a selector)```

**Comment by mlsorensen** [comment]
Would we first query a cache in: https://github.com/kubevirt/kubevirt/blob/3f2fdf3f22e0ac710ee4d6f9c3d92eb047c430f7/pkg/util/types/pvc.go#L72

And return that instead of doing a get, if found? Can we assume that the PVC wouldn't change meaningfully for us as long as the pod is on the node? We only have the volume name and the namespace to tell if we need to grab cache or query the API, not something unique, if we can do lookups in a cache by these values, and clear the cache when the pod stops to avoid collisions with recreated volumes of the same name, would that work?

**Comment by mlsorensen** [comment]
I'm playing with the k8s audit logs and if I'm reading this right, the vast majority of API calls from virt-handler are for "/version".  I have a test cluster with a dozen nodes, and over the course of 5 minutes "userAgent:  virt-handler/v0.0.0" made 1287 requests, 722 of these were for "/version".

**Comment by mlsorensen** [comment]
I went ahead and opened #5058 to track the "/version" piece separately.

**Comment by davidvossel** [comment]
resolved by #6226
