### ISSUE TITLE
[HotplugVolumes] Why disk must use a scsi bus?

### ISSUE THREAD

**Issue by cumirror** [kubevirt/kubevirt#5080]
I am using the HotplugVolumes feature recently. In the test, I found that only the disks with scsi bus are supported, but usually a virtio bus will be used.

Why does kubevirt have this limitation? The underlying qemu does not seem to have this limitation.

code: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
```			
disk := newDisks[k]
if disk.Disk == nil || disk.Disk.Bus != "scsi" {
	return webhookutils.ToAdmissionResponse([]metav1.StatusCause{
		{
			Type:    metav1.CauseTypeFieldValueInvalid,
			Message: fmt.Sprintf("hotplugged Disk %s does not use a scsi bus", k),
		},
	})
}
```

**Comment by awels** [comment]
Well basically the problem boils down to virtio bus uses a pci-root-port for each disk that is hotplugged. And you cannot dynamically increase the number of pci-root-port once the VM is started. By default there is a single available port for hot plugging a disk. So you can only add a single disk, which is not suffcient for many use cases.

We did not want to expose all the intricate details on configuring extra ports in the case you know ahead of time how many you need. I talked with the qemu developers for suggestions, and they told me the virtio-scsi supports more or less limitless number of disks you can hotplug.

We also looked at what other projects like oVirt are doing, they are all using virtio-scsi for hotplugging disks because of the same reasons. They also published benchmarks between virtio vs virtio-scsi and there was virtually no difference.

So in order to keep the API as simple as possible we defaulted to virtio-scsi. If you have a compelling use case where it makes sense to also support virtio and virtio-scsi is not sufficient we can certainly revisit that decision.

**Comment by cumirror** [comment]
Got it, thank you for your reply @awels
