### ISSUE TITLE
virt-handler metrics trigger API DoS with list calls to virtualmachineinstances

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#5193]
https://github.com/kubevirt/kubevirt/blob/d7a7d09b7c7ef9f67c9a9a598d7f6d2ec083cb57/pkg/util/lookup/lookup.go#L19

Prometheus metrics collection triggers a list call to virtualmachineinstances from each virt-handler. This can hit the Kubernetes API server pretty hard in larger clusters. Perhaps we can find a more efficient way to reflect this information. Further, this list call doesn't set a resourceVersion, which hits the etcd backend rather than allowing API cache to serve the request.

The call to API server, triggered by prometheus metrics collection, looks like this:

```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Request",
  "auditID": "d6328a34-0e8f-4d94-bbf4-3825b8b01199",
  "stage": "ResponseComplete",
  "requestURI": "/apis/kubevirt.io/v1alpha3/virtualmachineinstances?labelSelector=kubevirt.io%2FnodeName+in+%28node01%29",
  "verb": "list",
  "user": {
    "username": "system:serviceaccount:kubevirt:kubevirt-handler",
    "uid": "702c7284-9432-4c07-b505-a32422a4fcfe",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:kubevirt",
      "system:authenticated"
    ]
  },
  "sourceIPs": [
    "10.244.196.138"
  ],
  "userAgent": "virt-handler/v0.0.0 (linux/amd64) kubernetes/$Format",
  "objectRef": {
    "resource": "virtualmachineinstances",
    "apiGroup": "kubevirt.io",
    "apiVersion": "v1alpha3"
  },
  "responseStatus": {
    "metadata": {},
    "code": 200
  },
  "requestReceivedTimestamp": "2021-03-10T19:39:32.179339Z",
  "stageTimestamp": "2021-03-10T19:39:32.182319Z",
  "annotations": {
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"kubevirt-handler\" of ClusterRole \"kubevirt-handler\" to ServiceAccount \"kubevirt-handler/kubevirt\""
  }
}
```

**Comment by davidvossel** [comment]
> Prometheus metrics collection triggers a list call to virtualmachineinstances from each virt-handler.

Thanks for pointing this out. I find it frustrating that this got merged. We probably need to figure out a way to begin locking down when new k8s api server calls occur so it's harder for things like this to inadvertently slip in. 

For this issue, i bet the fix is fairly simple. 

all the VMIs on the each node are already cached in this virt-handler informer, https://github.com/kubevirt/kubevirt/blob/fab812ce1eda7d853c11a79deb4a34f3285fca3e/cmd/virt-handler/virt-handler.go#L218

we probably just need to pass that informer to the Prometheus collector here, https://github.com/kubevirt/kubevirt/blob/fab812ce1eda7d853c11a79deb4a34f3285fca3e/cmd/virt-handler/virt-handler.go#L308 and then use that for the lookup.

**Comment by rmohr** [comment]
> Thanks for pointing this out. I find it frustrating that this got merged. We probably need to figure out a way to begin locking down when new k8s api server calls occur so it's harder for things like this to inadvertently slip in.

Yes frustrating. It slipped through on a PR which I reviewed in 2019 already. The whole `lookup` package is an issue. For instance the `node` controller there also lists all VMIs from the apiserver since that change. I will take care of the node controller when #5269 is merged.
