### ISSUE TITLE
Support cgroupv2 in Kubevirt

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#5336]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

This is a placeholder issue to track the status of Control Group v2 (cgroupv2) support in Kubevirt.

https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

Cgroupv2 comes as a replacement of cgroupv1 and it introduces a new interface. Some features in Kubevirt make direct use of cgroup and therefore require adaptaion.

Initial support of cgroupv2 has been introduced in:
- https://github.com/kubevirt/kubevirt/pull/4907
- https://github.com/kubevirt/kubevirtci/pull/567
- https://github.com/kubevirt/project-infra/pull/1092
- https://github.com/kubevirt/project-infra/pull/1100

Known issues:
- Whitelisting block devices: cgroup v2 drops device cotntroller in favor of eBPF. New implementation is needed to attach/detach eBPF programs (affects `HotplugDisks`)
- Some tests are not run in CI: `KUBEVIRT_E2E_SKIP='Multus|SRIOV|GPU|Macvtap|Operator'`. Initially those were disabled for `k8s 1.20` and cgroupv2 lane inherited that.
- ~Currently cgroupv2 test image is a copy of k8s 1.20 with just a couple of config options addded (for the kernel command line and crio). Would be nice to have a single image and setup cgroup during `cluster-up`.~ Fixed in https://github.com/kubevirt/project-infra/pull/1414

**Comment by phoracek** [comment]
@vasiliy-ul with your PR merged, can we consider this Issue resolved?

**Comment by vasiliy-ul** [comment]
> @vasiliy-ul with your PR merged, can we consider this Issue resolved?

@phoracek , no the items listed in the description are not resolved yet. They need to be addressed in separate PRs.

**Comment by fabiand** [comment]
@iholder-redhat  @vasiliy-ul  is theer actually still outstanding work? If so, is there roughly a target date of when this work is finished?

BTW - Awesome to see this work taking place.

**Comment by iholder-redhat** [comment]
Hey @fabiand!
Yes - there is certainly an ongoing work which can be found in this PR: https://github.com/kubevirt/kubevirt/pull/6042 (which is not ready to review yet).

Long story short:
- I expect this PR to be updated & ready for review later today.
- This PR will not cause virt-handler to be cgroups v2 aware just yet - since container-selinux' policy prevents us from supporting it. I've merged a PR to container-selinux that change SPC containers policy. Now we only need to wait until we're affected by the changes. Until then I will push towards merging this PR so that once we're affected by container-selinux' changes we can support cgroups v2 right away.
- This PR does not only deal with supporting cgroups v2, but also involves a major refactoring. cgroup-related code was spread around many components, a lot of code was duplicated from runc repository (some of it was old and unmaintained) and was complex and hard to reason about. This PR creates a cohesive "cgroup" package that is fully v1/v2 agnostic from the user's perspective (e.g. can be used similarily to `cgroup.NewManager(...).Set(rule)`). It's a lot cleaner and compact and serves as a thin glue layer between us and runc.
- This PR had many obstacles in the way for many reasons. Two major ones were container-selinux' policy problem (which did not allow to create BPF programs while cgroups' v2 devices subsystem is entirely implemented with eBPFs) and runc repository which its logic was partly broken and had many problems (during my work they released v1.0.0, the first stable release in 5 years).

**Comment by iholder-redhat** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale

This PR https://github.com/kubevirt/kubevirt/pull/6042 has LGTM and is still waiting for review.
@rmohr @stu-gott

**Comment by iholder-redhat** [comment]
> /remove-lifecycle rotten /remove-lifecycle stale
> 
> This PR #6042 has LGTM and is still waiting for review. @rmohr @stu-gott

PR is merged. I think this issue can be closed.

**Comment by iholder-redhat** [comment]
> > /remove-lifecycle rotten /remove-lifecycle stale
> > This PR #6042 has LGTM and is still waiting for review. @rmohr @stu-gott
> 
> PR is merged. I think this issue can be closed.

@vasiliy-ul
