### ISSUE TITLE
Panic in apiserver logs during e2e test runs

### ISSUE THREAD

**Issue by fgimenez** [kubevirt/kubevirt#5353]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: Since 2021-03-26 11:36 CET we started noticing panics in the logs of the apiserver pods running on kubevirtci clusters, they look like this https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1375749634630094849/artifacts/k8s-reporter/1/pods/1_kube-system_kube-apiserver-node01-kube-apiserver.log

**What you expected to happen**: the apiserver pod of a cluster running kubevirt doesn't have any panic. 

**Anything else we need to know?**:
First jobs with this panic:
* 1.19                                                                                                                                                                                         
  * presubmit, first occurrence 2021-03-26 11:36 CET https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19/1375395932824145920
  * periodic, first occurrence 2021-03-27 11:01 CET https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1375749634630094849                               
* 1.18                                                                                                                                                                                         
  * presubmits, first occurrence 2021-03-26 18:45 CET https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.18/1375504143048773632                       
  * periodics, first occurrence 2021-03-28 00:01 CET https://prow.apps.ovirt.org/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1375930828252516352  

More recent occurrence with another test failing: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.18/1376857686909390848

/cc @maya-r

**Comment by ormergi** [comment]
I saw this panic also on a local setup, here is how to reproduce
Get kube-apiserver logs `kubectl logs kube-apiserver-node01 -n kube-system --since 1m -f`
On another terminal session create simple VMI `kubectl apply -f examples/vmi-masquerade`
And console to the VMI `virtctl console vmi-masquerade`
After a while I was connected to the VMI console, the panic error raised on the logs
there was no functional issues with the VMI from what I saw.

**Comment by maya-r** [comment]
Hi @fgimenez, any chance we can look at node usage metrics?
e.g. in the time of the panic 11:23:18.624116, did [node01](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5240/pull-kubevirt-e2e-k8s-1.19/1375395932824145920/artifacts/k8s-reporter/1/1_nodes.log) have heavy usage (i/o, cpu)?

**Comment by fgimenez** [comment]
I see from https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5240/pull-kubevirt-e2e-k8s-1.19/1375395932824145920/podinfo.json that this job run on `ibm-srv07.ovirt.org` here you can see the resource usage around that time https://graphite.phx.ovirt.org/d/IxtiYBemz/openshift-bare-metals?orgId=1&var-node=ibm-srv07_ovirt_org&from=1616714218475&to=1616804984617

**Comment by maya-r** [comment]
I came across [this](https://github.com/openshift/kubernetes/pull/480) which mentions several kubernetes pull requests like [this one to add a timeout to some requests](https://github.com/kubernetes/kubernetes/pull/95725) which otherwise starve other requests. I wonder whether this is what we're seeing.

Also, I would assume we need to update our vendored packages and not just the cluster version we use.

**Comment by maya-r** [comment]
awels mentioned that the test failures might be a regular race.
