### ISSUE TITLE
ssh connection hang after VM migrated

### ISSUE THREAD

**Issue by scuzhanglei** [kubevirt/kubevirt#5396]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
ssh to a VM hang after VM migrated.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
ssh to a VM(Masquerade to pod network) via service IP from terminal, then migrate the VM, after migrated, the ssh connection hang(can't make any operation), and I have to open a new ssh connection.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.35.0
- Kubernetes version (use `kubectl version`): 1.19.4
- VM or VMI specifications:
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Linux k8s-2 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by phoracek** [comment]
@scuzhanglei this is expected and there is no way around it. Due to limitations of underlying Kubernetes Pod network, external IP address of the VM changes once it lands on a different host.

If you want to preserve open connections, you have to use secondary multus network and handle IP management there yourself.
