### ISSUE TITLE
Use NodePort, drop externalIPs once CNI is fixed

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#542]
In #538 we move every inbound access to ingress.
However, the simple nodePort service type would be convenient, because we wouldn't need to specify any IP, but there is a bug in CNI (which we use) which is preventing this (kubernetes-incubator/kube-aws#704).

Once that bug is fied we can change the service to NodePort as well, which allows us to drop exteranlIP for good.

**Comment by rmohr** [comment]
Can you elaborate on what is not working? What is not working in CNI? Is there a bug open agains weave?

**Comment by fabiand** [comment]
Using a service like

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: spice-proxy
    port: 3128
    targetPort: 3128
    protocol: TCP
  - name: haproxy
    port: 8184
    targetPort: 8184
    protocol: TCP
  - name: virt-manifest
    port: 8186
    targetPort: 8186
    protocol: TCP
  selector:
    app: ingress-nginx
``

Should redirect the ports 3128, 8184, 8186 - but it doesn't.
The only ports which get redirected are the dynamically assigned ones.

**Comment by fabiand** [comment]
@rmohr you mentioned that it might be an outdated cni version in weave - but isn't cni shipped with kube?

**Comment by fabiand** [comment]
lThis might actually be weaveworks/weave#3016

**Comment by rmohr** [comment]
@fabiand yes that looks like the one. Thanks for digging it out.

**Comment by ArchiFleKs** [comment]
@fabiand I don't think it is related to CNI or Hostport if you are using Services, NodePort are handled by kube-proxy, and service are in a specific range : 

If you set the type field to "NodePort", the Kubernetes master will allocate a port from a flag-configured range (default: 30000-32767)

That's why your automaticly assigned service are working and not the one you specified manually outside the range.

You can change the range with the `service-cluster-ip-rang` flag

**Comment by rmohr** [comment]
haproxy is now removed.
