### ISSUE TITLE
disk img registry

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#5522]
/kind enhancement

Is there any reason why we only use quay.io to distribute KubeVirt images?

The architecture for quay.io is pretty bad resulting in severe outages in recent times.  I would like to see us get some redundancy.   CentOS yum repos have had redundancy for like 17.5 years.

**Comment by kwiesmueller** [comment]
I don't know about the options we have.
Docker is being moved away in many cases due to the pull limits.
We could provide our images on something like Google Container Registry, but that would mean additional cost for pulls we need to pay. Are there other options or does the CNCF suggest/provide anything?
Does GitHub offer something like this now?

**Comment by mazzystr** [comment]
GitHub offers a registry ... https://docs.github.com/en/packages/guides/about-github-container-registry

**Comment by usrbinkat** [comment]
Just passing through, personally I push images to quay.io, & docker.io for all builds. Critical images also go to ghcr.io & public.ecr.aws. I fallback to pulling from docker.io during quay outages. ghcr/ecr is last resort due to costs getting out of hand quickly on them.

I wish K8s had a native feature to pull fully qualified images in a list via weighted mechanism. Absent of that a manual flip covers outage times where a pull through mirror isnt present or doesnt have cached content.

**Comment by mazzystr** [comment]
I will check with RH OSPO / CNCF to see what they can provide for GitHub services
