### ISSUE TITLE
Remove node selectors from KubeVirt manifests. 

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#555]
Depends on #553 

Once #553 is complete, remove the node selectors from the KubeVirt component manifests.  #553 must be completed first because of the use of haproxy expects some components to live on a specific node. Once we remove haproxy, the node placement requirement is gone.

**Comment by rmohr** [comment]
> because of the use of haproxy expects some components to live on a specific node. Once we remove haproxy, the node placement requirement is gone.

haproxy does not need it. Some tests need it right now (they just need to be reworked) and it avoids unexpected timeouts during development/testing if you removel nodes to the cluster, since all core components always run on master, which is the only VM in our vagrant environment, which is always there.

**Comment by fabiand** [comment]
@rmohr can you tell which tests are affected?

**Comment by rmohr** [comment]
Done in #560
