### ISSUE TITLE
404 when connecting to console

### ISSUE THREAD

**Issue by steigr** [kubevirt/kubevirt#557]
I just tested kubevirt on tectonic. I deployed the manifest-files from v0.0.4 and all pods get up and running fine. When I want to connect I get following error.
```
$ virtctl console testvm --kubeconfig=$KUBECONFIG
Can't connect to console (404): 404 page not found
```

The requested resource is: `wss://kubernetes.example.com:443/apis/kubevirt.io/v1alpha1/namespaces/default/virtualmachines/testvm/console`

Kubernetes version is 1.8.2.

As I don't understand how the websocket is mounted behind the URL the via CDR I out of debugging options.

**Comment by rmohr** [comment]
Hi @steigr,

Yes that is a little bit confusing. We started with aggregated API-Server in mind before it was available and did not yet catch up with the aggregated API server availability. Right now we have a haproxy instance which proxies between our resources and kubernetes resources to provide a unified feeling. Since you are using the manifests from the repo, you should be able to connect to the console, if you use virtctl like this:

```
virtctl console testvm -master=http://${master_ip}:${master_port}
```

Default for ${master_port} is 8184 and ${master_ip} needs to be adjusted to an IP of one of your nodes which you can reach from you machine. You can set them in `hack/config-default.sh` and run `make generate`  to create an updated set of services. Also note that you can point `kubectl` to this endpoint too, since haproxy will redirect you to the k8s master for all endpoints which are not ours.

I guess you are aware of that anyway, but since we are in alpha state all this is wip and unusable for production.

Let us know if you need more help.

**Comment by rmohr** [comment]
Feel free to reopen if you need more help.
