### ISSUE TITLE
When removing VmReplicaSet, the scaled-up VMs are not deleted

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#590]
I am playing with virtual replica set. I have Q about behavior on deleting of replica set from cluster.

I have read [documentation](https://github.com/kubevirt/kubevirt/blob/master/docs/replica-sets.md) but I didn't find any about behavior on delete operation.

So I took a look at K8S [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/), and there is
```
To delete a ReplicaSet and all its pods, use kubectl delete.
Kubectl will scale the ReplicaSet to zero and wait for it to delete each pod
before deleting the ReplicaSet itself.
```
Unfortunately when I remove VmReplicaSet, it doesn't scale down VMs to 0, but leave them there ...
Is the current behavior correct ?

My steps:
```
kubectl create -f kubevirt/cluser/replicateset.yaml
kubectl get vmrs  # testreplicaset as expected
kubectl get vms  # 3 vms as expected
kubectl  delete vmrs testreplicaset  # success
kubectl get vms  # there are still 3 vms
```

**Comment by cynepco3hahue** [comment]
I think you can use --cascade flag, k8s does not remove automatically
nested resources.

**Comment by rmohr** [comment]
@lukas-bednar you are right, it does not do that. The reason is, that we are not yet using something like the aggregated api-server. Therefore, we have no chance of introducing a graceful-delete (which means that the controller is just marked as deleted and the controller can clean up and delete itself after it is done). Therefore it works like a `--cascade=false` is specified.

**Comment by lukas-bednar** [comment]
> I think you can use --cascade flag, k8s does not remove automatically
nested resources.

@cynepco3hahue but I want get my VMs get removed :-)
