### ISSUE TITLE
qemu-kvm get oom-killer

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#5958]
/kind bug

Hi Kubevirt, we start used with kubevirt as solution for our clusters. As of now still with low scale just to test all and see we can covers all or most of our requirements network/storage/performance/Devices... as of now I must to say your solution is amazing and we have only 2 main issues (As of now :) ).

1) libvirt POD consuming a lot of memory when we allocate VMI with 8 pcie devices.
2) the performance that we get is something that i believe can be batter than what we have today. ( I know there is many configuration and ingredient. I familiars with almost all and I'm play with kubevirt some time :) SRIOV (100G ) /Virtio-FS/WEKA storage solution and ceph/ disk of Nvme / 700GB RAM)

regarding #(1)
I have 2 problems, our KVM server looks like:  Mem: 740GB, 112 CPU (2 Socket,2 Thread, 28 Core) Nvme disk
and when we create a VMI with ~600G RAM + 106 CPU  + 8 pci devices that allocated **As you can see the memory jump to ~800GB** once the pci devices start to allocate.
![image](https://user-images.githubusercontent.com/34831587/124087007-46858780-da5a-11eb-99bf-4dd984405152.png)

another problem is that in case i want pinning the CPU im getting oom-killer (Always) and that a real problem for us.

k8s version:  1.19.10 (bare metal)
kuebvirt: 0.37
CDI: 1.31

**Comment by rthallisey** [comment]
cc @vladikr

**Comment by vladikr** [comment]
Hey Tal, @talcoh2x 

Thanks for reporting this. It's also great to see your project progressing so much!

When QEMU starts a virtual machine, it allocates memory for the guest OS but also uses an additional memory from the host for its monitor, various threads, for VFIO (device passthrough) it generally looks 1Gib of ram, VIRTIO-FS, etc...
In addition, currently, we add an overhead of 1Gib for VFIO devices, however, it is hard to estimate the overhead when multiple devices are being passthrough - it may be so that this estimation is incorrect.

Since KubeVirt runs Libvirt and QEMU in a container, all of this additional overhead[1][2] needs to be accounted for and added to the container's memory requests.
The correct estimation of the overhead becomes even more critical when dedicated CPUs (Guaranteed QoS) are being requested - In this case, KubeVirt will need to set CPU and memory Limits on the virt-launcher pod.
This means that the pod will be killed when an application (libvirt/qemu) running in the pod will try to use more memory than it requested.

I suppose that this is the reason why are you seeing an increased memory usage of the virt-launcher POD.

To address the oom-killer issues, perhaps, you could manually increase the overhead - this means requesting more memory for the virt-launcher POD than for the guest OS.

 For example: 
```
domain:
    memory:
      guest: 600Gi
.....
    resources:
      limits:
        cpu: 108
        memory: 850Gi
```

Please let us know if it helps.
Vladik

[1] https://github.com/kubevirt/kubevirt/blob/289213dc2502a1a8b958426e02b8cd794b1a927f/pkg/virt-controller/services/template.go#L1656
[2] https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#memory-overhead

**Comment by talcoh2x** [comment]
Hi @vladikr,
Yes i can see the "extra" 7G memory. NP i understand it and it's ok.
You want that I'll do memory-overcommit ? it will not impacts on my performance?

**Comment by talcoh2x** [comment]
@vladikr  BTW, just to highlight something without cpu pinning even if qemu process show VIRT of 800GB and VMI resource is only 600G kubevirt VM continue to run without any problem.

**Comment by vladikr** [comment]
> Hi @vladikr,
> Yes i can see the "extra" 7G memory. NP i understand it and it's ok.

> You want that I'll do memory-overcommit ? it will not impacts on my performance
This is essentially requesting more memory on the pod to allow the QEMU process to use more memory. 
It shouldn't affect performance.

**Comment by vladikr** [comment]
> @vladikr BTW, just to highlight something without cpu pinning even if qemu process show VIRT of 800GB and VMI resource is only 600G kubevirt VM continue to run without any problem.

That sounds correct. Without `dedicatedCpuPlacement`, the pod is being started with `Burstable` QoS meaning that the process running inside the pod can use more resources from host, if these are available. On the other hand, to obtain exclusive resources from the host, like CPU, the pod will run with `Guaranteed` QoS, therefore will have `limits` for its requested resources. Such pod will be oom killed if the process running inside the pod will try to use more memory than it requested.

**Comment by talcoh2x** [comment]
after @rmohr added support for guestMappingPassthrough we don't have such problem any more 
we can close it

**Comment by rmohr** [comment]
> after @rmohr added support for guestMappingPassthrough we don't have such problem any more
> we can close it

nice to hear :)

/close
