### ISSUE TITLE
Review and Revise User Guide

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#6088]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

Review and Revise User Guide by ensuring all information remains accurate and concise. We have some outdated items in there today.[s] Also, the documentation must include: 
   * known limitations, including what’s deferred from V1 and in the roadmap
      * Make the roadmap a visible item
   * day 2 operations guidance, e.g. upgrades and their impact
   * Add use cases for why using one option over other
   * User guide with user stories over straight up api doc.
   * Examples we people can copy/paste 
   * Release link that always points to the latest stable release
   * Examples: how to connect to VMs outside cluster. So ssh/rdp ingress from external to within the cluster that targets a VM host. 
   * Documentation Cleanup
      * Docs are spread out between … Repo kubevirt/kubevirt directory /docs, individual README markdown files located in various repo directories, repo kubevirt/user-guide markdown files which get presented by the Docsifyjs app and Google Pages under https://kubevirt.io/#/user-guide, main web site https://kubevirt.io/ pages and blogs
      * In the last 6 months I have repaired many broken links from the main website to external sources as well as main website to user-guide.  Problems keep popping up interfering with real work.  
      * Can we get a good reason behind using Docifyjs?  It seems all of the various js based engines have the same problem of making the html behind the markdown difficult to deal with.  We now have three different markdown formats to deal with (Jekyll, GitHub, Docsifyjs).  I propose we consolidate everything one way or another… Jekyll, GitHub, Docsifyjs … pick one...any one then let’s ensure we have tooling in place and a full migration.
         * Needs search bar, that mostly works.
      * The pages need to be reviewed for redundancy, missing, wrong content.  Case in point sometime in the past registryDisk was changed to containerDisk.  I recently fixed four cases in docs that still referenced registryDisk.

**Comment by yuchen-sun** [comment]
Hi @fabiand 
I'd be happy to help you with these documentation questions if you need help, as I too had a lot of doubts when I first read the documentation.

**Comment by fabiand** [comment]
@aburdenthehand in general this issue is covering to make our docs more approachable and correct. Any idea of how we can make this happen?

**Comment by aburdenthehand** [comment]
I'd like to take some time to think/review all of this a bit - particularly the tooling part of it - but off the top of my head:
1 How do we improve the docs going forward? 
  - Ensure we have docs built into our code process and maintain helpful contribution/style guidelines. There are linters we can apply to help out with docs PRs. 
2 How do we improve our current docs? 
  - Review and create a docs plan that takes into account our different user types, and segment the work based on priority and difficulty. Ensure these are appropriately tagged (good first issue, etc) to help guide new and interested contributors.
  - Maintain momentum on the docs plan so that we make consistent progress.
  - From the sounds of things we may need to centralise everything so that it's in the one repo?
3 How do we ensure docs are maintained properly going forward?
  - Ensure we have robust docs process built into updates.
4-x Some other stuff that I'm forgetting
  
There are some CNCF resources that I can take a look at it to help flesh this out a bit. 
@fabiand - Do you know who to talk to about the tooling - for historical context, maintenance, etc?
@yuchen-sun - Hello! Are you still interested in helping out? I know a lot can happen in 12 months but I'd be interested in your experience as you mentioned.

**Comment by yuchen-sun** [comment]
@aburdenthehand Of course, I'm happy to do something about it
