### ISSUE TITLE
[Outreachy][good-first-issue] Reduce Cognitive complexity

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#6310]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Sonarcloud has found many cognitive complexity issues in kubevirt [here](https://sonarcloud.io/project/issues?id=kubevirt_kubevirt&resolved=false)
**What you expected to happen**:
Breaking down of the code in an attempt to reduce the cognitive complexity

**Comment by MohammadRVR** [comment]
Please assign this issue to me

**Comment by MohammadRVR** [comment]
Hi @vatsalparekh @kubevirt-bot @phoracek 

I would like to work on this issue. Please assign it to me

**Comment by xpivarc** [comment]
Hi @MohammadRVR 
feel free to open an issue and put your specific goal(e.g reduce complexity in `this` function) to the description. You should then be able to assign the issue to yourself (or I will assign it for you). This issue is more of a placeholder.
Thank you for your interest and I am looking forward to your contribution.

**Comment by vatsalparekh** [comment]
@MohammadRVR feel free to take a look at the issues from https://github.com/kubevirt/kubevirt/issues?q=is%3Aissue+is%3Aopen+outreachy
