### ISSUE TITLE
functests: switch from cirros/alpine to more suitable image

### ISSUE THREAD

**Issue by mpolednik** [kubevirt/kubevirt#661]
When testing out initial q35-as-default PR #650, several issues with current cirros/alpine images used within functional tests surfaced.

First issue is networking, where when using q35 the VM is not able to communicate with external world, whereas simply switching it to i440fx works. The second issue behaves in similar fashion but with storage - rootfs cannot be found when disk iface is virtio-blk under q35.

Current consensus on the cause of this behavior is the image itself - both alpine and cirros are made to be as small as possible, and could have invalid assumptions about the virtualization environment. Solution to that could be using cloud image of full-featured distro such as Fedora.

**Comment by mpolednik** [comment]
cc @fabiand @nertpinx @michalskrivanek @rmohr

**Comment by nertpinx** [comment]
I'm trying to reproduce it and see what we can do to fix it. So I'll publish my finding shere.

For now I'm hitting another issue, However, I managed to get the cirrus working with q35. Unfortunately it's not that I would find the root cause. I tried seeing what's happening in the VM and after reboot it just started working and I can contact the outside world. I'll post what more I'll find.

**Comment by rmohr** [comment]
@nertpinx thanks for looking into the root cause. I would not have a good feeling to "just" switch to another image without knowing the problem.

**Comment by nertpinx** [comment]
Now it looks like the problem is really drivers for some of the connections of the card as it goes through the dmi-to-pci-bridge, etc. It can see the pcie root port, but probably not something else. Since it's so stripped down it's also harder to debug (almost no info in lspci for example).

**Comment by nertpinx** [comment]
Since the cirros image is so stripped down it's also harder to debug (almost no info in lspci for example). But it is clear now that it is missing kernel drivers for the pci-bridge, so it *is* the guest OS that's causing it to fail. I'm currently trying to prove that once more by booting the Fedora image.

**Comment by nertpinx** [comment]
Just changing the image to fedora works on local setup.

**Comment by rmohr** [comment]
We still use cirros 3.5. That's from 2014. Can you try it with 4.0? Seems they have a new version since last november.

**Comment by rmohr** [comment]
Cirros and Alpine are now both working with q35. In addition we also have the fedora cloud base image included as a registry disk, for cases where the othwer two are not sufficient.
