### ISSUE TITLE
The upgrade from v0.46.0 to v0.47.0 is failing

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#6763]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The upgrade from v0.46.0 to v0.47.0 is failing with:
```
{"component":"virt-operator","level":"error","msg":"reenqueuing KubeVirt kubevirt-hyperconverged/kubevirt-kubevirt-hyperconverged","pos":"kubevirt.go:589","reason":"rpc error: code = ResourceExhausted desc = trying to send message larger than max (2324167 vs. 2097152)","timestamp":"2021-11-09T11:17:07.470031Z"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling KubeVirt resource","name":"kubevirt-kubevirt-hyperconverged","namespace":"kubevirt-hyperconverged","pos":"kubevirt.go:637","timestamp":"2021-11-09T11:17:13.369681Z","uid":"d2fc13b4-46ed-4f79-9e3e-5ab3e823575b"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling deployment","name":"kubevirt-kubevirt-hyperconverged","namespace":"kubevirt-hyperconverged","pos":"kubevirt.go:983","timestamp":"2021-11-09T11:17:13.369832Z","uid":"d2fc13b4-46ed-4f79-9e3e-5ab3e823575b"}
{"component":"virt-operator","level":"info","msg":"Waiting on deployment virt-api to roll over to latest version","pos":"reconcile.go:288","timestamp":"2021-11-09T11:17:13.372548Z"}
{"component":"virt-operator","level":"info","msg":"Waiting on deployment virt-controller to roll over to latest version","pos":"reconcile.go:300","timestamp":"2021-11-09T11:17:13.372578Z"}
{"component":"virt-operator","level":"info","msg":"Waiting on daemonset virt-handler to roll over to latest version","pos":"reconcile.go:312","timestamp":"2021-11-09T11:17:13.372595Z"}
{"component":"virt-operator","kind":"","level":"error","msg":"Failed to create all resources: unable to create crd \u0026CustomResourceDefinition{ObjectMeta:{virtualmachineinstances.kubevirt.io  
```

See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1582/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-upgrade-prev-index-aws/1458014523230261248/artifacts/hco-e2e-upgrade-prev-index-aws/gather-extra/artifacts/pods/kubevirt-hyperconverged_virt-operator-6b89b7b86c-lnt4z_virt-operator.log for more logs

**What you expected to happen**:
the upgrade works

**How to reproduce it (as minimally and precisely as possible)**:
Try to upgrade from v0.46.0 to v0.47.0

**Anything else we need to know?**:
- We detected it on https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1582
- We detected it also on v0.46.0 -> v0.47.0-rc.0 ( please see https://github.com/kubevirt/kubevirt/issues/6727 )

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.46.0 -> v0.47.0
- Kubernetes version (use `kubectl version`): OCP 4.10
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
@rmohr @davidvossel maybe you can help here?

**Comment by zcahana** [comment]
The important bit from the logs is actually this:
```
{"component":"virt-operator","kind":"","level":"error","msg":"Failed to create all resources: unable to create crd <tons of CRD data omitted>: customresourcedefinitions.apiextensions.k8s.io \"virtualmachineinstances.kubevirt.io\" already exists","name":"kubevirt-kubevirt-hyperconverged","namespace":"kubevirt-hyperconverged","pos":"kubevirt.go:1036","timestamp":"2021-11-09T11:06:43.789557Z","uid":"d2fc13b4-46ed-4f79-9e3e-5ab3e823575b"}
```

So, the virt-operator attempts to **create** the VMI CRD instead of patching it, which leads to this conflict error ([here](https://github.com/kubevirt/kubevirt/blob/a7cddcc4fb5b332429978204984b1aab8ffbb720/pkg/virt-operator/resource/apply/crds.go#L76)). No clue yet why this happens, any chance the `CrdCache` hasn't synced yet while this function was executed?

**Comment by zcahana** [comment]
Here's what's happening: a recent PR (#6565) has changed the `app.kubernetes.io/managed-by` label value from `kubevirt-operator` to `virt-opertor`. This label is used as a label selector for most of the informers used by virt-operator, e.g. [here](https://github.com/kubevirt/kubevirt/blob/a7cddcc4fb5b332429978204984b1aab8ffbb720/pkg/controller/virtinformers.go#L690). Following the upgrade, this causes the OperatorCRD informer to drop all existing CRDs (labeled with `kubevirt-informer`) and hence to fail to observe that they already exist.

**Comment by rmohr** [comment]
@zcahana thanks for checking. Let's revert the PR and do a quick patch-level release.

**Comment by rmohr** [comment]
In a follow-up we should check why the upgrade for 0.46 to the devel release passed in the operator tests.

**Comment by zcahana** [comment]
> Let's revert the PR and do a quick patch-level release.

On it.

**Comment by rmohr** [comment]
> On it.

Awesome. Thanks.

**Comment by zcahana** [comment]
> In a follow-up we should check why the upgrade for 0.46 to the devel pr-code passed in the operator tests.

The most comprehensive upgrade test I found is [this](https://github.com/kubevirt/kubevirt/blob/ff8ebf3626bf2043f024bcd38377a1a9df4251a3/tests/operator_test.go#L1265), but it doesn't install a previous release of the virt-operator, but rather keeps/uses the current (tested) virt-operator and installs a previous release of the rest of the KubeVirt components (by setting the image tags in the KubeVirt CR).
In our case, the bug was introduced into a new version of virt-operator itself and would surface only when the upgrade is performed between two releases (unaffected --> affected) of virt-operator.

The best way to catch this kind of bugs is by testing a full-no-shortcuts upgrade. We could extend the operator lane with a test that runs such full upgrade. Note that HCO already does this kind of testing in its CI, but I'm not sure if/how can we leverage that to gate PRs (or at least releases) in the kubevirt repo.

**Comment by zcahana** [comment]
The bugfix has been backported in #6775 and a new release (v0.47.1) has been released and announced.
/close
