### ISSUE TITLE
Is there a method to config the target of live migration ?

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/kubevirt#7105]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

As far as I know, there is no setting of target migration.
Sometimes we need to set specific target of migration due to rebalancing resource.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@qkfrksvl the migration target will be chosen based on VMI node selectors, affinities and so forth. This turned out to be sufficient in the past for most relevant use-cases. Could you share what you are trying to achieve? That would help us either working with you on a solution based on implemented flows, or would provide a use-case which may make us reconsidering our current possibilities.

/triage needs-information

**Comment by ikandars** [comment]
@rmohr  it would be possible if kubevrit admission webhook allow to edit property `spec.nodeSelector` in VMI manifest. So the steps will be:

1. edit or add `spec.nodeSelector` in VMI object and put the target node label
2. apply `VirtualMachineInstanceMigration` to run live migration
