### ISSUE TITLE
Please add Cloud-hypervisor (Rust-Vmm) for light weight Virtual Machines

### ISSUE THREAD

**Issue by codesiddhant** [kubevirt/kubevirt#7163]
**Description**
The new rest-vmm based virtual machine are extremely fast and secure with minimum overhead please add new [cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor) in kubevirt.io for adding light weight VMs with much faster Boot time 

**Use case**
[cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor) is very similar to firecracker but with some additional features and security it's supports full-fledged Os including windows based Operating System and containers

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by fengye87** [comment]
Hi @codesiddhant, we've actually made a project named [Virtink](https://github.com/smartxworks/virtink) to support Cloud Hypervisor VMs solely on Kubernetes with some cool features like direct kernel boot with container rootfs.

We believe Kubernetes controllers should do one thing and do it well, that's why we created this project from scratch instead of introducing KubeVirt too many branches to deal with CH limitations and advantages. Our sight of it is that Virtink and KubeVirt can be two different but complement Kubernetes addons, KubeVirt is more specialized in traditional virtualized workloads while Virtink can be more specialized in cloud workloads.

Checkout our [Virtink](https://github.com/smartxworks/virtink) project if you are interested. Feel free to give us any feedbacks or questions on the project's issue board.

**Comment by codesiddhant** [comment]
Seems very interesting, I appreciate your contribution.

**Comment by lukasmrtvy** [comment]
@codesiddhant can You reopen this issue, please? Thanks

**Comment by poelzi** [comment]
/reopen
@kubevirt-bot bad bot

**Comment by xpivarc** [comment]
/lifecycle frozen
I would suggest anyone interested in this, please leave a comment with your use case and why Kubevirt with qemu is not sufficient enough for your use case. While it is technically challenging to add a new VMM to Kubevirt now it could be easier in the future.

**Comment by cheese** [comment]
FYI #8056
