### ISSUE TITLE
virtctl vnc not working on gpu enabled windows vms

### ISSUE THREAD

**Issue by jayasai470** [kubevirt/kubevirt#7208]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
virtctl vnc displays blank screen on gpu windows vms 
**What you expected to happen**:
use virtctl vnc to stream gpu enabled desktops
**How to reproduce it (as minimally and precisely as possible)**:
try to run virtctl vnc on gpu enabled vm

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jayasai470** [comment]
@victortoso FYI

**Comment by victortoso** [comment]
Hi @jayasai470, thanks for the bug.

So, just to be clear upfront, as far as I know, there is no way for the vnc server that runs in the host to display the contents of the gpu provided to the guest. There are projects that do that but they usually run on the guest too. QEMU's vnc server does not have that feature.

>  virtctl vnc displays blank screen on gpu windows vms

The fact that you see a blank screen is a bit puzzling. I think that the Guest is simply not using the emulated VGA device, only the GPU one. Could you confirm that you can access the (Windows?) VM with RDP running in the guest?

From KubeVirt/QEMU side, not sure if this scenario is easy to recognize in order to provide a proper error message to virtctl's user.

**Comment by jayasai470** [comment]
Hi @victortoso yes I can view the desktop using RDP
