### ISSUE TITLE
Use of multi GPU card

### ISSUE THREAD

**Issue by guleng** [kubevirt/kubevirt#7257]
version:
    k8s:v1.22.6
    docker:1.19.3
    node:Ubuntu 18.04
    kubevirt: 0.50
    kubevirt-gpu-device-plugin: 1.0.0

question：
I deployed kubevirt in k8s, and each node has eight NVIDIA GPU cards. I use "kubevirt GPU device plugin" to use GPU for virtual machines. I want four cards for virtual machines and four cards for other business non virtual machine k8s pods. However, if "kubevirt GPU device plugin" is used, the k8s pod cannot use GPU cards, I don't know how to allocate multiple GPU cards of a node to the pod scheduling of virtual machines and non virtual machines.

Are there any methods and suggestions to solve this problem?

**Comment by dhiller** [comment]
@vladikr could you take a look here? Thank you!

**Comment by uril** [comment]
Currently, based on [documentation](https://kubevirt.io/user-guide/operations/mediated_devices_configuration/), kubevirt takes control over all GPUs of a (selected) node.
This (taking control) is done based on the mediatedDevicesTypes list.

@guleng 
Can you add a vGPU device to a non-VM container (instead of the whole GPU) ?
It should be possible but I do not have instructions for how to do it.
Likely, it was not tested together with kubevirt.

If you want containers to use whole GPUs and the GPUs are different, then
you may be able to find a vGPU type that is supported by one GPU but not by another.
