### ISSUE TITLE
Need to support hybird kubevirt vms in a cluster

### ISSUE THREAD

**Issue by npu21** [kubevirt/kubevirt#7297]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What happened**:
In a cluster with both arm64 and amd64 nodes, currently,when virt-operator NewHandlerDaemonSet,there's some logic regarding this
![image](https://user-images.githubusercontent.com/11768607/156282352-435a2003-0101-4bb3-9cd5-33020de68f67.png)
so the virt-handler on arm64 nodes crashloopbackoff because of the InitContainers 
![`W5NKI 7)`8J}9CD`S` U7B](https://user-images.githubusercontent.com/11768607/156282766-a660a3f8-53d7-4441-bc31-ba998de342f5.jpg)
And there maybe some other logic different between arm64 and amd64

**What you expected to happen**:
In fact，kubevirt support both arm64 and amd64，however，the current logic of virt-operator and virt-controller only supports one of them in a cluster.
In my  scenario，my cluster is a hybird cluster with both arm64 and amd64 nodes，I want to launch kubevirt control plane pods and kubevirt vms according to the nodes architecture correctly.

**Comment by dhiller** [comment]
@zhlhahaha so I am assuming that you are already looking at this with #3558. As discussed in the community meeting we don't see an easy way to test this somehow. What do you think we should do with this one? Would there be a way to write a unit test at least?

**Comment by zhlhahaha** [comment]
> @zhlhahaha so I am assuming that you are already looking at this with #3558. As discussed in the community meeting we don't see an easy way to test this somehow. What do you think we should do with this one? Would there be a way to write a unit test at least?

Hi Daniel, I do not see the discuss in the [2022-03-02 MINUTES](https://docs.google.com/document/d/1kyhpWlEPzZtQJSjJlAqhPcn3t0Mt_o0amhpuNPGs1Ls/edit#heading=h.1y6ervkayqsm).
Anyway, I have not though it deeply. Here is some roughly ideas.
The core problem for hybird cluster is where we can get cpu architecture information. After solve this we can use the CPU arch information to generate arch specific VM configuration.
There are several places to do CPU arch specific modification,

- in the virt-api webhooks, set DefaultCPUModel, DefaultBootloader and DefaultDisksBus;
- in the pkg/virt-config/configuration.go, set DefaultOVMFPath, DefaultEmulatedMachines and DefaultMachineType;
- in the pkg/virt-launcher/virtwrap/converter/converter.go, set AutoattachGraphicsDevice, OS.SMBios and domain.Spec.Devices.Controllers
- in the pkg/virt-launcher/virtwrap/manager.go, set DetectEFIEnvironment and ConverterContext.Architecture
- in the pkg/virt-controller/watch/application.go, set topologyHinter.arch
- in the pkg/virt-handler/isolation/detector.go, set MemoryOverhead
- in the cmd/virt-handler/virt-handler.go, set nodeLabeller

Currently we get the CPU arch info from runtime.GOARCH. The CPU arch info supposed comes from worker node rather than the service running node, because some services may running on master node, and mater node may have different arch CPU with that on worker node in a hybird cluster.

In terms of unit test, only need to give a fake worker node CPU arch Information and see if kubevirt can generate correct VM configuration, like we are doing right now. The hybird cluster testing can be put in e2e test. This is hard to do, as we need a real hybird environment.

cc: @rmohr

**Comment by zhlhahaha** [comment]
Hi @rmohr @dhiller 
Do you have any suggestion on this?

**Comment by rmohr** [comment]
@zhlhahaha as you describe, the main discussion point will be where to get the desired cpu architecture from. Like I would expect a cluster default, and also ways to describe on the VM/VMI level the target architecture. In theory we could handle for some cases (like multi-arch boot images with containerDisks) the target architecture transparent, but in practice I would assume that this is not pracitcal for VMs. So basically useras and app owners would define upfront their target architecture on mixed setups.

Once it is clear where the target architecture is coming from, I think that the necessary changes fall naturally in place:

* Build multi-arch virt-launcher/virt-handler containers, or reference them explicitly otherwise in virt-operator/virt-controller. Multi-arch would probably be easiest, since otherwise e.g. different daemonsets for virt-handler need to be maintained.
* virt-api can do the proper validation when it knows the target architecture
* virt-handler and virt-launcher would naturally do the right thing, since we would run the right app for the right architecture.

I am not entirely sure if mixing architectures is a big enough use-case to implement it though. I would expect some more research and use-case study before we finally agree and tackle it. Could also be that we would not find enough use-cases right now but have more later.

**Comment by rmohr** [comment]
/reopen

We just merged #8293 and in principle we have all bits there now. It is however not released yet and especially around multi-arch container builds we may have some open bits left.

**Comment by xpivarc** [comment]
@rmohr Do you think we have everything in place?
