### ISSUE TITLE
VMI is in phase: Scheduled | Domain does not exist

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7325]
kubevirt 0.55.0, deploy windows, problems:

{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"win2016","namespace":"admin","pos":"vm.go:1547","timestamp":"2022-03-08T07:21:22.270713Z","uid":"1ca6a79e-d7b3-4974-95cc-1cbdd0223f5b"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"win2016","namespace":"admin","pos":"vm.go:1547","timestamp":"2022-03-08T07:21:22.278109Z","uid":"1ca6a79e-d7b3-4974-95cc-1cbdd0223f5b"}

      domain:
        resources:
          requests:
            memory: 8Gi
        devices:
          disks:
          - disk:
              bus: virtio
            name: windows
      volumes:
      - name: windows
        persistentVolumeClaim:
          claimName: windows

**Comment by lixiaobing1** [comment]
thx:)

**Comment by dhiller** [comment]
/triage needs-information

Could you please attach virt-handler and virt-launcher logs, also the complete vm spec?

**Comment by lixiaobing1** [comment]
thx, issue has been fixed :)

**Comment by forge3125** [comment]
Hi. Can we share what the fix was? I'm getting the same error while trying to deploy the demo VM. Also running Kubevirt v0.55.0.

log from virthandler pod...

{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:244","timestamp":"2022-08-16T21:33:03.747279Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[vhost-net541],}]","pos":"generic_device.go:245","timestamp":"2022-08-16T21:33:03.747406Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:244","timestamp":"2022-08-16T21:33:03.749614Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[kvm273],}]","pos":"generic_device.go:245","timestamp":"2022-08-16T21:33:03.749802Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:244","timestamp":"2022-08-16T21:33:03.752003Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[tun688],}]","pos":"generic_device.go:245","timestamp":"2022-08-16T21:33:03.752117Z"}
{"component":"virt-handler","kind":"","level":"info","msg":**"VMI is in phase: Scheduled | Domain does not exist",**"name":"testvm","namespace":"default","pos":"vm.go:1604","timestamp":"2022-08-16T21:33:09.826588Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of containerdisk volume","name":"testvm","namespace":"default","pos":"vm.go:2266","timestamp":"2022-08-16T21:33:09.826720Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of cloudinitdisk volume","name":"testvm","namespace":"default","pos":"vm.go:2266","timestamp":"2022-08-16T21:33:09.826745Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"testvm","namespace":"default","pos":"vm.go:1604","timestamp":"2022-08-16T21:33:09.904408Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 8b6f2a8b-63b3-4d05-b79f-f1a64714230a","name":"testvm","namespace":"default","pos":"vm.go:1860","timestamp":"2022-08-16T21:33:09.904572Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"testvm","namespace":"default","pos":"mount.go:357","timestamp":"2022-08-16T21:33:09.904821Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"testvm","namespace":"default","pos":"mount.go:747","timestamp":"2022-08-16T21:33:09.904904Z","uid":"8b6f2a8b-63b3-4d05-b79f-f1a64714230a"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"testvm","namespace":"default","pos":"vm.go:1894","timestamp":"2022-08-16T21:33:09.

**Comment by hijak** [comment]
same!

**Comment by xpivarc** [comment]
Please open a new issue with as much information as you can share.
