### ISSUE TITLE
multiqueue: Discussion about non virtio interfaces, and validation

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#7671]
Lets use this issue please in order to discuss 
If we want to convert Multi Queue to be best effort or keep it with the current validation.

**Is your feature request related to a problem? Please describe**:
Currently if Multi Queue is enabled, there must be at least one Virtio interface,
or no interfaces at all, else the validating webhook would block the creation
of either the VM or VMI.

There was a suggestion [1] to make Multi Queue Best Effort,
if possible allocate queues, if not don't, but don't fail the request.
The PR was closed because reviewers concluded we should warn
in case of an error, and it can't be best effort even that it has some corner cases.
The discussion was renewed when PR [2] was proposed.

PR [1] suggested the following change:
"enable Multi Queue when it makes sense"
Make the Multi Queue be a best effort.
In case Kubevirt can't honor it, simply don't, but don't reject the VM / VMI.

Reasons:
1. In case there is only one Cpu, the NIC gets a single queue, even that Multi Queue is enabled.
2. It will allow to use VM templates, and add any interface type upon needs,
without having to update the Multi Queue field.
3. Once we have hot unplug feature, it might make things more complicated,
unless the validating webhook is only for VM / VMI creation.
Note that even if it a mixed virtio + non virtio, where we hot unplug the virtio one,
won't be blocked, it means that at the end the machine will be with MQ enabled,
and only non virtio nics, which we block upon creation but not after hot plug.

Arguments against it:
1. About 1 above - A user asking for Multi Queue with one Cpu simply gets a single queue.
2. The guest OS user should explicitly request this, and it should
be deterministic, not silently ignored.

Please add any info that I might missed.

Lets discuss please what direction we want to take.

**Additional context**:
Previous discussions can be found on 
[1] https://github.com/kubevirt/kubevirt/pull/4631
[2] https://github.com/kubevirt/kubevirt/pull/7432

@AlonaKaplan @EdDev @dankenigsberg @maiqueb @davidvossel @vladikr @rmohr 
FYI as you were involved

Thanks

**Comment by davidvossel** [comment]
/cc @lyarwood 

In general, we don't have best effort tunings in our VMI api. If some one asks for something, they either get it, or they get a validation error if the tuning can't be satisfied.

The new flavor api does conceptually allow for best effort tunings though. For example, with the flavor api we're considering the idea of `preferred` fields. So a flavor could have `preferredDiskBus=virtio` which would default the disks to use virtio on a vmi. I could see `preferredMultiQueue` being another option.

> It will allow to use VM templates, and add any interface type upon needs,
without having to update the Multi Queue field.

If `preferredMultiQueue` is part of the flavor, then multiqueue doesn't have to be a part of the template at all. The flavor matched to the VMI will handle multiqueue.

**Comment by lyarwood** [comment]
> /cc @lyarwood
> 
> In general, we don't have best effort tunings in our VMI api. If some one asks for something, they either get it, or they get a validation error if the tuning can't be satisfied.
> 
> The new flavor api does conceptually allow for best effort tunings though. For example, with the flavor api we're considering the idea of `preferred` fields. So a flavor could have `preferredDiskBus=virtio` which would default the disks to use virtio on a vmi. I could see `preferredMultiQueue` being another option.
> 
> > It will allow to use VM templates, and add any interface type upon needs,
> > without having to update the Multi Queue field.
> 
> If `preferredMultiQueue` is part of the flavor, then multiqueue doesn't have to be a part of the template at all. The flavor matched to the VMI will handle multiqueue.

Apologies just catching up after PTO. Yeah the current series for flavors and preferences in https://github.com/kubevirt/kubevirt/pull/7578 introduces a preference of `preferredNetworkInterfaceMultiQueue` that is applied to the VMI submitted by the VM controller on start:

https://github.com/kubevirt/kubevirt/blob/a9c43b1cb6da664cecef2db5aba9863e8080c8b4/pkg/flavor/flavor.go#L311-L313

There's a chunky functional test in the series that needs to be broken up eventually but should give some context on how we envisage using flavors and preferences:

https://github.com/kubevirt/kubevirt/blob/8ab9f209dbca6a07b50f41bb393d8e2228a77ea6/tests/flavor_test.go#L178-L296

**Comment by dankenigsberg** [comment]
I think that deprecating `networkInterfaceMultiqueue` in favor of a flavor-level `preferredNetworkInterfaceMultiQueue` would make sense.
(I should dive deeper to understand how flavor-level defaults/preferences are going to be resolved with lower-level specific requests, but this is not the right place to discuss it)

**Comment by EdDev** [comment]
> In general, we don't have best effort tunings in our VMI api. If some one asks for something, they either get it, or they get a validation error if the tuning can't be satisfied.

I agree we do not have "best effort", however, we have something much worse (in API concepts): We have defaults.
Not only that, when the default was detected as not a fit for all cases, instead of going in the path of "specifics", we went and created a configurable defaults.
These layers of defaults and configurable defaults led us to the problem of maintenance we have today.
It is not only our maintenance issue, but also of clients that need to use our API.

> We can't deprecate NetworkInterfaceMultiqueue directly as PreferredNetworkInterfaceMultiQueue would still need something to set in the DomainSpec. We could however encapsulate the graceful fallback logic within the PreferredNetworkInterfaceMultiQueue preference, avoiding a failure when we later validate the VirtualMachineInstance

I think the direction is not to deprecate the functionality, but the API that tries to describe a generic state instead of being specific (per interface). If we will have this parameter per interface, there will be no need to make complex decisions and the flavors can easily adjust and set these per the interface types.

> Meaning the VM would have flavor with preferredNetworkInterfaceMultiQueue, and the VM controller would set on the VMI the multiqueue related tunings.
> 
> So, the flavor is using VMI tunings behind the scenes. We cant' get rid of tunings that the flavors use.

I think @dankenigsberg aimed to the deprecation of the global parameter in favor of one per-interface. Then the flavors will translate the needed (with its own logic) over to the logic-less API.

Will that make sense?

**Comment by davidvossel** [comment]
> I think @dankenigsberg aimed to the deprecation of the global parameter in favor of one per-interface. Then the flavors will translate the needed (with its own logic) over to the logic-less API.
> Will that make sense?

i don't know. It's unclear to me why someone would ever need to set this multiqueue option per interface

Maybe to take this back a bit. This discussion exists because of the technical limitations we have with what can be expressed using a VM templates. VM templates are static with variable substitution. Depending on the variables, it's possible portions of the VMI spec need to change for the spec to make sense.

The options i see are
1. change the multiqueue behavior on the VMI, which gets a little weird when people set multiqueue but don't actually get multiqueue
2. replace templates with flavors/preferences.

Is there a reason we can't plan to go with item 2?

**Comment by dankenigsberg** [comment]
> i don't know. It's unclear to me why someone would ever need to set this multiqueue option per interface

Multiqueue does not for free. Each queue takes memory and we allocate a CPU to service it. It makes sense to enable multiqueue only on interfaces where this kind of service is needed. That is why Linux and libvirt allows to set the number of queues per NIC. KubeVirt opted not to do so, but rather hard code a policy on how many queues should each NIC be allocated, based on the total number of cpus and nics. But that's not the only possible policy.

> This discussion exists because of the technical limitations we have with what can be expressed using a VM templates.

The discussion also stems from generic API design reasoning. The current API is not normalized and should be improved as it incurs redundant webhook validation, caused one [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2061208) and is likely to cause others once we allow NIC hot-plug.

> 1. change the multiqueue behavior on the VMI, which gets a little weird when people set multiqueue but don't actually get multiqueue

Note that this happens today, too. If I ask for multiqueue on a VM with one CPU, I'm getting a single queue. Our current API is already weird because on one hand it is very strict (you are not allowed to request multiqueue if you have no virtio) but on the other it quite lax (you may get a single queue). We have a semantics that is "best effort with a thorn".

> 2. replace templates with flavors/preferences.

Flavors gives us another location to clean up after imperfect API. For example, I assume that the flavor named "highperf" would have logic to enable multiqueue if the VM has virtio NIC, but disabled multiqueue if there is no NIC at all. In a way, it would be fighting against the lower-level KubeVirt API. I suggest to tidy up the lower level API, either by making it "best effort all the way" as in PR#4631 or by precise prescription as libvirt does.

**Comment by dankenigsberg** [comment]
> Does this sound reasonable?

To me it does, I suppose some people would like to see how many queues were enabled on each NIC.

**Comment by oshoval** [comment]
What about allowing to get this info, but not via the `status.interfaces` but via some virtctl API or so ?
I feel its better to keep  `status.interfaces` as light as possible ?

**Comment by lyarwood** [comment]
FWIW I agree with David here. 

> What about allowing to get this info, but not via the `status.interfaces` but via some virtctl API or so ? I feel that it is better to keep `status.interfaces` as light as possible ?
> 
> Another possible advantage of such, is that we don't need to keep this info anywhere, we just fetch XML upon request IIUC.

It's hardly overloading `vmi.status.interfaces` with additional data? Plumbing in a `virtctl` command that reaches all they way down into the domain XML of a guest seems far more heavyweight in comparison to me at least.

**Comment by davidvossel** [comment]
> What about allowing to get this info, but not via the status.interfaces but via some virtctl API or so ?
I feel that it is better to keep status.interfaces as light as possible ?
> Another possible advantage of such, is that we don't need to keep this info anywhere, we just fetch XML upon request IIUC.

the vmi status is the place used to aggregate info related to the vmi and publish it over a well defined api. I wouldn't be concerned about the status growing a new field, this happens pretty regularly as we need to present more detailed information.

**Comment by oshoval** [comment]
PR created https://github.com/kubevirt/kubevirt/pull/8071
