### ISSUE TITLE
ServiceAccount Volume compatible with Bound ServiceAccount tokens

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#7735]
**Is your feature request related to a problem? Please describe**:
Yes, this request should be addressing the need to adapt to the Bound ServiceAccount tokens and projected volumes change.

**Describe the solution you'd like**:
Due to bound service account tokens, pod level tokens are expiring. Toda KubeVirt generates disk images for a token (http://kubevirt.io/api-reference/main/definitions.html#_v1_serviceaccountvolumesource), thus if it expires, then it's still visible inside the guest, because the token is not getting updated on the virtual disk.

We need to fix this.

1. Fix how we can do this with disks (i.e. unplug, replug)?
2. Deprecate the disk approach, and use a file-system (virtiofs) based approach which will always pass through the  current pod level token. Here we need to check that virtiofs can be used in a restricted pod.

I'd personally prefer #2104 

**Describe alternatives you've considered**:

**Additional context**:

**Comment by jcanocan** [comment]
This issue should have been addressed in https://github.com/kubevirt/kubevirt/pull/9432 since it allows to expose ServiceAccounts through virtiofs. Therefore, ServiceAccounts changes could be reflected in vmis without requiring to be rebooted. This PR does not deprecate the current ISO based systems, it just add this possibility.

**Comment by jcanocan** [comment]
> @jcanocan While the above is true, an explicit feature gate is needed. We need to have a look if we can run virtiofs as non-root and without capabilities for these cases.

I have run some test without non-root and without capabilities in the virtiofs container, and the VMI is capable of reading the content of ConfigMaps, Secrets, DownwardAPI and ServiceAccounts. 

Regarding the feature gate, are you suggesting to expose a separate feature gate from the `VirtIOFSGate` specifically for config volumes  i.e. ConfigMaps, Secrets, DownwardAPI and ServiceAccounts shared with virtiofs? e.g. `VirtiofsConfigVolumes`. If yes, should the user enable both (`VirtIOFSGate` and `VirtiofsConfigVolumes`) in order to share their volumes with virtiofs?

**Comment by xpivarc** [comment]
@jcanocan 

>I have run some test without non-root and without capabilities in the virtiofs container, and the VMI is capable of reading the content of ConfigMaps, Secrets, DownwardAPI and ServiceAccounts.

Sounds like upstream worth! Lets get this in.

For the latter we do not need new feature gate but any feature that requires virtiofs should be protected right now unless we get the virtiofs working without capabilites and root.

**Comment by jcanocan** [comment]
> @jcanocan
> 
> > I have run some test without non-root and without capabilities in the virtiofs container, and the VMI is capable of reading the content of ConfigMaps, Secrets, DownwardAPI and ServiceAccounts.
> 
> Sounds like upstream worth! Lets get this in.
> 
> For the latter we do not need new feature gate but any feature that requires virtiofs should be protected right now unless we get the virtiofs working without capabilites and root.

We could implement a mechanism to discriminate when a user tries to share a configVolume with virtiofs. In that case, we can deploy a non-root virtiofs container without capabilities. Moreover, AFAIK `--sandbox` option needs to be `none`.  I'm agree that this should be protected with a feature gate, is the existing `VirtIOFSGate` feature gate good enough in your opinion?

**Comment by xpivarc** [comment]
>is the existing VirtIOFSGate feature gate good enough in your opinion?
Yes that is enough

**Comment by xpivarc** [comment]
I think  the final bit would be to support live migration.
