### ISSUE TITLE
make: *** [Makefile:187: format] Error 1

### ISSUE THREAD

**Issue by carpediemtal** [kubevirt/kubevirt#7738]
**What happened**:

I want to build kubevirt on my own, follow the guide([kubevirt/getting-started.md at main · kubevirt/kubevirt (github.com)](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md#i-just-want-it-built-and-run-it-on-my-cluster)), but I met this error.

Can anyone help me?

```bash
[root@localhost kubevirt]# make
./hack/dockerized "hack/bazel-fmt.sh"
go version go1.17.8 linux/arm64

c717b0987dfbd12c01fd2720ecdf6cebad9122d6a96830d9783426eeb096b06f
go version go1.17.8 linux/arm64
Regenerating sandbox
Another command holds the client lock:
pid=16
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

Waiting for it to complete...
Another command (pid=16) is running. Waiting for it to complete on the server (server_pid=20)...
Loading: 0 packages loaded
    Fetching @com_github_bazelbuild_buildtools; fetching
make: *** [Makefile:187: format] Error 1
```

**What you expected to happen**:
I wish I can make kubevirt successfully

**How to reproduce it (as minimally and precisely as possible)**:

```bash
git clone https://github.com/kubevirt/kubevirt
cd kubevirt
make
```

**Environment**:
- KubeVirt version (use `virtctl version`): 

  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)

  LATEST=20220509

- Kubernetes version (use `kubectl version`): 

  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
- Cloud provider or hardware configuration: N/A

- OS (e.g. from /etc/os-release): 

  NAME="openEuler"
  VERSION="22.03 LTS"
  ID="openEuler"
  VERSION_ID="22.03"
  PRETTY_NAME="openEuler 22.03 LTS"
  ANSI_COLOR="0;31"

- Kernel (e.g. `uname -a`): 

  Linux localhost.localdomain 5.10.0-60.20.0.52.oe2203.aarch64 #1 SMP Wed Apr 13 10:27:16 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

- Install tools: 

  ```bash
  $ LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-operator-arm64.yaml
  $ kubectl apply -f https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-cr-arm64.yaml
  ```

  

- Others: N/A

**Comment by zhonglin6666** [comment]
meet the same issue. 
Ubuntu 20.04
Centos 7.9

**Comment by dhiller** [comment]
@carpediemtal this looks like bazel is not able to fetch the dependencies for building the project. Are you behind a corporate firewall?

**Comment by lynn901** [comment]
I have the same problem, did you solve it?

**Comment by xiaobo55x** [comment]
We saw similar issue with corporate proxy!
@dhiller Do you know how to fix this issue?

**Comment by dhiller** [comment]
IIUC in general setting GOPROXY env var should work. What issues do you experience exactly?

**Comment by xiaobo55x** [comment]
> IIUC in general setting GOPROXY env var should work. What issues do you experience exactly?
I saw the below error logs after triggering the build with _'make'_
`Waiting for it to complete...
Another command (pid=16) is running. Waiting for it to complete on the server (server_pid=20)...
Loading: 0 packages loaded
    Fetching @com_github_bazelbuild_buildtools; fetching
make: *** [Makefile:187: format] Error 1`

The issue can be fixed with below changes:
`diff --git a/hack/dockerized b/hack/dockerized
index c97dd6f48..82eb2974e 100755
--- a/hack/dockerized
+++ b/hack/dockerized
@@ -22,6 +22,8 @@ SYNC_VENDOR=${SYNC_VENDOR:-false}
 
 TEMPFILE=".rsynctemp"
 
+CONTAINER_ENV="-e HTTP_PROXY=http://xxxx.com:913 -e HTTPS_PROXY=http://xxxx.com:913"
+
 # Be less verbose with bazel
 # For ppc64le the bazel server seems to be running out of memory in the Travis CI, so forcing no concurrent jobs to be run
 if [ -n "${TRAVIS_JOB_ID}" ]; then
@@ -135,19 +137,20 @@ if [ -n "$($KUBEVIRT_CRI ps --format '{{.Names}}' | grep ${BUILDER}-bazel-server
     fi
 fi
 
+echo "Starting Bazel server ..."
 # Ensure that a bazel server is running
 if [ -z "$($KUBEVIRT_CRI ps --format '{{.Names}}' | grep ${BUILDER}-bazel-server)" ]; then
-    $KUBEVIRT_CRI run --ulimit nofile=10000:10000 --network host -d ${volumes} --security-opt "label=disable" --name ${BUILDER}-bazel-server -w "/root/go/src/kubevirt.io/kubevirt" --rm ${KUBEVIRT_BUILDER_IMAGE} hack/bazel-server.sh
+    $KUBEVIRT_CRI run ${CONTAINER_ENV} --ulimit nofile=10000:10000 --network host -d ${volumes} --security-opt "label=disable" --name ${BUILDER}-bazel-server -w "/root/go/src/kubevirt.io/kubevirt" --rm ${KUBEVIRT_BUILDER_IMAGE} hack/bazel-server.sh
 fi
 
 # Update cert trust, if custom is provided
 if [ -n "$DOCKER_CA_CERT_FILE" ] && [ -f "$DOCKER_CA_CERT_FILE" ]; then
-    $KUBEVIRT_CRI exec ${BUILDER}-bazel-server /entrypoint.sh "/usr/bin/update-ca-trust"
+    $KUBEVIRT_CRI exec ${CONTAINER_ENV} ${BUILDER}-bazel-server /entrypoint.sh "/usr/bin/update-ca-trust"
 fi
 
 # Run the command
 test -t 1 && USE_TTY="-it"
-if ! $KUBEVIRT_CRI exec ${USE_TTY} ${BUILDER}-bazel-server /entrypoint.sh "$@"; then
+if ! $KUBEVIRT_CRI exec ${CONTAINER_ENV} ${USE_TTY} ${BUILDER}-bazel-server /entrypoint.sh "$@"; then
     # Copy the build output out of the container, make sure that _out exactly matches the build result
     if [ "$SYNC_OUT" = "true" ]; then
         _rsync --delete "rsync://root@127.0.0.1:${RSYNCD_PORT}/out" ${OUT_DIR}`

**Comment by xiaobo55x** [comment]
`word`

**Comment by dhiller** [comment]
@xiaobo55x thanks! I figure that we need to whitelist those `HTTP_PROXY` and `HTTPS_PROXY` env vars in the `Makefile` targets that require them. Are you willing to contribute this with a PR?

**Comment by xiaobo55x** [comment]
> @xiaobo55x thanks! I figure that we need to whitelist those `HTTP_PROXY` and `HTTPS_PROXY` env vars in the `Makefile` targets that require them. Are you willing to contribute this with a PR?

Yes, I will send a PR to fix it!

**Comment by xiaobo55x** [comment]
@dhiller I have post a PR for this issue, please help have a review! Thanks!
