### ISSUE TITLE
Deprecation policy for Kubevirt

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#7745]
For a long time now the topic of deprecation policy had been around, and I think it is time to make the discussion formal.

**Motivation:**
In order for any software to be reliable enough for production use, it needs to have a stable API. This means that users would have a high confidence that the way they use Kubevirt would not become obsolete, or at least would give the proper time to prepare if it does.
This is relevant to anything that is exposed directly to the user, such as:
* API
* Feature behavior
* Supported versions for dependencies
* Assumptions / limitations on users usage
* Etc

On the other hand, in order to advance and improve Kubevirt, old parts would have to be dropped off or drastically changed every once in a while. Since currently Kubevirt does not have an official deprecation policy, the burden of being backward compatible is accumulated. In many cases, developers cannot know for sure if users actually depend on a certain old API that ought to be removed, therefore keep everything backward compatible for the benefit of the doubt.

**Solution:**
Kubevirt's deprecation policy should be determined through discussing a formal process and guidelines for developers. The process should probably determine things like:
* How to notify the users about a future deprecation
  * For example, through logs, events, etc
* How further back do we guarantee backward comparability
  * For example, when a feature becomes stable it would take at least 3 releases to deprecate it completely
* What is the deprecation process from the community's aspect
  * For example, this could be done via a "deprecation proposal" (similar to "design proposal") which would be reviewed by the community

These topics and more should be discussed here.

**Links and references:**

Obviously, we have many references for deprecation policies, the most obvious one being [Kubernetes](https://kubernetes.io/docs/reference/using-api/deprecation-policy/), that should be explored to bring initial ideas into this discusison.

**Status:**
- [x] Feature gates: https://github.com/kubevirt/kubevirt/pull/7791
- [ ] labels / annotations (e.g. https://github.com/kubevirt/kubevirt/issues/8583)
- [ ] API
- [ ] Feature behavior

**Comment by iholder-redhat** [comment]
FYI @vladikr @davidvossel

**Comment by davidvossel** [comment]
There's certainly a lot to tackle here with a policy like this. I like the idea of the Kubernetes "living" document which keeps evolving as new scenarios are encountered. These situations can get quite nuanced, so hard rules can't always be followed.

Maybe as a first step, we can define how we deprecate feature gates, because that's something pretty small I think we can tackle easily.

My suggestion for that would be that once we eventually "graduate" a feature gated feature to always on, we simply warn people when the feature gate is used, and tell them that it doesn't do anything. This warning could come in the form of a validation "warning" which get's sent back to the user when they create/update a resource. Existing configurations should continue to work without breaking compatibility.

**Comment by iholder-redhat** [comment]
> There's certainly a lot to tackle here with a policy like this. I like the idea of the Kubernetes "living" document which keeps evolving as new scenarios are encountered. These situations can get quite nuanced, so hard rules can't always be followed.
> 
> Maybe as a first step, we can define how we deprecate feature gates, because that's something pretty small I think we can tackle easily.
> 
> My suggestion for that would be that once we eventually "graduate" a feature gated feature to always on, we simply warn people when the feature gate is used, and tell them that it doesn't do anything. This warning could come in the form of a validation "warning" (our validation webhook can send these) which get's sent back to the user when they create/update a resource. Existing configurations should continue to work without breaking compatibility.

Thanks for your response.
Feature gates a are indeed the easiest to tackle with, and your suggestion sounds great to me. Do you think that we, at some point, need to remove feature gates or simply keep them around as a no-op for compatibility?

I think that one of the most important topics to deal with is API deprecation. It's a bit more sensitive issue, but perhaps also pretty easy to tackle. What do you think about the following process:
1. An API deprecation-proposal needs to be merged. There, the community members would have a discussion of deprecating the API makes sense. The proposal can also provide further details about the deprecation according to a template we'll create, similar to design proposal template.
2. A mail would be sent to kubevirt-dev mailing list about the API deprecation.
3. In each Kubevirt release, we will downgrade the API version. For example, if `v1` API is decided to be deprecated in Kubevirt version X, it will before `v1beta1` in version X+1, `v1alpha1` in X+2 and would be fully deprecated in version X+3. As soon as the deprecation proposal merges, a warning should be popped up whenever using the API.

Also bear in mind that we can change the rules a bit within the discussion on the deprecation proposal. For example, we can decide that we would keep the API for a longer time, or any other demand according to the specific API we're dealing with. This would also help us to update this process (that, as you said, would be a "live document").

Does it make sense to you?

**Comment by davidvossel** [comment]
> Feature gates a are indeed the easiest to tackle with, and your suggestion sounds great to me. Do you think that we, at some point, need to remove feature gates or simply keep them around as a no-op for compatibility?

As long as the feature still exists, I don't really see an issue with keeping them around as no-op for compatibility.  I think we'd just want a running list of feature gates that have "graduated" to always on, and warn users whenever they use one of those feature gates.

> I think that one of the most important topics to deal with is API deprecation. It's a bit more sensitive issue, but perhaps also pretty easy to tackle. What do you think about the following process:
> 
> 1. An API deprecation-proposal needs to be merged. There, the community members would have a discussion of deprecating the API makes sense. The proposal can also provide further details about the deprecation according to a template we'll create, similar to design proposal template.
> 2. A mail would be sent to kubevirt-dev mailing list about the API deprecation.
> 3. In each Kubevirt release, we will downgrade the API version. For example, if `v1` API is decided to be deprecated in Kubevirt version X, it will before `v1beta1` in version X+1, `v1alpha1` in X+2 and would be fully deprecated in version X+3. As soon as the deprecation proposal merges, a warning should be popped up whenever using the API.


I think that the mechanics around how we deprecate an API should closely align with what Kubernetes does today [here](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api). Meaning that we likely adopt all the rules outlined there as a starting point and only deviate when we need to.

For example, everything that the Kubernetes policy outlines around how versions are incremented when ever a field is removed should apply to us. The things that differ are the timelines when we eventually remove the old outdated version. So, I'd expect the timelines and how deprecation is communicated to be unique for our policy, but the mechanics of how the apis are handled to mostly remain the same.

This would mean that rather than "downgrading" an existing API, we would increment the version number and deprecate (and eventually remove) the old version in time. For APIs that are being removed entirely, we'd just deprecate and remove after a specificed time. Webhooks can be used to warn users who are using deprecated APIs that their API will be removed in some future `X` release.

^ That discussion only handles how APIs are deprecated over time. We'll also need to handle deprecating features that aren't necessarily tied to an api version, like virtctl cli arguments for example.  We should use kubernetes as a startign point for this policy as well, https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior

**Comment by iholder-redhat** [comment]
> As long as the feature still exists, I don't really see an issue with keeping them around as no-op for compatibility. I think we'd just want a running list of feature gates that have "graduated" to always on, and warn users whenever they use one of those feature gates.

I agree. The only concern that comes into mind here is that developers would continue to use the feature gate not knowing it's deprecated. But this is a devs problem, not an user problem. We can think how to tackle that (perhaps automatically ?)

> I think that the mechanics around how we deprecate an API should closely align with what Kubernetes does today [here](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api). Meaning that we likely adopt all the rules outlined there as a starting point and only deviate when we need to.
> 
> For example, everything that the Kubernetes policy outlines around how versions are incremented when ever a field is removed should apply to us. The things that differ are the timelines when we eventually remove the old outdated version. So, I'd expect the timelines and how deprecation is communicated to be unique for our policy, but the mechanics of how the apis are handled to mostly remain the same.
> 
> This would mean that rather than "downgrading" an existing API, we would increment the version number and deprecate (and eventually remove) the old version in time. For APIs that are being removed entirely, we'd just deprecate and remove after a specificed time. Webhooks can be used to warn users who are using deprecated APIs that their API will be removed in some future `X` release.

I completely agree.
As you said, the timelines may differ from Kubernetes' policy. For example, they write "GA API versions may be marked as deprecated, but must not be removed within a major version of Kubernetes". What is a "major version" for Kubevirt? Should this be simply determined by number of releases we make (e.g. X next releases)?

I think it's best to start with something fairly arbitrary (e.g. deprecate for 5 releases with warnings from webhooks, then remove on the 6th release) and then refine it in the future if we need to. WDYT?

> ^ That discussion only handles how APIs are deprecated over time. We'll also need to handle deprecating features that aren't necessarily tied to an api version, like virtctl cli arguments for example. We should use kubernetes as a startign point for this policy as well, https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior

Agreed. As a starting point I think we should use the same policy for APIs and tools like virtctl. As you said, this should serve as a live document and we can always refine it over time.

---------------

@davidvossel Do you think we have enough here in order to have an initial policy? I've already started this PR https://github.com/kubevirt/kubevirt/pull/7791 (which needs to be refined and updated). Do you think it's okay to close this issue and continue there?

Thanks a lot

**Comment by davidvossel** [comment]
> I think it's best to start with something fairly arbitrary (e.g. deprecate for 5 releases with warnings from webhooks, then remove on the 6th release) and then refine it in the future if we need to. WDYT?

something like that seems like a reasonable starting point.

> @davidvossel Do you think we have enough here in order to have an initial policy? I've already started this PR https://github.com/kubevirt/kubevirt/pull/7791 (which needs to be refined and updated). Do you think it's okay to close this issue and continue there?

using the k8s doc as a starting point, i think we have enough to go on here to draft our own policy. Our policy will likely evolve pretty quickly as we're also considering release cadence changes as well.

**Comment by iholder101** [comment]
This effort had a good start with a policy to deprecate feature gates :)
I think the effort should indeed continue

/remove-lifecycle stale
