### ISSUE TITLE
[sig-scale] virt-controller-node workqueue has too many key requeues

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#7968]
**What happened**:
Thanks to the PR #7879 the virt-controller now has higher throughput, and VM creation latency is lower.

By increasing the throughput we are able now to see some hidden issues that was not showing up before. For example, when creating 1k VMs, there are a lot of requeues in the virt-controller-node workqueue.

In the figure below, the first bump is the original virt-controller QPS/Burst configuration, the other ones are increasing the QPS/Burst.
![image](https://user-images.githubusercontent.com/5133121/174821450-e90e4d57-a25a-4083-af1f-f7919b00bc18.png)

**What you expected to happen**:
Lower requeue by fixing what is preventing the key to be properly processed or maybe increase the requeue time if possible. This will improve the performance and scalability.

**How to reproduce it (as minimally and precisely as possible)**:
A cluster where you can create a large number of VMs, in my case was 1k.
Increase the virt-controller QPS/Burst

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by andreyod** [comment]
NodeController in virt-controller is doing kind of monitoring for node responsiveness and node orphaned/errored VMIs so by design it constantly re-enqueue nodes(with 1 minute delay). The catch is that the controller watches for both node and VMI events, so 1 minute after the burst of VMI events there will be a burst of re-enqueue. The reconciliation is short and simple(if the node is responsive) but still can impact virt-controller performance. To improve this we should reconcile nodes and VMIs but re-enqueue only on node events.
