### ISSUE TITLE
Pass environment variables from templates to virtual machine instances

### ISSUE THREAD

**Issue by SyngoPredevelopment** [kubevirt/kubevirt#7992]
**Is your feature request related to a problem? Please describe**:
Need the possibility to set environment variables for VirtualMachineInstance instances from the kubevirt yaml templates.
For example for virtual machines created through containerDisk (also for other types):

_containerDisk:
&nbsp; image: myimage:latest
&nbsp; imagePullSecret: regcred_

it would be great to have the possibility to pass environment variables through values referenced for example from config maps.
Something like (similar like for normal pods in K8s):
    
_env:
&nbsp;- name: MYENVVARIABLE
&nbsp;&nbsp;&nbsp;valueFrom:
&nbsp;&nbsp;&nbsp;&nbsp;configMapKeyRef:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name: myconfigmap
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;key: myenvvariable_

**Describe the solution you'd like**:
Configuring environment variables in this way after startup of the virtual machine the environment variable would be set to the value from the referenced config map.
This should work for Linux as well as Windows virtual machines.

**Describe alternatives you've considered**:
Currently I am trying a solution using startup scripts:
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/
Unfortunately for the solution proposed I need to do a autologon (Windows example) 
in order to run a script at startup which sets the environment variables.

**Additional context**:
This whole feature is needed for deployment specific K8s clusters which have the need
to specify the same environment variables with different values within the virtual machines managed by kubevirt.

**Comment by alicefr** [comment]
@SyngoPredevelopment I spent some time on this and it is also an old topic (see [here](https://lists.nongnu.org/archive/html/qemu-devel/2015-02/msg00441.html)) and cloud-init seems really the best way to achieve this.
If we create a file on an iso or directly mount a file using virtiofs, in both cases we need an agent inside the guest that performs the mount (e.g cloud-int).
The other way could to rely on libguestfs-tools and copy a file with the environmental variable inside. We already have guestfs-tools as supported images and it could be started as init container. However, this is quite a large effort from Kubevirt. This could be achieved by using [tekton-tasks](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/tasks/disk-virt-customize). The real problem is that we don't control what is installed in the guest and really depends on the guest OS

**Comment by SyngoPredevelopment** [comment]
Thanks for the information. I meanwhile have chosen a solution where i do it inside the vmi with a Windows Service which communicates with other K8s services at startup of the vmi. The solution with cloud-init and Windows is very complex, i decided against it.
It would have been nice to have the same functionality like for normal pods like setting environment variables or mapping config maps as files inside the container etc. I understand that this is then very much work from kubevirt side, will continue with the Windows Service which collects all needed information at startup. Many thanks again !

**Comment by alicefr** [comment]
@SyngoPredevelopment we could discuss this in the next community meeting if there are other use-cases for this. Would you like to document in the [user-guide](https://github.com/kubevirt/user-guide) how you did for Windows VMs? This might be very helpful for other KubeVirt users that face the same problem
