### ISSUE TITLE
sig-network: Proposal - Run only latest k8s version as presubmit, rest as periodics

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#8169]
**Is your feature request related to a problem? Please describe**:
Currently each PR runs 5 lanes of sig-network (not only sig-network but focusing on it on this proposal)
`k8s-1.22-sig-network`
`k8s-1.23-sig-network`
`k8s-1.24-sig-network`
`k8s-1.23-sig-network non root`
`k8s-1.24-sig-network single stack ipv6`

All those lanes make CI very busy, and we us all waiting a lot of time
to see results / to merge PRs.

It is very rare that old k8s versions have regression that is flaky,
at the worst case if a feature breaks, it breaks totally
and on the latest versions, not on the previous.

**Describe the solution you'd like**:
We suggest to make at least those periodic (maybe even more of the above list)
`k8s-1.22-sig-network`
`k8s-1.23-sig-network`

The periodic test-grid will send email to the sig-network group
and we will monitor those.
EDIT - or send to a dedicated slack channel as we are doing with the other periodics.

**Describe alternatives you've considered**:
See please
https://groups.google.com/g/kubevirt-dev/c/c0U4lv6PYcM/m/9ZZ9-aQZBAAJ?utm_medium=email&utm_source=footer&pli=1
Please comment whatever the alternatives you suggest or any comments.

Investigate usage of Tekton with prow
https://github.com/kubernetes/test-infra/issues/13874#issuecomment-521237150

**Additional context**:

**Comment by maiqueb** [comment]
While there's a problem to fix (overwhelmed CI), I do not think dropping lanes (essentially testing less) is the correct thing to do.

I'm aware you want to rely on periodics; that - imo - is not enough since we have flaky tests all over.

I really think that for us to merge a PR - that touches either e2e tests or the production code - we need to make sure that all tests passed at least once (in all the supported k8s versions).

There are changes that happen in the k8s API that would not cause flakes (i.e. would constantly fail / pass), but, some others - let's point the finger at the K8s client for instance - that probably would, since they add auto-retry for WATCH / GET / LIST methods for instance. Your code using k8s 1.23 would for instance feature an auto-retry for certain methods on that particular version, but not have it on previous versions.

... having said that, we should improve what we have.

**Comment by fabiand** [comment]
My biggest concern with this is that it will introduce an inconsistency between the major lanes.

Also: Periodics: Show me three bugs that you found and fixed based on periodics. IOW I think periodics are under monitored.

I'd suggest: Get rid oof the nonroot lane ASAP

What about the single stack ipv6 lane?

**Comment by oshoval** [comment]
> I'd suggest: Get rid oof the nonroot lane ASAP

I think thats indeed going to happen, not sure what blocks it, @brianmcarey knows IIRC ?

> What about the single stack ipv6 lane?

We do need it, because we support single stack ipv6.
We have it only on the latest one, not sure we will want to make it periodic, unless the sig network decide otherwise

Thanks for the comments

**Comment by EdDev** [comment]
> Also: Periodics: Show me three bugs that you found and fixed based on periodics. IOW I think periodics are under monitored.

Hmm... this works in both ways.
Can we identify any bug that showed up on older k8s versions but not on the latest we test against?

It is perfectly reasonable to have such a scenario, as older k8s clusters may not support some features.
As we need to balance between available resources and the amount of checks, this may still be a reasonable risk to take, assuming it will be eventually detected by the periodic checks.

I must admit, I find it hard to vote one way or the other.

**Comment by oshoval** [comment]
I think that it deserves a try only on network lanes
We might find out that we are too strict now for no need
