### ISSUE TITLE
When stop/start vm, new vmi may be deployed to new node, so how to copy data from old node vm to new node vm?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#8460]
When stop/start vm, new vmi may be deployed to new node, so how to copy data from old node vm to new node vm?

**Comment by usrbinkat** [comment]
There are several possible roots of the behavior described. Most of them will be answered by providing the VM yaml, and by including the requested information from the [kubevirt/kubevirt bug template](https://github.com/kubevirt/kubevirt/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).

Please share more info so that we can help.
