### ISSUE TITLE
Second migration fails with containerDisk and containerd runtime

### ISSUE THREAD

**Issue by shweta50** [kubevirt/kubevirt#8471]
**What happened**:
I’m trying to migrate VMI with containerDisk.
First time the VM live migrates successfully, but on the second migration, it fails with the below error in the target virt-launcher pod. This works fine when using docker runtime.
`Warning Failed     23s (x2 over 51s) kubelet      Error: ImagePullBackOff
 Normal  Pulling     11s (x3 over 54s) kubelet      Pulling image "sha256@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd"
 Warning Failed     9s (x3 over 52s)  kubelet      Failed to pull image "sha256@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/sha256@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd": failed to resolve reference "docker.io/library/sha256@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd"`

**What you expected to happen**:
VMI’s should be migrated multiple times without any errors.

**How to reproduce it (as minimally and precisely as possible)**:
Create VMI with containerDisk. 
live-Migrate VMI twice 

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- VM or VMI specifications: 

> spec:
  domain:
    cpu:
      cores: 1
      model: host-model
      sockets: 1
      threads: 1
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - masquerade: {}
          name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: e03ae16f-10d6-4ed6-9ed2-6212ba8556f3
    machine:
      type: q35
    resources:
      requests:
        memory: 1024M
  networks:
    - name: default
      pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: quay.io/kubevirt/fedora-cloud-container-disk-demo
        imagePullPolicy: Always
      name: containerdisk

 
- Container runtime: containerd

**Comment by vasiliy-ul** [comment]
Link to the discussion in Slack: https://kubernetes.slack.com/archives/C8ED7RKFE/p1662020784894239

**Comment by vasiliy-ul** [comment]
I think I have some updates here. For the migration we want to use the same exact containerdisk on the target node and for that we need to know the SHA-digest of the image. In current implementation, we extract it from `ContainerStatuses` of the `virt-launcher` pod using the `Image` and `ImageID` fields.

What happens with `containerd` and e.g. `quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.57.0` is the following:

- when created, the vmi gets scheduled to some node (assuming `node01`) and `containerd` pulls the required image using the provided tag `v0.57.0`:
```
# crictl -r unix:///run/k3s/containerd/containerd.sock images
IMAGE                                                      TAG                  IMAGE ID            SIZE
...
quay.io/kubevirt/fedora-with-test-tooling-container-disk   v0.57.0              e3559e53b6b1d       684MB
...
```
- then, when we first time migrate the VMI, during preparation of the pod on the target node (assuming `node02`), we take the SHA-digest instead of the tag. For the specified image, the pullable reference will look like `quay.io/kubevirt/fedora-with-test-tooling-container-disk@sha256:30750fe1f8936e21890a4e45289ec3afdbcae3d9072ec7d7629ec20f4afbd00e` and `containerd` will pull that on the target node:
```
# crictl images 
IMAGE                                                                  TAG                    IMAGE ID            SIZE
...
quay.io/kubevirt/fedora-with-test-tooling-container-disk               <none>                 e3559e53b6b1d       684MB
...
```
** thing to note here is that there is no tag: `<none>`.
- After the first migration, when we want to migrate for the second time (from `node02` back to `node01`), we repeat the process with extracting the SHA-digest. However, now there is a difference. I assume, because the image now does not have an assigned tag, what we get in the `ContainerStatuses[].Image` is the `IMAGE ID` (listed above in the `crictl` output) in the form of `sha256:e3559e53b6b1df866598887793f94b9908d3a7e343f4a6394670d69fbe511cb2`. And here we take `sha256` as the image name, and eventually it ends up in trying to pull this weird image reference: `sha256@sha256:30750fe1f8936e21890a4e45289ec3afdbcae3d9072ec7d7629ec20f4afbd00e`. Interesting thing is that `kubectl describe pod ...` shows `Image` as a correct reference, while `kubectl get pod -o json ...` gives that `sha256:....`.


I think in order to fix it, we need to get the image from the VMI spec instead of using the `ContainerStatuses[].Image` field.

@shweta50, as a quick workaround you can just pre-pull the image on your nodes using the tag, e.g.:
```
crictl pull quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.57.0
```
