### ISSUE TITLE
Why kubevirt components have no resource limits set?

### ISSUE THREAD

**Issue by chrisho** [kubevirt/kubevirt#8485]
We would like to add resource limits to each component of Kubevirt to ensure a stable allocation of node resources, can the community provide best practices for calculating how many resources a component needs?

related issues:
https://github.com/harvester/harvester/issues/2729

**Comment by rthallisey** [comment]
The trouble with setting limits upstream is knowing exactly how much memory each component should be using at all times in all cases.  For the virt-operator that's quantifiable because it's upper bounded by the number of nodes and it would be strange for a user to constantly kill control-plane pods.  Other KubeVirt components don't have these limitations, so I'm skeptical if limits will have a positive affect in the upstream repo.

However inside a controlled environment like an end user's cluster, it could make sense.  Maybe you can provide some guidance on your cluster size, vm throughput, and we could help build a guide for end users.

**Comment by chrisho** [comment]
thanks @rthallisey 
I recently did some CPU benchmark tests on virt components, when operating about 100 VMs, as below:
![image](https://user-images.githubusercontent.com/3347460/191921369-aa6813d4-5a84-47bb-ad78-b9a4453b9976.png)
![image](https://user-images.githubusercontent.com/3347460/191921383-9520753e-1a2c-441a-957c-f4902bea6081.png)
![image](https://user-images.githubusercontent.com/3347460/191921403-47acb979-da79-4e4d-930e-76b7eaf49880.png)

Can you provide pprof for virt components? I want to know where the CPU performance is consumed.

**Comment by rthallisey** [comment]
There's a cluster-profile tool you can build with `make bazel-build` to get the profiles - https://github.com/kubevirt/kubevirt/tree/main/tools/cluster-profiler

**Comment by chrisho** [comment]
After re-verification, CPU performance is fine, the PromQL statement refers to the CPU percentage ratio and not the number of cores used. https://github.com/harvester/harvester/pull/2774#issuecomment-1294426262

In addition, I also analyzed kubevirt components and most of the performance consumed was due to `json` parsing and `openapi` validation. https://github.com/harvester/harvester/pull/2774#issuecomment-1294622928

thanks. cc @rthallisey

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten
It might be a good idea to at least provide configuration knobs to set these limits. As mentioned we don't set them because limits have a strong correlation to the cluster size and the operations on the cluster, which we don't know upfront.

**Comment by xpivarc** [comment]
/open
/good-first-issue

> /reopen /remove-lifecycle rotten It might be a good idea to at least provide configuration knobs to set these limits. As mentioned we don't set them because limits have a strong correlation to the cluster size and the operations on the cluster, which we don't know upfront.
