### ISSUE TITLE
gpu occupied by another vm after vm stopped

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8496]
**What happened**:

Let say I have one GPU and two vm(vm1 and vm2) both request one GPU:

* vm1 started normally 
* vm2 start failed because insufficient of GPU

When I stop vm1, then virt-launcher-vm1 pod delete, the unschedulable vm vm2 occupied the GPU resource.  At this moment vm1 start failed.

**What you expected to happen**:

Do not release GPU resource when vm1 stopped(or restart, restart  will delete pod and re-create it).

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by usrbinkat** [comment]
The best recommendation I can offer is to be more specific in how you label GPU devices to prevent GPU contention, if multiple VMs are pinned to the same GPU label, then which ever VM can schedule to a matching available GPU will do that and this appears to be expected behavior.

**Comment by chenxinlong** [comment]
@usrbinkat 

Hi, how should I add label to GPU devices ?  Currently I let GPU device passthrough to guest, so there's no "GPU device" 
 api resource in kubernetes.

**Comment by xpivarc** [comment]
> @usrbinkat
> 
> Hi, how should I add label to GPU devices ? Currently I let GPU device passthrough to guest, so there's no "GPU device" api resource in kubernetes.

Hey,
how do you expose the GPU to Kubernetes? The idea described is to name specific gpu devices with one name and that name could be referred to only by one VM. That is definitely not ideal.  

Now here we are lacking the K8S support because there the concept of device reservation doesn't make much sense for VMs. You would need to develop your own device plugin that would understand the concept of reservation/ownership for the VM or you can use resource quotas to distribute your resources.
