### ISSUE TITLE
How to build docker image of kubevirt?

### ISSUE THREAD

**Issue by joeevon** [kubevirt/kubevirt#8577]
Hello, i have met some cases that current release can not satisfy our situtation, and probably will not be supported in future. Because it is specially situtation in our business mode.
So, i have to modify code and build docker image.
But now, i do not know how to build image. May i have your help?

**Comment by alicefr** [comment]
hi @joeevon, it will be interesting to know what are the cases that kubevirt cannot satisfy.

Otherwise, we build the container image using bazel. You can see an example in [virt-launcher](https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-launcher/BUILD.bazel#L169). You should be able to modify KubeVirt code and then run `make bazel-build-images`. This builds an imabe tarball and they aren't visible with the `docker images`. You can directly push the images to a registry using the command `make bazel-push-images`. We have various environmental variables that help you customizing the image names such as `DOCKER_PREFIX`  and `DOCKER_TAG` (see the [Makefile](https://github.com/kubevirt/kubevirt/blob/main/Makefile#L28))

**Comment by joeevon** [comment]
@alicefr thanks for reply so much.
first, the cases that kubevirt cannot satisfy:
1.vram of video is fixed at 16384 Bytes, which is not enough, it leads to the operation in vnc is not smooth;
2.we need to retain some resources(eg: ip, gpu) where vm is restarted or stopped, #8550 , but now it will released as pod completed or deleted.

i will try to build docker image according to your suggest.
thanks so much.

**Comment by alicefr** [comment]
@joeevon I know very less about 1. However, I'm really curious how you plan to solve 2. Do you plan to keep the virt-launcher pod running even if the VM is shut down?

**Comment by joeevon** [comment]
@alicefr We will test in that tack, do you have suggestion?
