### ISSUE TITLE
Add virtctl install

### ISSUE THREAD

**Issue by deesejohn** [kubevirt/kubevirt#8648]
**Is your feature request related to a problem? Please describe**:
KubeVirt docs describe installing the operator and crds via manifests, manually verifying the components have deployed, and then separately installing virtctl matching the version. This requires a little work to automate.

**Describe the solution you'd like**:
It would be useful to do the opposite order, instead install the virtctl cli based on the version we wanted to use, and then execute `virtctl install` (similar to how `cilium install` works). `virtctl install` could block until the components are verified as deployed or a separate `virtctl status` command could be created.

**Describe alternatives you've considered**:
A shell script can achieve the same goal. Another alternative would be a helm chart as described in issue https://github.com/kubevirt/kubevirt/issues/8347.

**Additional context**:
Checkout `cilium install` and `cilium status --watch` from their [Quick Installation](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-cilium) docs. Other examples include: [Istio](https://istio.io/latest/docs/setup/getting-started/#install) and [Linkerd](https://linkerd.io/2.12/getting-started/#step-3-install-linkerd-onto-your-cluster).

**Comment by davidvossel** [comment]
This is a neat idea. in the cluster-api (capi) community, `clusterctl` can install capi components using a similar concept.

I'd like to see a design of this feature, and for us to work through how certain paths are handled (like updates and removal). It might also be interesting to have cdi installed automatically as well as part of this tool since cdi is such an integral component to kubevirt now.

**Comment by asaub** [comment]
We are working on this on https://github.com/asaub/kubevirt/tree/feature/add-virtctl-install
