### ISSUE TITLE
Monitoring metrics not available for K3s if namespace is default.

### ISSUE THREAD

**Issue by knitanurag** [kubevirt/kubevirt#8698]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/13597410/198935954-8ef908d8-9da4-4089-9ffd-c6340137123a.png">

used above deploy Kubevirt . my Prometheus operator is installed on default namespace.
no metrics for kubevirt.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/13597410/198936258-340f30db-a0b3-4e19-98de-04d977051ee3.png">

**Comment by usrbinkat** [comment]
Possibly related to https://github.com/kubevirt/kubevirt/issues/8044

**Comment by knitanurag** [comment]
@usrbinkat Hey, I just found a solution in which i have edited the Prometheus to allow service monitor from all the namespaces and also edited the pod monitor namespace and selector to open for all. now i am getting some of the metrics but still there are some metrics that kubevirt documented but i am not able to see.
I also see there is no proper documentation available if it is other than openstack platform.

**Comment by usrbinkat** [comment]
It looks like the available docs for Kubevirt/Prometheus coverage are [here](http://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator) and I assume you've found them. This might be an opportunity to PR to docs pages.

Are you able to clarify which metrics you're missing that you expect to see?

Perhaps @sradco might have some other info?

**Comment by sradco** [comment]
@knitanurag @usrbinkat Please have a look here https://book.kubebuilder.io/reference/metrics.html
at the paragraph that starts with: "If you are using Prometheus Operator ensure that you have the required permissions".

Please update which metrics are documented and are no showing.

**Comment by liyang516** [comment]
@knitanurag I got the same problem, have you been resovled this problem?

**Comment by AKS74n** [comment]
Okay. If anyone has a same issue, here's a resolve steps.
BTW the Prometheus I use is based on kube-prometheus-stack helm chart since prometheus-operator already deprecated.

1. Add Helm repo from `prometheus-community` and download kube-prometheus-stack tgz (not install)
2. Extract tgz file and open `values.yaml` inside extracted folder.
3. Find `serviceMonitorSelectorNilUsesHelmValues` and set to `false`
4. Use `helm package` to re-pack tgz file. Then install it.
5. Follow [here](https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator) to add `monitorNamespace` and `monitorAccount` into kubevirt config.

Probably had another better solution, this is what I figure out.

**Comment by AKS74n** [comment]
> @knitanurag @usrbinkat Please have a look here https://book.kubebuilder.io/reference/metrics.html at the paragraph that starts with: "If you are using Prometheus Operator ensure that you have the required permissions".
> 
> Please update which metrics are documented and are no showing. Available metrics are documented here https://github.com/kubevirt/monitoring/blob/main/docs/metrics.md

Hi @sradco , I can provide some information about the metrics that didn't show up.
But there're few metrics I haven't test since my platform didn't fulfill the live migration conditions yet.

Here's a list that metrics didn't show up on my current platform:
(Note: the metric name with * in the end means all sub metrics in this type didn't show up)

KubeVirt：
- kubevirt_vmi_filesystem_*
- kubevirt_vmi_memory_used_bytes

**Comment by cybercoder** [comment]
> > @knitanurag @usrbinkat Please have a look here https://book.kubebuilder.io/reference/metrics.html at the paragraph that starts with: "If you are using Prometheus Operator ensure that you have the required permissions".
> > Please update which metrics are documented and are no showing. Available metrics are documented here https://github.com/kubevirt/monitoring/blob/main/docs/metrics.md
> 
> Hi @sradco , I can provide some information about the metrics that didn't show up. But there're few metrics I haven't test since my platform didn't fulfill the live migration conditions yet.
> 
> Here's a list that metrics didn't show up on my current platform: (Note: the metric name with * in the end means all sub metrics in this type didn't show up)
> 
> KubeVirt：
> 
> * kubevirt_vmi_filesystem_*
> * kubevirt_vmi_memory_used_bytes

Have you fixed this?
![Screen Shot 1403-06-31 at 16 48 22](https://github.com/user-attachments/assets/adc475b1-df8d-4b93-9ecd-8313f3666eca)
I have not ```kubevirt_vmi_memory_used_bytes``` too!

**Comment by sradco** [comment]
Do you have a guest agent installed on the vms?
