### ISSUE TITLE
vm.yaml has invalid image name

### ISSUE THREAD

**Issue by martinpitt** [kubevirt/kubevirt#874]
In https://github.com/cockpit-project/cockpit/pull/8947 I'm trying to rebuild Cockpit's openshift image which includes the current release (v0.3.0) of kubevirt. This tries to deploy iscsi-demo-target.yaml (which works, or at least does not fail), and then [vm.yaml](https://github.com/kubevirt/kubevirt/blob/master/cluster/vm.yaml). But this specifies `image: kubevirt/cirros-registry-disk-demo:devel` which [does not exist](https://hub.docker.com/r/kubevirt/cirros-registry-disk-demo/tags/). I figure it should match the released version, so maybe it should use `{{ docker_tag }}` like the [iscsi demo](https://github.com/kubevirt/kubevirt/blob/master/manifests/testing/iscsi-demo-target.yaml.in)?

So I pulled kubevirt/cirros-registry-disk-demo:v0.3.0 and changed the file to use the `:v0.3.0` tag. 

~But then it still fails:~ **Update**: All good, I just forgot the setup steps.

**Comment by martinpitt** [comment]
Nevermind, I forgot the `bootstrapKubevirt()` bits in my manual test. Now it's working fine, so this is just about the bad tag.

**Comment by fabiand** [comment]
Cool. Closing this, let me know if you need anything else.

**Comment by martinpitt** [comment]
No no, the invalid image name is real. The bit that wasn't was the thing after "But then it still fails...", which I already updated in the description. Please reopen.

**Comment by rmohr** [comment]
@martinpitt looking at https://github.com/cockpit-project/cockpit/pull/8947/files#diff-3db8a96aef3a0ad8fd60930f6774d271R47, we use in all our examples the `devel` tag which we do intentionally not publish. That helps us to ensure that we can tie or examples to the exact repo content. If you would run `make cluster-up && make cluster-sync` followed by a `cluster/kubectl.sh create -f cluster/vm.yaml` the manifests would work.

We could probably rethink that, since registry disks themselves never changed since they got implemented.

**Comment by martinpitt** [comment]
Thanks. If it's by intent, I'm fine with keeping that seddery there. Admittedly I'm just monkey-patching around, this was originally written by @mareklibra - maybe he has a comment about this.

**Comment by fabiand** [comment]
Closing in favor of #1045
