### ISSUE TITLE
identify shutdown "within" or "outside" 

### ISSUE THREAD

**Issue by attlee-wang** [kubevirt/kubevirt#8817]
How do I identify whether it is an internal shutdown of the virtual machine or an external shutdown of the virtual machine?

**Comment by alicefr** [comment]
@attlee-wang could you please be more precise about what you mean by `internal` or `external` shutdown?

**Comment by attlee-wang** [comment]
@alicefr  internal: os shutdown，such as user exec `shutdown -h now` at VM insite.  external:  In addition to kubevirt components by other exceptions caused，such as the problem with the system disk.

**Comment by alicefr** [comment]
AFAIU, if user executes inside the guest `shutdown` or `poweroff`, then the pod/VMI should be in Completed/Succeeded state. If there is an error with the system, I'd expect some kind of error message. For example, on IO errors, the guest is in paused state, but the virt-launcher still runs and an event is thrown.
Otherwise, if you are talking about errors during boot, again the virt-launcher pod should be running, and for example you can run `vnc` to check what caused the problem. 
Or do I understand this wrong?
