### ISSUE TITLE
Could kubevirt use qemu rbd module for direct access a ceph rbd block device?

### ISSUE THREAD

**Issue by weixiao-huang** [kubevirt/kubevirt#8897]
**Is your feature request related to a problem? Please describe**:
No

**Describe the solution you'd like**:
qemu provide a [ceph rbd integration](https://docs.ceph.com/en/quincy/rbd/qemu-rbd/#running-qemu-with-rbd). Could kubevirt use it directly instead of mount a Block PVC device in the host? It seems directly using rbd module of qemu is much more efficient.

**Describe alternatives you've considered**:
See above

**Additional context**:
No

**Comment by xpivarc** [comment]
Hi,
for now, there is no support for this and I am not aware of any plans. @alicefr I believe there was a similar discussion around, can you link it?

**Comment by alicefr** [comment]
There was a similar question and discussion [here](https://github.com/kubevirt/kubevirt/issues/952#issuecomment-1202138461). We could use it if we have a storage solution using the [qemu-storage-daemon](https://qemu.readthedocs.io/en/latest/tools/qemu-storage-daemon.html) that could used any qemu storage backend, and then QEMu could access the storage through vhost-user protocol and the QSD.
We are collecting requirements about this, if you have any numbers or experience you could share, this could help us a lot.

**Comment by LittleFox94** [comment]
QSD would be needed because of the second requirement [in this comment](https://github.com/kubevirt/kubevirt/issues/952#issuecomment-455520614), "However, we can not leak the PV details into the VM Pod, as PV connection details are considered to be pirvate"?

What about having this feature only in combination with Rook, using the [`CephClient`](https://rook.github.io/docs/rook/v1.11/CRDs/ceph-client-crd/) resource? Rook is a great way to integrate Ceph and Kubernetes, even if the Ceph cluster is not in Kubernetes itself - integrating this way seems useful to me.

~~Having Qemu speak Ceph RBD directly would the big benefit of live migration with RBD volumes - currently this is not possible as they cannot be created `ReadWriteMany`~~ - always check your comments before sending them, `Block` mode volumes can in fact be RWX! TIL. Still think this would be a good feature though :D

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten

> QSD would be needed because of the second requirement [in this comment](https://github.com/kubevirt/kubevirt/issues/952#issuecomment-455520614), "However, we can not leak the PV details into the VM Pod, as PV connection details are considered to be pirvate"?
> 
> What about having this feature only in combination with Rook, using the [`CephClient`](https://rook.github.io/docs/rook/v1.11/CRDs/ceph-client-crd/) resource? Rook is a great way to integrate Ceph and Kubernetes, even if the Ceph cluster is not in Kubernetes itself - integrating this way seems useful to me.
> 
> ~Having Qemu speak Ceph RBD directly would the big benefit of live migration with RBD volumes - currently this is not possible as they cannot be created `ReadWriteMany`~ - always check your comments before sending them, `Block` mode volumes can in fact be RWX! TIL. Still think this would be a good feature though :D

I think the QSD CSI is still a way to go because of maintainability and having existing integrations(PVC, Backups, ...).

**Comment by alicefr** [comment]
> /reopen /remove-lifecycle rotten
> 
> > QSD would be needed because of the second requirement [in this comment](https://github.com/kubevirt/kubevirt/issues/952#issuecomment-455520614), "However, we can not leak the PV details into the VM Pod, as PV connection details are considered to be pirvate"?
> > What about having this feature only in combination with Rook, using the [`CephClient`](https://rook.github.io/docs/rook/v1.11/CRDs/ceph-client-crd/) resource? Rook is a great way to integrate Ceph and Kubernetes, even if the Ceph cluster is not in Kubernetes itself - integrating this way seems useful to me.
> > ~Having Qemu speak Ceph RBD directly would the big benefit of live migration with RBD volumes - currently this is not possible as they cannot be created `ReadWriteMany`~ - always check your comments before sending them, `Block` mode volumes can in fact be RWX! TIL. Still think this would be a good feature though :D
> 
> I think the QSD CSI is still a way to go because of maintainability and having existing integrations(PVC, Backups, ...).

I am still not sure if this is going to happen. 

The main reason is because ceph CSI plugin only exposes devices or directories. If you want to use directly the rbd protocol then we need to implement it in the plugin and avoid the existing plugin. Otherwise, users need to have already available some pre-provisioned rbd devices that we could expose to QEMU with the CSI QSD plugin. Is that the case here?

**Comment by telmich** [comment]
Some input from running bigger VM infrastructures: One of the key features missing when we look at kubevirt is the ability to leverage "smart choices" when it comes to storage. In typical mid to large scale environments you want a) qemu to talk to ceph directly, avoiding creating hundreds of rbd devices on each host that need to be mapped and unmapped again and b) much more important, you want to be able to thin provision images. 

While the former *might* be solved using rook, as it integrates with CSI and can provide RWX based storage classes, the latter is a big constraint if you have for instance thousands of VMs running of Debian 10, each with only minor modifications, thus saving about 90% storage in the cluster.

**Comment by LittleFox94** [comment]
> Some input from running bigger VM infrastructures: One of the key features missing when we look at kubevirt is the ability to leverage "smart choices" when it comes to storage. In typical mid to large scale environments you want a) qemu to talk to ceph directly, avoiding creating hundreds of rbd devices on each host that need to be mapped and unmapped again and b) much more important, you want to be able to thin provision images.
> 
> While the former _might_ be solved using rook, as it integrates with CSI and can provide RWX based storage classes, the latter is a big constraint if you have for instance thousands of VMs running of Debian 10, each with only minor modifications, thus saving about 90% storage in the cluster.

The second point would already be implemented on the rook (well, actually Ceph) side of things - you'd have a "Debian 10" PVC and create your individual VM PVCs either directly from that volume or from a snapshot of that volume. And since that's no new features and only needs the `layering` image feature in ceph-csi (which is available since Linux 3.10 in KRBD) that already should already be available if configured properly :)
