### ISSUE TITLE
Revisiting timestamp related metrics and alerts in a design doc

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#8920]
**What happened**:
https://github.com/kubevirt/kubevirt/pull/7918/files#diff-0f904f2ae31317b82daba8b2976856da054ce0ff43731afe9a91befa5e2489fd adds timestamp based metrics and also adds alerts for specific types of user-workload centric flows. There was also an intended follow-up https://github.com/kubevirt/kubevirt/pull/8855 which I put on hold.

There are a few concerns about that type of approach:

 * timestamp based metrics are hard to handle in a lot of cases (yes prom allows all kinds of tricks), requiring extra considerations on every query (especially related to #7918)
 * alerts added in #7918 are very opinionated and it is hard for different users or vendors to get rid of those alerts or modify them without changing the actual code. 
 * Alerts in #7918, independent of being configurable or not, may not be generic enough to make sense to be included in core kubevirt
 * #8855 introduces another timestamp metric, seemingly for the intent to get an info about for how long a VMI exists beyond potential retention periods (kind of trying to get long-term storage)

**What you expected to happen**:

We had similar issues on a few metrics related PRs now and I think it is time to address all the above points in a design doc. @sradco I think it makes sense if you drive that design doc, since you are using the metrics in the most diverse fashion and are exposed to a lot of different requests directed to you.

As the outcome it would be great if we can have a path to:

 * expose metrics prometheus friendly
 * don't try to emulate long-term storage but
 * still provide for varying use cases guidance on how to solve issues where long retention periods are required (like suggesting thanos, fetching VMIs directly, ...)

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by sradco** [comment]
Adding @iholder101 , @machadovilaca and @enp0s3. Please see the comments @rmohr made here.
Here are my thoughts about this.

> - timestamp based metrics are hard to handle in a lot of cases (yes prom allows all kinds of tricks), requiring extra considerations on every query (especially related to https://github.com/kubevirt/kubevirt/pull/7918)

I disagree. There are other metrics that are using this approach and we can gap the way to handle them we documentation. Prometheus itself exposes metrics like this one and we made the final decision due to performance considerations. For example `data_pipeline_last_record_processed_timestamp_seconds` from the official [Prometheus documentation](https://prometheus.io/docs/practices/naming/).

> - alerts added in https://github.com/kubevirt/kubevirt/pull/7918 are very opinionated and it is hard for different users or vendors to get rid of those alerts or modify them without changing the actual code.
> - Alerts in https://github.com/kubevirt/kubevirt/pull/7918, independent of being configurable or not, may not be generic enough to make sense to be included in core kubevirt

I agree with the fact that we should deprecate the alerts. They are based on customer setup and might not be valid to all clusters. We can suggest in the UI to inspect the VM/VMIs that are in a specific condition for more than X amount of time. But adding an alert is too opinionated. 

> - https://github.com/kubevirt/kubevirt/pull/8855 introduces another timestamp metric, seemingly for the intent to get an info about for how long a VMI exists beyond potential retention periods (kind of trying to get long-term storage)

I agree that we should not create this metric and a better KPIs can be based on `kubevirt_vm_non_running_status_last_transition_timestamp_seconds` that can help us calculate the average time of running VMIs for the cluster, the max running VMI , etc.

> - expose metrics Prometheus friendly

We made this choice due to performance considerations. Documentation can close the gap of how to use the metrics.

> - don't try to emulate long-term storage but

> - still provide for varying use cases guidance on how to solve issues where long retention periods are required (like suggesting thanos, fetching VMIs directly, ...)

We don't abuse Prometheus for this purpose.
I don't see a difference in having a boolean up/down metric for the VM/VMI condition and the 'last_transition' metrics that also provides us more information about how long they are in this transition.

**Comment by sradco** [comment]
Before creating a design doc, I would like @iholder101 , @machadovilaca and @enp0s3 the chance to also add their thoughts here.

**Comment by rmohr** [comment]
Thanks for the detailed response.

> I agree with the fact that we should deprecate the alerts. They might not be valid to all clusters. We can suggest in the UI to inspect the VM/VMIs that are in a specific condition for more than X amount of time. But adding an alert is too opinionated.

Sounds good. Great!

> I disagree. There are other metrics that are using this approach and we can gap the way to handle them with documentation. Prometheus itself exposes metrics like this one and we made the final decision due to performance considerations. For example `data_pipeline_last_record_processed_timestamp_seconds` from the official [Prometheus documentation](https://prometheus.io/docs/practices/naming/).

This is an interesting example. What you see on this metric is an event. It has not time-range. Like it is not measuring for how long the sync took, it just indicates, "sync done". However that is very different to the metrics we talk about. Let me try to illustrate that below, following up on this comment:

> We don't abuse Prometheus for this purpose.
> I don't see a difference in having a boolean up/down metric for the VM/VMI condition and the 'last_transition' metrics that also provides us more information about how long they are in this transition.

Let's for instance look at a `kubevirt_vm_ready_last_transition_timestamp_seconds` and see  what it means having it:

It may at first look like this properly reflects the `ready` condition, however closely looking it does not. To fully represent the condition like prposed here, we would have 4 interesting data-points:

 1. ready
 1. timestamp when it became ready
 1. not ready
 1. timmestamp when it became unready
 
We can now represent datapoints 1-2 with a `timestamp_seconds` metric: The value is not 0 in this case and the value is the timestamp. We can also represent point 3, by setting this metric to `0`. But since we have to set the metric to `0` we can not represent 4 the same way lik we can represent 2.

There would be two solutions to that for you:

 1. creating another timestamp metric `kubevirt_vm_not_ready_last_transition_timestamp_seconds`
 2. looking at the actual time-series when the metric went back to 0
 
 What are the disadvantages now:
 
 Let's consider we continue with just one metric:
 
  * People have to act on the metric for `not_ready` like if it would not be a timestamp and have to look on the time-series.
  * People can't simply use a `sum()` for getting `ready` counts, can't simply use averages, and so forth.
 
What is the advantage of this:
 
  * they can look on how long a VM was ready (but not not-ready) when the timepoint it became ready is outside of the configured retention period.
  
Now, let's suppose I have a retention period of 3 weeks:

 * Why do I care  if my VM was ready for 6 weeks in general more than just knowing that it was ready for 3 weeks without interruption?
 * Why would I care specifically about `ready`, but not about `not_ready`
 * Why would I not increase the retention period "somehow" to 8 weeks if I care about an 8 week window
 * Why do we think that this is worth complicating more monitoring-related queries?

**Comment by rmohr** [comment]
> We made this choice due to performance considerations. Documentation can close the gap of how to use the metrics.
> 
> >

These performance considerations would for instance be something I would want to see spelled out in the design doc if you think this is the right way to go.

**Comment by sradco** [comment]
> Thanks for the detailed response.
> 
> > I agree with the fact that we should deprecate the alerts. They might not be valid to all clusters. We can suggest in the UI to inspect the VM/VMIs that are in a specific condition for more than X amount of time. But adding an alert is too opinionated.
> 
> Sounds good. Great!

We open an issue for that.
> 
> > I disagree. There are other metrics that are using this approach and we can gap the way to handle them with documentation. Prometheus itself exposes metrics like this one and we made the final decision due to performance considerations. For example `data_pipeline_last_record_processed_timestamp_seconds` from the official [Prometheus documentation](https://prometheus.io/docs/practices/naming/).
> 
> This is an interesting example. What you see on this metric is an event. It has not time-range. Like it is not measuring for how long the sync took, it just indicates, "sync done". However that is very different to the metrics we talk about. Let me try to illustrate that below, following up on this comment:

They are not that different since this metric is probably used to check how long it passed since the last processed record, to identify if there is an issue with getting new records and raise an alert.

Another OpenShift metric example is the `cluster_version` metric https://github.com/openshift/cluster-version-operator/blob/fa8004488fbdc02dc58f004db09c7597c832b2bc/pkg/cvo/metrics.go#L67. Its also reporting the epoch timestamp. Bad metric naming! 
There are many others that report value as the epoch timestamp.

> 
> > We don't abuse Prometheus for this purpose.
> > I don't see a difference in having a boolean up/down metric for the VM/VMI condition and the 'last_transition' metrics that also provides us more information about how long they are in this transition.
> 
> Let's for instance look at a `kubevirt_vm_ready_last_transition_timestamp_seconds` and see what it means having it:

There is no `kubevirt_vm_ready_last_transition_timestamp_seconds` metric..
These are the metrics that were added :
```
kubevirt_vm_error_status_last_transition_timestamp_seconds
kubevirt_vm_migrating_status_last_transition_timestamp_seconds
kubevirt_vm_non_running_status_last_transition_timestamp_seconds
kubevirt_vm_running_status_last_transition_timestamp_seconds
kubevirt_vm_starting_status_last_transition_timestamp_seconds
```
They are based on the conditions.
What metric did you refer to as `ready` ?
Did you mean the `running`? We have `non-running` as well.

> 
> It may at first look like this properly reflects the `ready` condition, however closely looking it does not. To fully represent the condition like prposed here, we would have 4 interesting data-points:
> 
> 1. ready
> 2. timestamp when it became ready
> 3. not ready
> 4. timmestamp when it became unready
> 
> We can now represent datapoints 1-2 with a `timestamp_seconds` metric: The value is not 0 in this case and the value is the timestamp. We can also represent point 3, by setting this metric to `0`. But since we have to set the metric to `0` we can not represent 4 the same way lik we can represent 2.
> 
> There would be two solutions to that for you:
> 
> 1. creating another timestamp metric `kubevirt_vm_not_ready_last_transition_timestamp_seconds`
> 2. looking at the actual time-series when the metric went back to 0
> 
> What are the disadvantages now:
> 
> Let's consider we continue with just one metric:
> 
> * People have to act on the metric for `not_ready` like if it would not be a timestamp and have to look on the time-series.
> * People can't simply use a `sum()` for getting `ready` counts, can't simply use averages, and so forth.

You can use `count()` which will give you the correct result.
For average you can do average over the count().

> 
> What is the advantage of this:
> 
> * they can look on how long a VM was ready (but not not-ready) when the timepoint it became ready is outside of the configured retention period.
> 
> Now, let's suppose I have a retention period of 3 weeks:
> 
> * Why do I care  if my VM was ready for 6 weeks in general more than just knowing that it was ready for 3 weeks without interruption?

> * Why would I care specifically about `ready`, but not about `not_ready`
> * Why would I not increase the retention period "somehow" to 8 weeks if I care about an 8 week window

> * Why do we think that this is worth complicating more monitoring-related queries? ( I understand that they are all still possible in principle)
> 
> Let's now consider the boolean metric:
> 
> There true is `1` and false is `0`, and we get the timestamps in a uniform way. Writing queries is much more straight forward. Also, the fact that we are dealing with a time-period is properly reflected. Everything is fully-consistent and works out of the box like expected. The only "disadvantage" is that I can not see when it became `ready` when it happened already before the retention period (but this is also weird in the previous case, because I would not get `not_ready` when it happened outside of the retention period anyway).

Increasing the retention time impacts the size needed of the db. 
The VMI/VMs can be running for much longer or less then the retention time. The metrics can help with creating `uptime`, `planned downtime`, `unplanned downtime` which are important KPIs for a cluster. 
This was also requested by the RHV users in the past.

I don't see this as misusing Prometheus. The metric name clearly states what it means and the way to use it is not that complicated.
Doing `time()-metric` provides the time in seconds the VM/VMI is in that condition.
Doing `count by (vm name)(metric)` allows you to get the number of VM/VMIs for each condition and graph them over time.

This implementation helps the users to identify problematic VM/VMIs (We are only interested with the existing VM/VMIs) based on the time the VM/VMI is in that condition.
I understand it might feel a but more complicated, but we had to choose how to report the metrics:
- As transition timestamp
- Calculate the time from transition and report it in second
We agreed that the first option is the convention and most efficient.

And in fact as I written above, the actual use of the metric is not that complicated and users will use other metrics like this in other operators. So I don't think it should be a consideration.

**Comment by enp0s3** [comment]
Hello

> 
> There are a few concerns about that type of approach:
> 
> * timestamp based metrics are hard to handle in a lot of cases (yes prom allows all kinds of tricks), requiring extra considerations on every query (especially related to [Add alerts for VMs unhealthy states #7918](https://github.com/kubevirt/kubevirt/pull/7918))

I couldn't find a reference that suggests to avoid using timestamp based metrics when possible. So I understand that
the complexity of the evaluation is a concern here. I think that this concern was already raised as part of #7918 discussion, and we decided to embrace the complexity in favor to the long-term storage emulation. And now since there is a concern about the need for this storage emulation (it probably can be done outside of kubevirt core), there is also
a concern whether we need to use timestamp. I can see the rationale behind creating a design doc in order to make that decision clear for everyone, and also argue about that.

> * alerts added in [Add alerts for VMs unhealthy states #7918](https://github.com/kubevirt/kubevirt/pull/7918) are very opinionated and it is hard for different users or vendors to get rid of those alerts or modify them without changing the actual code.
> * Alerts in [Add alerts for VMs unhealthy states #7918](https://github.com/kubevirt/kubevirt/pull/7918), independent of being configurable or not, may not be generic enough to make sense to be included in core kubevirt

I am all for decouple user-workload monitoring from the kubevirt core, perhaps moving it to a dedicated repo,
leaving only the generic metrics and alerts of the core control-plane components.

> * [Add VMI creation timestamp metric #8855](https://github.com/kubevirt/kubevirt/pull/8855) introduces another timestamp metric, seemingly for the intent to get an info about for how long a VMI exists beyond potential retention periods (kind of trying to get long-term storage)
> 
> **What you expected to happen**:
> 
> We had similar issues on a few metrics related PRs now and I think it is time to address all the above points in a design doc. @sradco I think it makes sense if you drive that design doc, since you are using the metrics in the most diverse fashion and are exposed to a lot of different requests directed to you.
> 
> As the outcome it would be great if we can have a path to:
> 
> * expose metrics prometheus friendly

I think this is expected from metrics and alerts of kubevirt core. I think that for opinionated user-workload monitoring
we can use some more complicated solutions if needed, and this opinionated monitoring to be placed in a separate repo.
