### ISSUE TITLE
admin_pass set in metadata with  NoCloud

### ISSUE THREAD

**Issue by yuntianfeijing** [kubevirt/kubevirt#8923]
**What happened**:
When I create a Windows VM,  The passwd parameter does not work for default user: Admin, the real password is random. From the cloudbase init document, I should set admin_pass in metadata, Whether to provide a way for users to set metadata ？

**What you expected to happen**:

userdata in vm:
```
#cloud-config
set_timezone: Asia/Shanghai
users:
  -
    name: Admin
    passwd: StrongPassw0rd
```

cloudbase-init version: 1.1.2
cloudbase-init.conf:
```
[DEFAULT]
username=Admin
groups=Administrators
inject_user_password=true
bsdtar_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\bsdtar.exe
mtools_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\
verbose=true
debug=true
log_dir=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log\
log_file=cloudbase-init.log
default_log_levels=comtypes=INFO,suds=INFO,iso8601=WARN,requests=WARN
logging_serial_port_settings=COM1,115200,N,8
mtu_use_dhcp_config=true
ntp_use_dhcp_config=true
local_scripts_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\LocalScripts\
user_password_length=10
retry_count=1
retry_count_interval=3
netbios_host_name_compatibility=false
san_policy=OnlineAll
first_logon_behaviour=no
metadata_services=cloudbaseinit.metadata.services.nocloudservice.NoCloudConfigDriveService,cloudbaseinit.metadata.services.configdrive.ConfigDriveService
[config_drive]
raw_hdd=true
cdrom=true
vfat=true
```

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): A
- Kubernetes version (use `kubectl version`): A
- VM or VMI specifications: A
- Cloud provider or hardware configuration: A
- OS (e.g. from /etc/os-release): A
- Kernel (e.g. `uname -a`): A
- Install tools: A
- Others: A

**Comment by usrbinkat** [comment]
I'm not sure that we have any [cloud
ase-init](https://cloudbase-init.readthedocs.io/en/latest/config.html#config-drive) expertise to assist here, however if I were to take a guess at best first steps I would make sure the VirtualMachine definition user-data is set to type `cloudinitConfigDrive` and attached as disk type `cdrom` so that the cloudbase-init process in your customized windows image will correctly detect the supplied config.

After that, it would be a matter of collecting logs to identify whether that config is correctly discovered and if it is still failing see if there are any logs indicating why.
