### ISSUE TITLE
"VM defined" event is sent on every successfull VirtualMacine sync in virt-handler

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#894]
Instead of being just triggered when we define a domain in libvirt, we send the event on every successfull sychronization loop between virt-handler and virt-launcher:

```
  Type    Reason   Age                From                                                 Message
  ----    ------   ----               ----                                                 -------
  Normal  Created  9m (x135 over 1d)  virt-handler, kubevirtdemo  VM defined.
```

**Comment by fabiand** [comment]
Setting critical urgent, not because it's criticsl, rather that it should be fixed quick in order to make the describe command cleaner

**Comment by slintes** [comment]
I'm wondering why https://github.com/kubevirt/kubevirt/pull/895 was closed?

Or: what exactly should be done for resolving this issue?

- do we want an event on every sync, but with a better message?
- or do we want an event only when a new domain is defined?

@fabiand @rmohr ?

**Comment by rmohr** [comment]
> I'm wondering why #895 was closed?

@slintes I just closed it because I could not get back to it and the proposed solution is not correct. Removing the events (which I did in the PR) is not correct. We want to only send the events once when they actually happen.

**Comment by slintes** [comment]
ok, thanks for clarification.

So the solution would be to check the VMI and the domain, and only send the event when the sync results in a domain definition.

**Comment by rmohr** [comment]
Yes that is one possibility. Note that we then will have to indroduce expectation management like we do in the controllers, so that we can properly wait for creations. Another option is to exchange event type, message and level as part of the rpc call between virt-handler and virt-launcher.

**Comment by slintes** [comment]
Note to developer:

While the initial reason for this issue is "only" about a sending a wrong kubernetes event, the story is a bit more complex, and we want to improve the whole story.

The story is:

- at the moment we are sending a "VirtualMachineInstance defined" event from `virt-handler` right after sending a `sync` command to  `virt-launcher`, see https://github.com/kubevirt/kubevirt/blob/73edb2f175fd7b7c7d8595c032696823f47c2dd6/pkg/virt-handler/vm.go#L580
- the first and obvious problem here is: not every sync results in a domain definition
- but even if we would take the domain we got from the cache (https://github.com/kubevirt/kubevirt/blob/73edb2f175fd7b7c7d8595c032696823f47c2dd6/pkg/virt-handler/vm.go#L311) into consideration for determining what really happened, that would not be accurate, because the actual domain can be in another state in the meanwhile. And guessing what happened seems to be a bad idea at all.

So the best solution would be to send events when we know what really happened. Unfortunatly we don't have that information yet in `virt-handler`, only `virt-launcher` knows which libvirt command(s) were actually executed during a sync. In order to get this information into `virt-handler`, we want to extend the the rpc calls between these 2 components, so that `virt-launcher` returns enough information about what it did, so that `virt-handler` can send the correct events.

In order to implement this, you need to extend

- `virt-launcher`'s rpc command server (https://github.com/kubevirt/kubevirt/blob/73edb2f175fd7b7c7d8595c032696823f47c2dd6/pkg/virt-launcher/virtwrap/cmd-server/server.go#L56) : additionally to the error, return a new struct which contains enough information about what was done, so that this information can be used for the k8s events
- `virt-handler`'s rpc command client (https://github.com/kubevirt/kubevirt/blob/73edb2f175fd7b7c7d8595c032696823f47c2dd6/pkg/virt-handler/cmd-client/client.go#L184): use the new struct from the response for sending k8s events.
