### ISSUE TITLE
Avoid setting security contexts on pods when they are needed only by 1 container

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#8968]
There is at least one instance, introduced by https://github.com/kubevirt/kubevirt/pull/8649, of us setting a more relaxed security context than the default one on an entire pod instead of the specific container(s) that need it.
We should instead set the security context on the container that needs it to keep the rest of the pod unaffected.

**Comment by AbdelrahmanElawady** [comment]
Hi I am interested in fixing this issue. if there is no one working on it can I get assigned?

**Comment by AbdelrahmanElawady** [comment]
If I understand your comments on #8649 the problem is with the `templateService` applying a security context on the pod itself not the containers, but looking at the `rendercontainer.go` file [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/rendercontainer.go#L56) for example the security context for all containers gets set according to the vmi specs, also for disk containers, kernel boot containers and sidecar containers. except for virtio containers they always run as root. so since all containers get assigned a security context doesn't that just override the pod security context as mentioned [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)? or did I misunderstand the issue?

**Comment by jean-edouard** [comment]
> If I understand your comments on #8649 the problem is with the `templateService` applying a security context on the pod itself not the containers, but looking at the `rendercontainer.go` file [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/rendercontainer.go?rgh-link-date=2023-03-03T14%3A13%3A30Z#L56) for example the security context for all containers gets set according to the vmi specs, also for disk containers, kernel boot containers and sidecar containers. except for virtio containers they always run as root. so since all containers get assigned a security context doesn't that just override the pod security context as mentioned [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)? or did I misunderstand the issue?

Hi @AbdelrahmanElawady ! You got all that right, but for what you looked at, can't we then remove the pod security context?
It's also worth looking at other pods than virt-launcher.
Please keep in mind that it is possible that everything is already correctly done! I should have titled this "Ensure we don't set a relaxed security context on a pod that has containers that could run with stricter defaults" or something like that.
I hope that helps, and thank you for looking at this!

**Comment by AbdelrahmanElawady** [comment]
I looked at the other templates and they all use security context at container level. only the virt-launcher uses both at container level and pod level. I am not really sure if pod security context is needed here because for all containers other than virtiofs they have similar context to the pod one except for the seccomp profile. so if just having a security context at container level overrides the pod one then I think it's not needed. but if it's just overrides the pod security if there is overlap then the seccomp profile for example would need to be added to each container? if it just overrides then I think it can be removed but I am not sure.

**Comment by jean-edouard** [comment]
> @jean-edouard I also need some clarifications :). Do we want to rely on k8s defaults and not set the security context when it is possible?

I'd say yes unless what we're setting is less permissive than the defaults.
