### ISSUE TITLE
prevent rsync error in make

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#898]
add ```sleep``` in line 35 of https://github.com/kubevirt/kubevirt/blob/master/hack/dockerized
to prevent from following error when running ```make```:
```
rsync: safe_read failed to read 1 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.3]
```

**Comment by rmohr** [comment]
Hm, I think it is better to give fsync a timeout. E.g. 15 seconds and until then swallow the whole error output. Then do a final run and output the error. It greatly varies from run to run and host speed how  fast rsyncd is ready to accept connections (can actually take a few seconds and I don't want to delay the run for everyone).

**Comment by rmohr** [comment]
We can also give it 30 seconds, then it is for sure enough. I think that within that timeout we should redirect  to /dev/null. If it is then still not ready, we should try once again and print the result to sterr, so that people can see that something is wrong. Otherwise it would just hang forever without any output.
