### ISSUE TITLE
Avoid running CI tests when it is not necessary

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#9013]
In `kubevirt/kubevirt` we have a pretty massive CI system.

Currently, the CI system executes many tests on each PR, even in cases when it is not necessary. For example, when changing:
* Comments
* Non-code files (e.g. `.md` files)
* A commit message

Our CI often suffers from being overloaded, causing lanes to be flakie and hurts our overall project.
IMHO, we should find a way to avoid running CI, or at least reduce the number of lanes that are being run in unnecessary scenarios.

**Comment by EdDev** [comment]
There is a need to define some goals to this issue, otherwise it becomes hard to threat it.

Latest work done in this direction encountered resistance [here](https://github.com/kubevirt/kubevirt/pull/10019).

To raise awareness and start a deeper discussion on this matter, perhaps a design proposal can be started, describing there all options with possible PoC and work plans.

**Comment by oshoval** [comment]
Please see https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759
I think we can save precious time meanwhile with MVP, personally i am not interested to dedicate time extending the plugins, it is not our core business logic, and prone for weird corner cases as the link says.

**Comment by EdDev** [comment]
I think the concrete suggestion presented is good enough to be accepted.
The do not understand the resistance to it, especially when there is nothing else concrete to offer.

Having a design & discussion is always better, but I recognize it is not always easy and in a priority.

**Comment by iholder101** [comment]
Looking at https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759, seems that they recommended using `run_if_changed` and `skip_if_only_changed` combination to avoid running CI when only non-code files change. IIUC, @oshoval's current solution only addresses the non-code file changes scenario, so why not take their suggestion and implement in with prow settings? This is also what @dhiller suggested in [his comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1619972260).

What I want to understand is how difficult would it be to implement it in the right way. Temporary workarounds (which are by definition a technical debt) are sometimes acceptable, but there's a need for a strong justification in order to use them, and to know when and how they can be removed in the future.

@dhiller @brianmcarey would you be able to look into this again and try to think about the necessary steps / sub-tasks in order to get this working the right way? Once we know exactly what needs to be done it would be easier to asses how difficult it would be. I'd say that a temporary workaround is acceptable only if we see that the steps forward are either not possible at the moment or would demand too much effort that no one can invest now. On the other hand, if this is not a huge effort to invest and can be done in a reasonable amount of time, I'd say that a temporary workaround won't be worth it.

After you're done, I can add a check-list of the things need to be done to this issue.
Also, if you find it complicated enough, we can start a design proposal, although I'm not sure that's necessary.

**Comment by oshoval** [comment]
> Looking at https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759, seems that they recommended using `run_if_changed` and `skip_if_only_changed` combination to avoid running CI when only non-code files change. IIUC, @oshoval's current solution only addresses the non-code file changes scenario, so why not take their suggestion and implement in with prow settings? This is also what @dhiller suggested in [his comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1619972260).

Because one would need to add it in each and every job, and for each change need to update them all.
It also depends on the current label that do exists etc (but we might covered this issue already on the linked PR).

> 
> What I want to understand is how difficult would it be to implement it in the right way. Temporary workarounds (which are by definition a technical debt) are sometimes acceptable, but there's a need for a strong justification in order to use them, and to know when and how they can be removed in the future.

Right but on the other hand a MVP that saves time meanwhile, when the good solution might take months (or even if it wont take months), is totally fine to have, and the right thing to do imho.

**Comment by iholder101** [comment]
> > Looking at https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759, seems that they recommended using `run_if_changed` and `skip_if_only_changed` combination to avoid running CI when only non-code files change. IIUC, @oshoval's current solution only addresses the non-code file changes scenario, so why not take their suggestion and implement in with prow settings? This is also what @dhiller suggested in [his comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1619972260).
> 
> Because one would need to add it in each and every job, and for each change need to update them all. It also depends on the current label that do exists etc (but we might covered this issue already on the linked PR).

Perhaps there's a way to re-use the same rule for many jobs?

> > What I want to understand is how difficult would it be to implement it in the right way. Temporary workarounds (which are by definition a technical debt) are sometimes acceptable, but there's a need for a strong justification in order to use them, and to know when and how they can be removed in the future.
> 
> Right but on the other hand a MVP that saves time meanwhile, when the good solution might take months (or even if it wont take months), is totally fine to have, and the right thing to do imho. Moreover it is such small change that can be removed easily which worth to consider.

If this effort would really be that big, then it's very reasonable to consider a temporary workaround IMO.
As said before, I think that the first thing needs to be done is to asses which tasks need to be done and how much effort they demand.

**Comment by oshoval** [comment]
> > > Looking at https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759, seems that they recommended using `run_if_changed` and `skip_if_only_changed` combination to avoid running CI when only non-code files change. IIUC, @oshoval's current solution only addresses the non-code file changes scenario, so why not take their suggestion and implement in with prow settings? This is also what @dhiller suggested in [his comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1619972260).
> > 
> > 
> > Because one would need to add it in each and every job, and for each change need to update them all. It also depends on the current label that do exists etc (but we might covered this issue already on the linked PR).
> 
> Perhaps there's a way to re-use the same rule for many jobs?

maybe, anchor and preset remind this, not sure but by heart if there is already something suitable for it

> 
> > > What I want to understand is how difficult would it be to implement it in the right way. Temporary workarounds (which are by definition a technical debt) are sometimes acceptable, but there's a need for a strong justification in order to use them, and to know when and how they can be removed in the future.
> > 
> > 
> > Right but on the other hand a MVP that saves time meanwhile, when the good solution might take months (or even if it wont take months), is totally fine to have, and the right thing to do imho. Moreover it is such small change that can be removed easily which worth to consider.
> 
> If this effort would really be that big, then it's very reasonable to consider a temporary workaround IMO. As said before, I think that the first thing needs to be done is to asses which tasks need to be done and how much effort they demand.

Right, but i see it in other way, this issue is from January, and the design can take time,
either because people are busy or it is deep, and there are such cases where we put tech-debt as priority and forget about MVP, when it is not the right thing to do, and this is one of those cases imho.
If we encourage in some situations a MVP when the signal to noise worth it we can save hours.
But now all is said already from our both sides, this is my 2 cents.

**Comment by EdDev** [comment]
> Looking at https://kubernetes.slack.com/archives/CDECRSC5U/p1689496532563759, seems that they recommended using `run_if_changed` and `skip_if_only_changed` combination to avoid running CI when only non-code files change. IIUC, @oshoval's current solution only addresses the non-code file changes scenario, so why not take their suggestion and implement in with prow settings? This is also what @dhiller suggested in [his comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1619972260).

Because it does not work for required jobs.

We are basically going no-where with this.
The members who invested in this have come out with this solution, no one else could find a better solution or did not have time to invest in this further.

Either way, if no one volunteers to work on it now, please focus on what is available now.
It is fine to nack a solution, but it needs to have a good reasoning.
The reasoning I saw until now are focus on finding something better, but as said before, no one found anything else and no one is actively working on it.

**Comment by iholder101** [comment]
Since I see that indeed no one can come up with better solutions, I'm OK with getting this in.

However, please @oshoval create an issue to track the missing parts and to remind us to keep investigating this in the future.

@lyarwood @dhiller @brianmcarey - any objections?

**Comment by oshoval** [comment]
There is this issue, we can just update the PR desc with the ref to the PR on the specific bullet 
wdyt ?

**Comment by oshoval** [comment]
i meant the issue (but i will update the PR)
can you please update the issue with ref to the PR for the specific bullet ? only you have edit permissions

**Comment by iholder101** [comment]
> i meant the issue (but i will update the PR) can you please update the issue with ref to the PR for the specific bullet ? only you have edit permissions

Sure. I will update the issue if there are no objections

**Comment by dhiller** [comment]
Referring to [this comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1669376591)
@brianmcarey and me would like to investigate changing tide configuration so that we can leverage `skip_if_only_changed` which is exactly what we want.

But for this we do need to research and test, this will take a bit of time.

As stated in the above comment, I think the PR is not worth merging since it currently adds a burden to all PRs while saving only on an estimated 1/20 PRs.

**Comment by oshoval** [comment]
> Referring to [this comment](https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1669376591) @brianmcarey and me would like to investigate changing tide configuration so that we can leverage `skip_if_only_changed` which is exactly what we want.
> 
> But for this we do need to research and test, this will take a bit of time.
> 
> As stated in the above comment, I think the PR is not worth merging since it currently adds a burden to all PRs while saving only on an estimated 1/20 PRs.

about the burden, i think i can remove the `git fetch`
https://github.com/kubevirt/kubevirt/pull/10019/files#r1266720195
if this what will make this PR be merged please let me know
ref https://github.com/kubevirt/kubevirt/pull/10019#issuecomment-1669382138

**Comment by brianmcarey** [comment]
@iholder101 I believe we can close this issue since this was merged - https://github.com/kubevirt/kubevirt/pull/11147
