### ISSUE TITLE
Change source code folder from kubevirt-0.4.1 to kubevirt-v0.4.1

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#919]
After download the tar.gz file from https://github.com/kubevirt/kubevirt/releases and extract it, the folder name like below:

```
kubevirt-0.4.1                                             
kubevirt-0.4.1-alpha.1 
```
I notice there a small problem in kubevirt-ansible, it's using `v{{ version }}` in
https://github.com/kubevirt/kubevirt-ansible/blob/857bf53094db020c885933d3f72ac2fa4b1be095/roles/kubevirt/tasks/provision.yml#L35, it works but not good when consider code readability. I suggest to change the folder name to `kubevirt-v0.4.1`, so it can use variable `{{ version}}` everywhere.
 
All versions on the release page have the character `v`, like `virtctl-v0.4.1-linux-amd64`, `v0.4.1`, so it seems reasonable to change it.

**Comment by rmohr** [comment]
I don't think that we are responsible for that. Github generates these archives, and skips the `v`. So if we create a release with a tag `v4.0.1`, the archive will contain a top-level directory called `kubevirt-4.0.1`.

The only thing which can be influenced, is how the tar.gz archive itself is named. E.g.

```
curl -O -L https://github.com/kubevirt/kubevirt/archive/v0.4.1.tar.gz#/test,tar.gz
```

would download an archive called `test.tar.gz` instead of `kubevirt-0.4.1.tar.gz`.

**Comment by gouyang** [comment]
Thanks for the explanation, I'm not aware of that it's github's work.
