### ISSUE TITLE
Add test which checks if virtctl works with auth plugins

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#933]
Follow up of #929. We should have a basic check which makes sure that our websockets console streams work for auth plugins (e.g. open id).

**Comment by rmohr** [comment]
@mlsorensen FYI

**Comment by mlsorensen** [comment]
Yeah, that's something to think about. I suppose that requires the test environment to set up a cluster that has this sort of authentication enabled.

**Comment by fabiand** [comment]
@mlsorensen do you have an example of where the support is needed i.e. with which plugin?

**Comment by mlsorensen** [comment]
If you're using OIDC tokens to authenticate to your cluster, then virtctl needs to be OIDC enabled in order for the api calls it makes to the subresources for /vnc and /console to work. The change in #929 causes virtctl to inherit the work that kubernetes does in this regard for kubectl.

This allows virtctl to work with Kubernetes installations that might be using authentication like CoreOS Dex, Google or Azure clusters.  For testing, we could spin up an auth provider and configure the test cluster with it (say UAA), use a known static auth provider, or perhaps look into how Kubernetes project is testing the code doing this work.  

My initial thinking was that since this change was merely an import from another project, the other project's testing would suffice. There are no new units to test in virtctl. However, I can understand the desire to validate that the upstream code is working as expected.

https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens

**Comment by rmohr** [comment]
@gouyang is that something which you guys have on the list for testing?
