### ISSUE TITLE
Live migration not working with custom migration network and pod network in bridge mode and fixed IP

### ISSUE THREAD

**Issue by xagent003** [kubevirt/kubevirt#9440]
Using Calico as the CNI. For VMs, we're handling IP allocations by creating a special IPPool for Calico and assigning the VMs a fixed IP via annotation, for example:

```
      annotations:
        'cni.projectcalico.org/ipAddrs': '["10.99.99.97"]'

```
Now VM (and virt-launcher Pod) has same IP regardless of node placement. I don't want to use masquerade mode because VM doesnt have actual IP configured inside, and of extra NAT and two VMs talking on same Pod network would be NAT'd. So we want bridge mode.

I followed steps here mostly to a tee: https://kubevirt.io/user-guide/operations/live_migration/#using-a-different-network-for-migrations

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: migration-network
  namespace: kubevirt
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "migration-bridge",
      "type": "macvlan",
      "master": "vlan300",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.1.1.0/24"
      }
    }'
```

kubectl edit'd the Kubevirt CR in -n kubevirt:

```
        migrations:
          network: migration-network
```

I expect the VM to now be migrateable with interface on pod network as bridge: {} but it still shows:

```
NAME              AGE    PHASE     IP            NODENAME      READY   LIVE-MIGRATABLE   PAUSED
vmcalicobridge2   110s   Running   10.99.99.97   10.240.0.34   True    False             
```

How would we get live migration working in this case?

**Comment by maiqueb** [comment]
This might be a stupid question, but did you enable the feature gate ? https://kubevirt.io/user-guide/operations/live_migration/#enabling-the-live-migration-support

**Comment by EdDev** [comment]
@xagent003 , there has been no response on this issue for a few months now.

To the content itself, the VMI is not migratable when the primary network (the pod network) is non-masquerade.
The fact that the migration datapath is done though a secondary multus network, is related to the virt-handler component and relates to the data passed in the migration itself.
KubeVirt does not allow live-migration when the VMI interface uses bridge binding because we cannot assure the IP in the guest is updated.
While in the scenario you are raising now it makes sense, because you assure the IP is sticky using the IPAM provider, we cannot depend on that to open this for other scenarios. I.e. we try to limit the dependency on network providers and CNI/s. 

Said that, an initiative to try and extract out network logic out of core kubevirt is starting.
This may allow individuals to integrate external bindings and logic.
I guess we can consider this migration customization as well, allowing the "plugin" to allow or disallow it.

If there is anything else you would like to ask, please let me know.
We will close this issue in a few days if there will be no response, but it can be re-open if needed.

/assign

**Comment by EdDev** [comment]
In continuation to the previous message, I am closing this issue.

/close
