### ISSUE TITLE
Bug: Upgrade might no be complete

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#9469]
**What happened**:
The upgrade path described https://kubevirt.io/user-guide/operations/updating_and_deletion/#updating-kubevirt-control-plane as 
"By changing the imageTag value in the KubeVirt CR's spec." may lead to not all changes being deployed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by shivangnayar-crypto** [comment]
deploying a new KubeVirt manifest with the updated image tag might solve the problem

Because changing the imageTag value in the KubeVirt CR's spec only updates the KubeVirt control plane image and not the entire KubeVirt deployment. As a result, any changes made to the KubeVirt deployment (such as changes to the Kubernetes manifests or the configuration files) will not be reflected in the updated deployment.
