### ISSUE TITLE
Move to libvirtd 3.9

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#956]
Currently we are using libvirt 3.7.

In order to stay closer to what is state of the art we should consider moving to 3.9:

https://www.redhat.com/archives/libvirt-announce/2017-November/msg00001.html

**Comment by fabiand** [comment]
@stu-gott @rmohr should some image get updated to pull in a new version? 

Or in other words: How often do we updat ethe libvirt base image?

**Comment by rmohr** [comment]
@fabiand https://github.com/kubevirt/libvirt needs to be rebuilt. Once that succeeds we can update the libvirt base image in the codebase here.

**Comment by nertpinx** [comment]
You might just as well update to 4.4.0 that was released on Monday. Upstream using upstream might make sense. If you are not sure you want the latest one (which, for libvirt, I don't see why that coudln't be updated regularly), then at least consider using virt-preview repository for the latest fedora. I can send a PR for the update, but I'm not sure if there are more steps needed.

**Comment by rmohr** [comment]
I am skeptical about going with upstream releases. For as long as we don't need features from there I would actually prefer to go with the latest centos/rhel releases, since as far as I can tell that will be much close with what people normally use in their production environments.

**Comment by nertpinx** [comment]
Sure, on the other hand this is upstream kubevirt. And with more upstream libvirt releases you get more fixes. And since that is used pretty much on all fedora workstations, staying more than 1 or 2 releases behind upstream due to "possible bugs" is usually pointless. I say "usually" because every now and then there is bug everywhere and I don't want to make someone to just go with it unconditionally. There should always be some decision process on whether to update to newer release.
Maybe that is just because I feel it the other way. Unless there are known issues in a release (which are not back-ported to maintenance branches) newer releases give you fixes for bunch of "hard to identify" bugs where you dig deep to find out what happens why and it's just fixed in some newer release. We also have that virt-preview repo due to similar reasons, there are features or fixes that lot of people want faster than what's the downstream release schedule of an OS.
But I'm not trying o advocate either way, if you prefer older version, there are three other possibilities to go with, let me know which one would you prefer:
- fedora 27 w/o virt-preview: libvirt-3.7.0
- fedora 27 w/ virt-preview: libvirt-4.0.0
- fedora 28 w/o virt-preview: libvirt-4.1.0
- ~~fedora 28 w/ virt-preview: libvirt-4.2.0~~

For 3.9.0 you'd need to go with RPMs built upstream which you probably don't want at all. Above data was gathered using the following one-liner:
```
for i in 27 28; do docker run -it fedora:$i sh -c "dnf info libvirt; curl --output /etc/yum.repos.d/fedora-virt-preview.repo https://fedorapeople.org/groups/virt/virt-preview/fedora-virt-preview.repo; dnf info libvirt"; done
```

**Comment by stu-gott** [comment]
I too feel that consuming upstream might be a bit aggressive. Testing KubeVirt against what could reasonably be considered "production" makes more sense. Obviously being several months behind isn't great either.

To address @fabiand's question directly, perhaps evaluating our dependencies should be part of the release process--or more specifically, should we update deps after a release?

**Comment by rmohr** [comment]
> fedora 27 w/o virt-preview: libvirt-3.7.0

I would prefer if we switch to centos as base. It contains 3.9. I think centos/rhel shipped versions is what normally is used in production.

I think we should aim for production-ready quality on every release, no matter if upstream or downstream. Targetting with our upstream tests well known libvirt/qemu versions would be one part of it.

Regarding to regular updates: E.g. weekly updating the libvirt image on the centos base would work for me.

**Comment by nertpinx** [comment]
That makes perfect sense. I haven't thought of switching the base image distro. Probably my mind was not open-minded enough.
Switching to CentOS image makes it also easy in a way since the `FROM centos:latest` doesn't need to be updated. Let me know if that is OK for the update.

**Comment by fabiand** [comment]
Our version indicates that we are in heavy development and we are also working with the libvirt team to consume features they develop. Thus for the time being we should stick to fedora to keep getting the "most recent" (packaged) versions.

Once we do have stable branches, then I think it's worth choosing centos as a base.

**Comment by rmohr** [comment]
We use libvirt 4.2 right now.

/close
