### ISSUE TITLE
VM's can be deleted regardless of the state of the VM

### ISSUE THREAD

**Issue by sudharsanomprakash** [kubevirt/kubevirt#9580]
**What happened**:
 I was able delete running Virtual Machine.

**What you expected to happen**:
Not to delete a running VM and expected to return error like, "VM is running and cannot be delete"

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a VM
kubectl delete vm vmname

**Additional context**:
It is Ok for running VMI getting deleted as it will be re-deploy from VM object. But running VM object should be disallowed from deleting?

**Environment**:
- KubeVirt version (use `virtctl version`): Server Version: version.Info{GitVersion:"v0.58.0", GitCommit:"6e41ae7787c1b48ac9a633c61a54444ea947242c", GitTreeState:"clean", BuildDate:"2022-10-13T00:33:22Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by usrbinkat** [comment]
@sudharsanomprakash Thanks for raising this.

The current pattern is consistent with general Kubernetes pod lifecycle behavior. Is there a specific reason that might warrant a deviation from the established kubernetes pattern which you are looking to resolve?

**Comment by sudharsanomprakash** [comment]
The current pattern works fine with VMI resources as it will be re-deploy from VM definition irrespective of VM state. But if VM resource is deleted it won't redeploy. It would be better if delete operation on a VM resources can only be performed if VMI resource is not running or failed status. It prevents accidental delete of VM. 

Is that acceptable or am I missing something ? 🤔

**Comment by usrbinkat** [comment]
Because Kubernetes is a state controller and operates on Custom Resource Definitions (CRD) with individual custom resource objects per VM, this type of "delete protection" pattern does not conform to the kubernetes API and custom resource lifecycle.

If you are looking for safer change control for VM creation, termination, and deletion, a GitOps pattern or other DevOps approach may be the best path forward to reduce the risks of human error. In a GitOps scenario for example, you would create/delete VMs via pull request to your infrastructure as code repository where VMs are defined in yaml, terraform, pulumi, or other iac implementation and human actions against the kubernetes api itself could be reduced or eliminated. You could restrict user accounts from having delete privileges for example to prevent un-controlled delete activities.

**Comment by sudharsanomprakash** [comment]
Agreed. Thank you @usrbinkat
