### ISSUE TITLE
[code refactor] Remove mitchellh/go-ps library

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#9671]
**Is your feature request related to a problem? Please describe**:
We use the library [github.com/mitchellh/go-ps](https://github.com/mitchellh/go-ps) to get qemu process information in [isolation](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/isolation/isolation.go). The library doesn't get updated since Nov 2020, we could avoid using it and reimplement this part in isolation.

**Comment by dharmit** [comment]
@alicefr I'd like to pick this up if I can get some help with basic/silly/naive/dumb questions I'd be throwing along the way. Can I pick it up?

**Comment by alicefr** [comment]
/assign dharmit

Sure, feel free to ask any question here or in the slack channel

**Comment by shekhar-chauhan** [comment]
So, do we just remove 
`ps "github.com/mitchellh/go-ps"`
Or, currently is it being used and we've to modify accordingly ?

**Comment by dharmit** [comment]
@alicefr thanks.

> we could avoid using it and reimplement this part in isolation.

IIUC, we only need the part of original repo which is in [`process_unix.go`](https://github.com/mitchellh/go-ps/blob/master/process_unix.go#L50-L90) because [KubeVirt runs only on Linux hosts](https://kubernetes.slack.com/archives/C0163DT0R8X/p1681895788556759?thread_ts=1681895728.505019&cid=C0163DT0R8X). WDYT?

**Comment by alicefr** [comment]
@dharmit yes, KubeVirt is only supported on linux host
