### ISSUE TITLE
Limits issue?

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#970]
Currently, it seems memory for the VM is created via the 'spec.domain.resources.requests' field. The limit for the virt-launcher pod seems to come from the namespace default (kubectl get limits default). If the default limits are lower than the requests, the virt-launcher pod does not create.

Reproduce: "kubectl edit limits default", set memory to 128Mi, then try to create a VM with 1Gi of memory.

I propose that the virt-launcher pod's 'spec.domain.resources.limits.memory' be set to the request field. It seems the VM is already slightly less than the request, so hopefully there's enough buffer in the pod for running bash or whatever else might be needed, but there may need to be additional buffer accounted for in this number.

Alternatively, change the memory field to come from the limit rather than the request, in which case kubernetes will automatically populate the request field to match.

Likewise, it seems like setting CPU via spec.domain.cpu.cores does not change the virt-launcher's CPU request/limit beyond the namespace default. This may be by design, for example one could create an 8 core VM that is throttled down to 100m CPU time, but I'm not sure.

**Comment by vladikr** [comment]
> Likewise, it seems like setting CPU via spec.domain.cpu.cores does not change the virt-launcher's CPU request/limit beyond the namespace default. This may be by design, for example one could create an 8 core VM that is throttled down to 100m CPU time, but I'm not sure.

Hi,

Yes, absolutely. The spec.domain.cpu.cores setting only controls the cpu topology of the vm, as it will be seen by the guest OS. Currently, we are only presenting 1 socket with X cores and 1 thread.
Please see [1]
The number of physical CPUs that the VM will run on can be requested using the spec.domain.resources.requests.cpu as in [2]

> Currently, it seems memory for the VM is created via the 'spec.domain.resources.requests' field. The limit for the virt-launcher pod seems to come from the namespace default (kubectl get limits default). If the default limits are lower than the requests, the virt-launcher pod does not create.

Thanks, I wasn't aware of this, let me look into it. 
On the other hand, memory limits can set using the  spec.domain.resources.limits.memory as in [2], does it solve the problem?

> It seems the VM is already slightly less than the request, so hopefully there's enough buffer in the pod for running bash or whatever else might be needed, but there may need to be additional buffer accounted for in this number.

We are accounting a memory overhead, please see [3] and [4]. There is an ongoing effort to improve this and suggestions are welcome :)

I think the reason for less memory being presented in the guest OS is because of the kernel memory reservations.

[1] http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=cpu
[2] http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=resources-requests-and-limits
[3] http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=memory-overhead
[4] https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-controller/services/template.go#L255

**Comment by mlsorensen** [comment]
Yes, explicitly setting a limit works, and should be fine if there's overhead built-in. This means users who have low defaults have to always specify both memory requests and memory limits to the same value (or limit higher than requests). It works but is a bit unintuitive to users who are simply thinking in terms of "how do I set the VM's RAM".

On the one hand I could see kubevirt ensuring the memory limit is at least the request for virt-launcher pod, to avoid failures that might not be easy for the end user to figure out.  I can also see the limit and request being used to set initial and max RAM for a VM with memory ballooning, but I guess that's not really in conflict with ensuring that limit is >= request.

**Comment by rmohr** [comment]
@mlsorensen great that you brought that up.

> Yes, explicitly setting a limit works, and should be fine if there's overhead built-in. This means users who have low defaults have to always specify both memory requests and memory limits to the same value (or limit higher than requests). It works but is a bit unintuitive to users who are simply thinking in terms of "how do I set the VM's RAM".

I agree. I would even formulate it as a hard requirement that users can simply think about  "how do I set the VM's RAM". Our overhead should not be of interest to them.

In my opinion the main issue is that we even allow posting VMs which are invalid when considering the default limits. We now have the possibility to reject vms, because of the validating webhook. I think the webhook should take the overhead into account and simply reject the vm with something like:

```
invalid: spec.resources.requests: Invalid value: "610554432":
        must be less than or equal to memory limit
``` 

A few more things to make it less confusing for people:
 * Add the allowed maximum to the error message.
 * Let a modifying webhook set the maximum based on the pod default limits (this one is not yet there, but we will need it for all modifications which happend because of defaulting and presets anyway).

So step one would be adding validation with the default limits in mind, the second step would be the modifying webhook.

> I can also see the limit and request being used to set initial and max RAM for a VM with memory ballooning, but I guess that's not really in conflict with ensuring that limit is >= request.

Yes that is one of the goals to use it for ballooning too.

**Comment by mlsorensen** [comment]
Looks like "limits" aren't pulled in from VM presets, so with presets at least it can't override a low default limit.

**Comment by rmohr** [comment]
@mlsorensen maybe my comment was confusing. Nothing of what I describe above is currently happening, just in case it sounded like the presets should take the limits into account already.

**Comment by mlsorensen** [comment]
Oh no, I wasn't getting that from your comment. Just that I thought maybe this could be worked around for users via presets, adding a 'limits' in addition to the 'requests' in the preset would mean that  individual VMs would not need to specify both. 

 As it stands, if I have a 'foo' preset that 'requests' 1Gi of RAM, as a user if my default limits are small I have to still specify a 'limits' value in my VM even when using 'foo' preset. Trying to add a 'limits' to the preset to get around this does nothing. I think that's a bug, perhaps a separate issue should be created to apply limits via preset?

**Comment by vladikr** [comment]
@mlsorensen I'm wondering whether are working on this already? I'd like to start a PR, just don't to get in your way if you are planning too. :)

**Comment by nellyc** [comment]
@fabiand we marked it for 1.1, let us know if you disagree

**Comment by fabiand** [comment]
Another aspect to this is that the cluster defaults are not visible in the VM spec i.e. if as in the example the limits are set, the limits will not turn up on the vm spec, only on the vmpod.

We could however also respect those limits with kubevirt and add them to the VM spec in order to make this at least visible (that defaults were applied).
