### ISSUE TITLE
Force restart VM expose the risk of data corruption

### ISSUE THREAD

**Issue by xiesheng211** [kubevirt/kubevirt#9830]
**What happened**:
When VM get force restarted with GracePeriod == 0, the virt-launcher will get force deleted.
[Code link](https://github.com/kubevirt/kubevirt/blob/fceb5249e38ace6904bc2d0357b96a5d44911612/pkg/virt-api/rest/subresource.go#L440)

This could cause potential corruption if triggered when the node is under partition, which causes two VMs running at same time.

**What you expected to happen**:
SIGKILL should succeed when tearing down the VM.

One way to workaround is to set GracePeriod = 1, which is similar workaround as kubectl ([link](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/delete/delete.go#L187))

cc. @rmohr

**Comment by xpivarc** [comment]
I believe this is expected behavior. What do you mean by `SIGKILL should succeed when tearing down the VM.`?

**Comment by rmohr** [comment]
I think the issue is  that it behaves like `kubectl delete pods --grace-period 0 --force`. It is basically not waiting for kubelet confirmation. So, if the kubelet is slow or unresponsive, we risk a split-brain scenario. I don't think this is what we intend to express with a forced restart. I think we just want to express: "Don't wait for a clean shutdown. I want to press the reset button.".

I think, as outlined by @xiesheng211, going with a grace period of 1 would be more what users would understand as a force-restart: If they system is unhealthy (e.g. node unresponsive), the pod will still be stuck until a force delete, in any other case, it would still restart practically right away.

**Comment by rmohr** [comment]
> I see your point. We don't wait for confirmation that the Pod was deleted.

@xpivarc Does it sound reasonable to internally on the pod delete transform the 0 request into a 1 request?
